#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

namespace Params
{

struct ULayersBlueprintLibrary_RemoveActorFromLayer final
{
public:
	class AActor*                                     InActor;
	struct FActorLayer                                Layer;
};

struct ULayersBlueprintLibrary_GetActors final
{
public:
	class UObject*                                    WorldContextObject;
	struct FActorLayer                                ActorLayer;
	TArray<class AActor*>                             ReturnValue;
};

struct ULayersBlueprintLibrary_AddActorToLayer final
{
public:
	class AActor*                                     InActor;
	struct FActorLayer                                Layer;
};

}
}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
