// generated by beardumper

#include "../SDK.hpp"

namespace SDK
{

void ULayersBlueprintLibrary::RemoveActorFromLayer(class AActor* InActor, struct FActorLayer* Layer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LayersBlueprintLibrary", "RemoveActorFromLayer");

	Params::ULayersBlueprintLibrary_RemoveActorFromLayer Parms{};
	Parms.InActor = InActor;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (Layer != nullptr)
		*Layer = Parms.Layer;
}

TArray<class AActor*> ULayersBlueprintLibrary::GetActors(class UObject* WorldContextObject, struct FActorLayer* ActorLayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LayersBlueprintLibrary", "GetActors");

	Params::ULayersBlueprintLibrary_GetActors Parms{};
	Parms.WorldContextObject = WorldContextObject;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (ActorLayer != nullptr)
		*ActorLayer = Parms.ActorLayer;

	return Parms.ReturnValue;
}

void ULayersBlueprintLibrary::AddActorToLayer(class AActor* InActor, struct FActorLayer* Layer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LayersBlueprintLibrary", "AddActorToLayer");

	Params::ULayersBlueprintLibrary_AddActorToLayer Parms{};
	Parms.InActor = InActor;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (Layer != nullptr)
		*Layer = Parms.Layer;
}

}
