// generated by beardumper

#include "../SDK.hpp"

namespace SDK
{

void UActorSequenceComponent::StopSequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("ActorSequenceComponent", "StopSequence");

	SDK::Rt::ProcessEvent(this, Func, nullptr);
}

void UActorSequenceComponent::PlaySequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("ActorSequenceComponent", "PlaySequence");

	SDK::Rt::ProcessEvent(this, Func, nullptr);
}

void UActorSequenceComponent::PauseSequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("ActorSequenceComponent", "PauseSequence");

	SDK::Rt::ProcessEvent(this, Func, nullptr);
}

}
