#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

enum class EAudioDeviceChangedRole : uint8
{
	Invalid                                   = 0,
	Console                                   = 1,
	Multimedia                                = 2,
	Communications                            = 3,
	Count                                     = 4,
	EAudioDeviceChangedRole_MAX               = 5,
};

enum class EAudioDeviceChangedState : uint8
{
	Invalid                                   = 0,
	Active                                    = 1,
	Disabled                                  = 2,
	NotPresent                                = 3,
	Unplugged                                 = 4,
	Count                                     = 5,
	EAudioDeviceChangedState_MAX              = 6,
};

enum class EAudioMixerChannelType : uint8
{
	FrontLeft                                 = 0,
	FrontRight                                = 1,
	FrontCenter                               = 2,
	LowFrequency                              = 3,
	BackLeft                                  = 4,
	BackRight                                 = 5,
	FrontLeftOfCenter                         = 6,
	FrontRightOfCenter                        = 7,
	BackCenter                                = 8,
	SideLeft                                  = 9,
	SideRight                                 = 10,
	TopCenter                                 = 11,
	TopFrontLeft                              = 12,
	TopFrontCenter                            = 13,
	TopFrontRight                             = 14,
	TopBackLeft                               = 15,
	TopBackCenter                             = 16,
	TopBackRight                              = 17,
	Unknown                                   = 18,
	ChannelTypeCount                          = 19,
	DefaultChannel                            = 0,
	EAudioMixerChannelType_MAX                = 20,
};

enum class EAudioMixerStreamDataFormatType : uint8
{
	Unknown                                   = 0,
	Float                                     = 1,
	Int16                                     = 2,
	Unsupported                               = 3,
	EAudioMixerStreamDataFormatType_MAX       = 4,
};

enum class ESwapAudioOutputDeviceResultState : uint8
{
	Failure                                   = 0,
	Success                                   = 1,
	None                                      = 2,
	ESwapAudioOutputDeviceResultState_MAX     = 3,
};

enum class ESourceManagerRenderThreadPhase : uint8
{
	Begin                                     = 0,
	PumpMpscCmds                              = 1,
	PumpCmds                                  = 2,
	ProcessModulators                         = 3,
	UpdatePendingReleaseData                  = 4,
	GenerateSrcAudio_WithBusses               = 5,
	ComputeBusses                             = 6,
	GenerateSrcAudio_WithoutBusses            = 7,
	UpdateBusses                              = 8,
	SpatialInterface_OnAllSourcesProcessed    = 9,
	SourceDataOverride_OnAllSourcesProcessed  = 10,
	UpdateGameThreadCopies                    = 11,
	Finished                                  = 12,
	ESourceManagerRenderThreadPhase_MAX       = 13,
};

enum class EMusicalNoteName : uint8
{
	C                                         = 0,
	Db                                        = 1,
	D                                         = 2,
	Eb                                        = 3,
	E                                         = 4,
	F                                         = 5,
	Gb                                        = 6,
	G                                         = 7,
	Ab                                        = 8,
	A                                         = 9,
	Bb                                        = 10,
	B                                         = 11,
	EMusicalNoteName_MAX                      = 12,
};

enum class ESubmixEffectDynamicsProcessorType : uint8
{
	Compressor                                = 0,
	Limiter                                   = 1,
	Expander                                  = 2,
	Gate                                      = 3,
	UpwardsCompressor                         = 4,
	Count                                     = 5,
	ESubmixEffectDynamicsProcessorType_MAX    = 6,
};

enum class ESubmixEffectDynamicsPeakMode : uint8
{
	MeanSquared                               = 0,
	RootMeanSquared                           = 1,
	Peak                                      = 2,
	Count                                     = 3,
	ESubmixEffectDynamicsPeakMode_MAX         = 4,
};

enum class ESubmixEffectDynamicsChannelLinkMode : uint8
{
	Disabled                                  = 0,
	Average                                   = 1,
	Peak                                      = 2,
	Count                                     = 3,
	ESubmixEffectDynamicsChannelLinkMode_MAX  = 4,
};

enum class ESubmixEffectDynamicsKeySource : uint8
{
	Default                                   = 0,
	AudioBus                                  = 1,
	Submix                                    = 2,
	Count                                     = 3,
	ESubmixEffectDynamicsKeySource_MAX        = 4,
};

struct FAudioOutputDeviceInfo
{
public:
	class FString                                     Name;
	class FString                                     DeviceId;
	int32                                             NumChannels;
	int32                                             SampleRate;
	enum class EEAudioMixerStreamDataFormatType       Format;
	uint8                                             Pad_0[0x0007];
	TArray<enum class EEAudioMixerChannelType>        OutputChannelArray;
	uint8                                             bIsSystemDefault : 1;
	uint8                                             bIsCurrentDevice : 1;
	uint8                                             BitPad_0 : 6;
	uint8                                             Pad_1[0x0007];
};

struct FSwapAudioOutputResult
{
public:
	class FString                                     CurrentDeviceId;
	class FString                                     RequestedDeviceId;
	enum class EESwapAudioOutputDeviceResultState     Result;
	uint8                                             Pad_0[0x0007];
};

struct FSubmixEffectDynamicProcessorFilterSettings
{
public:
	uint8                                             bEnabled : 1;
	uint8                                             BitPad_0 : 7;
	uint8                                             Pad_0[0x0003];
	float                                             Cutoff;
	float                                             GainDb;
};

struct FSubmixEffectDynamicsProcessorSettings
{
public:
	enum class EESubmixEffectDynamicsProcessorType    DynamicsProcessorType;
	enum class EESubmixEffectDynamicsPeakMode         PeakMode;
	enum class EESubmixEffectDynamicsChannelLinkMode  LinkMode;
	uint8                                             Pad_0[0x0001];
	float                                             InputGainDb;
	float                                             ThresholdDb;
	float                                             Ratio;
	float                                             KneeBandwidthDb;
	float                                             LookAheadMsec;
	float                                             AttackTimeMsec;
	float                                             ReleaseTimeMsec;
	enum class EESubmixEffectDynamicsKeySource        KeySource;
	uint8                                             Pad_1[0x0007];
	class UAudioBus*                                  ExternalAudioBus;
	class USoundSubmix*                               ExternalSubmix;
	uint8                                             bChannelLinked : 1;
	uint8                                             bAnalogMode : 1;
	uint8                                             bBypass : 1;
	uint8                                             bKeyAudition : 1;
	uint8                                             BitPad_0 : 4;
	uint8                                             Pad_2[0x0003];
	float                                             KeyGainDb;
	float                                             OutputGainDb;
	struct FSubmixEffectDynamicProcessorFilterSettings KeyHighshelf;
	struct FSubmixEffectDynamicProcessorFilterSettings KeyLowshelf;
	uint8                                             Pad_3[0x0004];
};

struct FSubmixEffectEQBand
{
public:
	float                                             Frequency;
	float                                             Bandwidth;
	float                                             GainDb;
	uint8                                             bEnabled : 1;
	uint8                                             BitPad_0 : 7;
	uint8                                             Pad_0[0x0003];
};

struct FSubmixEffectSubmixEQSettings
{
public:
	TArray<struct FSubmixEffectEQBand>                EQBands;
};

struct FSubmixEffectReverbSettings
{
public:
	bool                                              bBypassEarlyReflections;
	uint8                                             Pad_0[0x0003];
	float                                             ReflectionsDelay;
	float                                             GainHF;
	float                                             ReflectionsGain;
	bool                                              bBypassLateReflections;
	uint8                                             Pad_1[0x0003];
	float                                             LateDelay;
	float                                             DecayTime;
	float                                             Density;
	float                                             Diffusion;
	float                                             AirAbsorptionGainHF;
	float                                             DecayHFRatio;
	float                                             LateGain;
	float                                             Gain;
	float                                             WetLevel;
	float                                             DryLevel;
	bool                                              bBypass;
	uint8                                             Pad_2[0x0003];
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
