#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

namespace Params
{

struct UAudioCapture_IsCapturingAudio final
{
public:
	bool                                              ReturnValue;
};

struct UAudioCapture_GetAudioCaptureDeviceInfo final
{
public:
	struct FAudioCaptureDeviceInfo                    OutInfo;
	bool                                              ReturnValue;
};

struct UAudioCaptureFunctionLibrary_CreateAudioCapture final
{
public:
	class UAudioCapture*                              ReturnValue;
};

struct UAudioCaptureBlueprintLibrary_GetAvailableAudioInputDevices final
{
public:
	class UObject*                                    WorldContextObject;
	struct FDelegateProperty_                         OnObtainDevicesEvent;
};

struct UAudioCaptureBlueprintLibrary_Conv_AudioInputDeviceInfoToString final
{
public:
	struct FAudioInputDeviceInfo                      info;
	class FString                                     ReturnValue;
};

}
}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
