#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class UClothConfigNv : public UClothConfigCommon
{
public:
	enum class EEClothingWindMethodNv                 ClothingWindMethod;
	uint8                                             Pad_0[0x0003];
	struct FClothConstraintSetupNv                    VerticalConstraint;
	struct FClothConstraintSetupNv                    HorizontalConstraint;
	struct FClothConstraintSetupNv                    BendConstraint;
	struct FClothConstraintSetupNv                    ShearConstraint;
	float                                             SelfCollisionRadius;
	float                                             SelfCollisionStiffness;
	float                                             SelfCollisionCullScale;
	struct FVector                                    Damping;
	float                                             Friction;
	float                                             WindDragCoefficient;
	float                                             WindLiftCoefficient;
	uint8                                             Pad_1[0x0004];
	struct FVector                                    LinearDrag;
	struct FVector                                    AngularDrag;
	struct FVector                                    LinearInertiaScale;
	struct FVector                                    AngularInertiaScale;
	struct FVector                                    CentrifugalInertiaScale;
	float                                             SolverFrequency;
	float                                             StiffnessFrequency;
	float                                             GravityScale;
	uint8                                             Pad_2[0x0004];
	struct FVector                                    GravityOverride;
	bool                                              bUseGravityOverride;
	uint8                                             Pad_3[0x0003];
	float                                             TetherStiffness;
	float                                             TetherLimit;
	float                                             CollisionThickness;
	float                                             AnimDriveSpringStiffness;
	float                                             AnimDriveDamperStiffness;
	enum class EEClothingWindMethod_Legacy            WindMethod;
	uint8                                             Pad_4[0x0003];
	struct FClothConstraintSetup_Legacy               VerticalConstraintConfig;
	struct FClothConstraintSetup_Legacy               HorizontalConstraintConfig;
	struct FClothConstraintSetup_Legacy               BendConstraintConfig;
	struct FClothConstraintSetup_Legacy               ShearConstraintConfig;
	uint8                                             Pad_5[0x0004];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ClothConfigNv");
		return Clss;
	}
};

class UClothingSimulationFactoryNv : public UClothingSimulationFactory
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ClothingSimulationFactoryNv");
		return Clss;
	}
};

class UClothingSimulationInteractorNv : public UClothingSimulationInteractor
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ClothingSimulationInteractorNv");
		return Clss;
	}

	void SetAnimDriveDamperStiffness(float InStiffness);
};

class UClothPhysicalMeshDataNv_Legacy : public UClothPhysicalMeshDataBase_Legacy
{
public:
	TArray<float>                                     MaxDistances;
	TArray<float>                                     BackstopDistances;
	TArray<float>                                     BackstopRadiuses;
	TArray<float>                                     AnimDriveMultipliers;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ClothPhysicalMeshDataNv_Legacy");
		return Clss;
	}
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
