#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

struct FClothCollisionPrim_Sphere
{
public:
	int32                                             BoneIndex;
	float                                             Radius;
	struct FVector                                    LocalPosition;
};

struct FClothCollisionPrim_SphereConnection
{
public:
	int32                                             SphereIndices[0x02];
};

struct FClothCollisionPrim_ConvexFace
{
public:
	struct FPlane                                     Plane;
	TArray<int32>                                     Indices;
};

struct FClothCollisionPrim_Convex
{
public:
	TArray<struct FClothCollisionPrim_ConvexFace>     Faces;
	TArray<struct FVector>                            SurfacePoints;
	int32                                             BoneIndex;
	uint8                                             Pad_0[0x0004];
};

struct FClothCollisionPrim_Box
{
public:
	struct FVector                                    LocalPosition;
	uint8                                             Pad_0[0x0008];
	struct FQuat                                      LocalRotation;
	struct FVector                                    HalfExtents;
	int32                                             BoneIndex;
	uint8                                             Pad_1[0x0004];
};

struct FClothVertBoneData
{
public:
	int32                                             NumInfluences;
	uint16                                            BoneIndices[0x0C];
	float                                             BoneWeights[0x0C];
};

struct FClothCollisionData
{
public:
	TArray<struct FClothCollisionPrim_Sphere>         Spheres;
	TArray<struct FClothCollisionPrim_SphereConnection> SphereConnections;
	TArray<struct FClothCollisionPrim_Convex>         Convexes;
	TArray<struct FClothCollisionPrim_Box>            Boxes;
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
