#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class UClothingAssetBase : public UObject
{
public:
	class FString                                     ImportedFilePath;
	struct FGuid                                      AssetGuid;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ClothingAssetBase");
		return Clss;
	}
};

class UClothConfigBase : public UObject
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ClothConfigBase");
		return Clss;
	}
};

class UClothSharedSimConfigBase : public UObject
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ClothSharedSimConfigBase");
		return Clss;
	}
};

class UClothingSimulationFactory : public UObject
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ClothingSimulationFactory");
		return Clss;
	}
};

class UClothingInteractor : public UObject
{
public:
	uint8                                             Pad_0[0x0008];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ClothingInteractor");
		return Clss;
	}
};

class UClothingSimulationInteractor : public UObject
{
public:
	TMap<class FName, class UClothingInteractor*>     ClothingInteractors;
	uint8                                             Pad_0[0x0018];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ClothingSimulationInteractor");
		return Clss;
	}

	void SetNumSubsteps(int32 NumSubsteps);
	void SetNumIterations(int32 NumIterations);
	void SetMaxNumIterations(int32 MaxNumIterations);
	void SetAnimDriveSpringStiffness(float InStiffness);
	void PhysicsAssetUpdated();
	float GetSimulationTime();
	int32 GetNumSubsteps();
	int32 GetNumKinematicParticles();
	int32 GetNumIterations();
	int32 GetNumDynamicParticles();
	int32 GetNumCloths();
	class UClothingInteractor* GetClothingInteractor(const class FString& ClothingAssetName);
	void EnableGravityOverride(struct FVector* InVector);
	void DisableGravityOverride();
	void ClothConfigUpdated();
};

class UClothPhysicalMeshDataBase_Legacy : public UObject
{
public:
	TArray<struct FVector3f>                          Vertices;
	TArray<struct FVector3f>                          Normals;
	TArray<uint32>                                    Indices;
	TArray<float>                                     InverseMasses;
	TArray<struct FClothVertBoneData>                 BoneData;
	int32                                             NumFixedVerts;
	int32                                             MaxBoneWeights;
	TArray<uint32>                                    SelfCollisionIndices;
	uint8                                             Pad_0[0x0050];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ClothPhysicalMeshDataBase_Legacy");
		return Clss;
	}
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
