#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

namespace Params
{

struct UCommonActionWidget_SetInputActions final
{
public:
	TArray<struct FDataTableRowHandle>                NewInputActions;
};

struct UCommonActionWidget_SetInputAction final
{
public:
	struct FDataTableRowHandle                        InputActionRow;
};

struct UCommonActionWidget_SetIconRimBrush final
{
public:
	struct FSlateBrush                                InIconRimBrush;
};

struct UCommonActionWidget_SetEnhancedInputAction final
{
public:
	class UInputAction*                               InInputAction;
};

struct UCommonActionWidget_IsHeldAction final
{
public:
	bool                                              ReturnValue;
};

struct UCommonActionWidget_GetIcon final
{
public:
	struct FSlateBrush                                ReturnValue;
};

struct UCommonActionWidget_GetDisplayText final
{
public:
	class FText                                       ReturnValue;
};

struct UCommonUserWidget_SetConsumePointerInput final
{
public:
	bool                                              bInConsumePointerInput;
};

struct UCommonActivatableWidget_SetBindVisibilities final
{
public:
	enum class EESlateVisibility                      OnActivatedVisibility;
	enum class EESlateVisibility                      OnDeactivatedVisibility;
	bool                                              bInAllActive;
};

struct UCommonActivatableWidget_IsActivated final
{
public:
	bool                                              ReturnValue;
};

struct UCommonActivatableWidget_GetDesiredFocusTarget final
{
public:
	class UWidget*                                    ReturnValue;
};

struct UCommonActivatableWidget_BP_OnHandleBackAction final
{
public:
	bool                                              ReturnValue;
};

struct UCommonActivatableWidget_BP_GetDesiredInputConfig final
{
public:
	struct FUIInputConfig                             ReturnValue;
};

struct UCommonActivatableWidget_BP_GetDesiredFocusTarget final
{
public:
	class UWidget*                                    ReturnValue;
};

struct UCommonActivatableWidget_BindVisibilityToActivation final
{
public:
	class UCommonActivatableWidget*                   ActivatableWidget;
};

struct UCommonAnimatedSwitcher_SetDisableTransitionAnimation final
{
public:
	bool                                              bDisableAnimation;
};

struct UCommonAnimatedSwitcher_IsTransitionPlaying final
{
public:
	bool                                              ReturnValue;
};

struct UCommonAnimatedSwitcher_IsCurrentlySwitching final
{
public:
	bool                                              ReturnValue;
};

struct UCommonAnimatedSwitcher_HasWidgets final
{
public:
	bool                                              ReturnValue;
};

struct UCommonAnimatedSwitcher_ActivatePreviousWidget final
{
public:
	bool                                              bCanWrap;
};

struct UCommonAnimatedSwitcher_ActivateNextWidget final
{
public:
	bool                                              bCanWrap;
};

struct UCommonBorderStyle_GetBackgroundBrush final
{
public:
	struct FSlateBrush                                Brush;
};

struct UCommonBorder_SetStyle final
{
public:
	class UClass*                                     InStyle;
};

struct UCommonButtonStyle_GetSelectedTextStyle final
{
public:
	class UCommonTextStyle*                           ReturnValue;
};

struct UCommonButtonStyle_GetSelectedPressedBrush final
{
public:
	struct FSlateBrush                                Brush;
};

struct UCommonButtonStyle_GetSelectedHoveredTextStyle final
{
public:
	class UCommonTextStyle*                           ReturnValue;
};

struct UCommonButtonStyle_GetSelectedHoveredBrush final
{
public:
	struct FSlateBrush                                Brush;
};

struct UCommonButtonStyle_GetSelectedBaseBrush final
{
public:
	struct FSlateBrush                                Brush;
};

struct UCommonButtonStyle_GetNormalTextStyle final
{
public:
	class UCommonTextStyle*                           ReturnValue;
};

struct UCommonButtonStyle_GetNormalPressedBrush final
{
public:
	struct FSlateBrush                                Brush;
};

struct UCommonButtonStyle_GetNormalHoveredTextStyle final
{
public:
	class UCommonTextStyle*                           ReturnValue;
};

struct UCommonButtonStyle_GetNormalHoveredBrush final
{
public:
	struct FSlateBrush                                Brush;
};

struct UCommonButtonStyle_GetNormalBaseBrush final
{
public:
	struct FSlateBrush                                Brush;
};

struct UCommonButtonStyle_GetMaterialBrush final
{
public:
	struct FSlateBrush                                Brush;
};

struct UCommonButtonStyle_GetDisabledTextStyle final
{
public:
	class UCommonTextStyle*                           ReturnValue;
};

struct UCommonButtonStyle_GetDisabledBrush final
{
public:
	struct FSlateBrush                                Brush;
};

struct UCommonButtonStyle_GetCustomPadding final
{
public:
	struct FMargin                                    OutCustomPadding;
};

struct UCommonButtonStyle_GetButtonPadding final
{
public:
	struct FMargin                                    OutButtonPadding;
};

struct UCommonButtonBase_UpdateHoldData final
{
public:
	enum class EECommonInputType                      CurrentInputType;
};

struct UCommonButtonBase_SetTriggeringInputAction final
{
public:
	struct FDataTableRowHandle                        InputActionRow;
};

struct UCommonButtonBase_SetTriggeringEnhancedInputAction final
{
public:
	class UInputAction*                               InInputAction;
};

struct UCommonButtonBase_SetTriggeredInputAction final
{
public:
	struct FDataTableRowHandle                        InputActionRow;
};

struct UCommonButtonBase_SetTouchMethod final
{
public:
	enum class EEButtonTouchMethod                    InTouchMethod;
};

struct UCommonButtonBase_SetStyle final
{
public:
	class UClass*                                     InStyle;
};

struct UCommonButtonBase_SetShouldUseFallbackDefaultInputAction final
{
public:
	bool                                              bInShouldUseFallbackDefaultInputAction;
};

struct UCommonButtonBase_SetShouldSelectUponReceivingFocus final
{
public:
	bool                                              bInShouldSelectUponReceivingFocus;
};

struct UCommonButtonBase_SetSelectedPressedSoundOverride final
{
public:
	class USoundBase*                                 Sound;
};

struct UCommonButtonBase_SetSelectedInternal final
{
public:
	bool                                              bInSelected;
	bool                                              bAllowSound;
	bool                                              bBroadcast;
};

struct UCommonButtonBase_SetSelectedHoveredSoundOverride final
{
public:
	class USoundBase*                                 Sound;
};

struct UCommonButtonBase_SetPressMethod final
{
public:
	enum class EEButtonPressMethod                    InPressMethod;
};

struct UCommonButtonBase_SetPressedSoundOverride final
{
public:
	class USoundBase*                                 Sound;
};

struct UCommonButtonBase_SetMinDimensions final
{
public:
	int32                                             InMinWidth;
	int32                                             InMinHeight;
};

struct UCommonButtonBase_SetMaxDimensions final
{
public:
	int32                                             InMaxWidth;
	int32                                             InMaxHeight;
};

struct UCommonButtonBase_SetLockedPressedSoundOverride final
{
public:
	class USoundBase*                                 Sound;
};

struct UCommonButtonBase_SetLockedHoveredSoundOverride final
{
public:
	class USoundBase*                                 Sound;
};

struct UCommonButtonBase_SetIsToggleable final
{
public:
	bool                                              bInIsToggleable;
};

struct UCommonButtonBase_SetIsSelected final
{
public:
	bool                                              InSelected;
	bool                                              bGiveClickFeedback;
};

struct UCommonButtonBase_SetIsSelectable final
{
public:
	bool                                              bInIsSelectable;
};

struct UCommonButtonBase_SetIsLocked final
{
public:
	bool                                              bInIsLocked;
};

struct UCommonButtonBase_SetIsInteractionEnabled final
{
public:
	bool                                              bInIsInteractionEnabled;
};

struct UCommonButtonBase_SetIsInteractableWhenSelected final
{
public:
	bool                                              bInInteractableWhenSelected;
};

struct UCommonButtonBase_SetIsFocusable final
{
public:
	bool                                              bInIsFocusable;
};

struct UCommonButtonBase_SetInputActionProgressMaterial final
{
public:
	struct FSlateBrush                                InProgressMaterialBrush;
	class FName                                       InProgressMaterialParam;
};

struct UCommonButtonBase_SetHoveredSoundOverride final
{
public:
	class USoundBase*                                 Sound;
};

struct UCommonButtonBase_SetHideInputAction final
{
public:
	bool                                              bInHideInputAction;
};

struct UCommonButtonBase_SetClickMethod final
{
public:
	enum class EEButtonClickMethod                    InClickMethod;
};

struct UCommonButtonBase_OnTriggeringInputActionChanged final
{
public:
	struct FDataTableRowHandle                        NewTriggeredAction;
};

struct UCommonButtonBase_OnTriggeringEnhancedInputActionChanged final
{
public:
	class UInputAction*                               InInputAction;
};

struct UCommonButtonBase_OnTriggeredInputActionChanged final
{
public:
	struct FDataTableRowHandle                        NewTriggeredAction;
};

struct UCommonButtonBase_OnInputMethodChanged final
{
public:
	enum class EECommonInputType                      CurrentInputType;
};

struct UCommonButtonBase_OnActionProgress final
{
public:
	float                                             HeldPercent;
};

struct UCommonButtonBase_NativeOnHoldProgressRollback final
{
public:
	float                                             DeltaTime;
	bool                                              ReturnValue;
};

struct UCommonButtonBase_NativeOnHoldProgress final
{
public:
	float                                             DeltaTime;
	bool                                              ReturnValue;
};

struct UCommonButtonBase_NativeOnActionProgress final
{
public:
	float                                             HeldPercent;
};

struct UCommonButtonBase_IsPressed final
{
public:
	bool                                              ReturnValue;
};

struct UCommonButtonBase_IsInteractionEnabled final
{
public:
	bool                                              ReturnValue;
};

struct UCommonButtonBase_HandleTriggeringActionCommited final
{
public:
	bool                                              bPassthrough;
};

struct UCommonButtonBase_GetStyle final
{
public:
	class UCommonButtonStyle*                         ReturnValue;
};

struct UCommonButtonBase_GetSingleMaterialStyleMID final
{
public:
	class UMaterialInstanceDynamic*                   ReturnValue;
};

struct UCommonButtonBase_GetShouldSelectUponReceivingFocus final
{
public:
	bool                                              ReturnValue;
};

struct UCommonButtonBase_GetSelected final
{
public:
	bool                                              ReturnValue;
};

struct UCommonButtonBase_GetLocked final
{
public:
	bool                                              ReturnValue;
};

struct UCommonButtonBase_GetIsFocusable final
{
public:
	bool                                              ReturnValue;
};

struct UCommonButtonBase_GetInputAction final
{
public:
	struct FDataTableRowHandle                        InputActionRow;
	bool                                              ReturnValue;
};

struct UCommonButtonBase_GetEnhancedInputAction final
{
public:
	class UInputAction*                               ReturnValue;
};

struct UCommonButtonBase_GetCurrentTextStyleClass final
{
public:
	class UClass*                                     ReturnValue;
};

struct UCommonButtonBase_GetCurrentTextStyle final
{
public:
	class UCommonTextStyle*                           ReturnValue;
};

struct UCommonButtonBase_GetCurrentCustomPadding final
{
public:
	struct FMargin                                    OutCustomPadding;
};

struct UCommonButtonBase_GetCurrentButtonPadding final
{
public:
	struct FMargin                                    OutButtonPadding;
};

struct UCommonButtonBase_GetConvertInputActionToHold final
{
public:
	bool                                              ReturnValue;
};

struct UCommonButtonBase_ForceSetSelectedState final
{
public:
	bool                                              bInSelected;
};

struct UCommonButtonBase_DisableButtonWithReason final
{
public:
	class FText                                       DisabledReason;
};

struct UCommonButtonBase_BP_OnLockedChanged final
{
public:
	bool                                              bIsLocked;
};

struct UCommonButtonBase_BP_OnInputMethodChanged final
{
public:
	enum class EECommonInputType                      CurrentInputType;
};

struct UCommonTextBlock_SetWrapTextWidth final
{
public:
	int32                                             InWrapTextAt;
};

struct UCommonTextBlock_SetTextCase final
{
public:
	bool                                              bUseAllCaps;
};

struct UCommonTextBlock_SetStyle final
{
public:
	class UClass*                                     InStyle;
};

struct UCommonTextBlock_SetScrollingEnabled final
{
public:
	bool                                              bInIsScrollingEnabled;
};

struct UCommonTextBlock_SetMobileFontSizeMultiplier final
{
public:
	float                                             InMobileFontSizeMultiplier;
};

struct UCommonTextBlock_SetMargin final
{
public:
	struct FMargin                                    InMargin;
};

struct UCommonTextBlock_SetLineHeightPercentage final
{
public:
	float                                             InLineHeightPercentage;
};

struct UCommonTextBlock_GetMobileFontSizeMultiplier final
{
public:
	float                                             ReturnValue;
};

struct UCommonTextBlock_GetMargin final
{
public:
	struct FMargin                                    ReturnValue;
};

struct UCommonDateTimeTextBlock_SetTimespanValue final
{
public:
	struct FTimespan                                  InTimespan;
};

struct UCommonDateTimeTextBlock_SetDateTimeValue final
{
public:
	struct FDateTime                                  InDateTime;
	bool                                              bShowAsCountdown;
	uint8                                             Pad_0[0x0003];
	float                                             InRefreshDelay;
};

struct UCommonDateTimeTextBlock_SetCountDownCompletionText final
{
public:
	class FText                                       InCompletionText;
};

struct UCommonDateTimeTextBlock_GetDateTime final
{
public:
	struct FDateTime                                  ReturnValue;
};

struct UCommonLazyImage_SetMaterialTextureParamName final
{
public:
	class FName                                       TextureParamName;
};

struct UCommonLazyImage_SetBrushFromLazyTexture final
{
public:
	TSoftObjectPtr<class UTexture2D>                  LazyTexture;
	bool                                              bMatchSize;
};

struct UCommonLazyImage_SetBrushFromLazyMaterial final
{
public:
	TSoftObjectPtr<class UMaterialInterface>          LazyMaterial;
};

struct UCommonLazyImage_SetBrushFromLazyDisplayAsset final
{
public:
	TSoftObjectPtr<class UObject>                     LazyObject;
	bool                                              bMatchTextureSize;
};

struct UCommonLazyImage_IsLoading final
{
public:
	bool                                              ReturnValue;
};

struct UCommonLazyWidget_SetLazyContent final
{
public:
	TSoftClassPtr<class UUserWidget>                  SoftWidget;
};

struct UCommonLazyWidget_IsLoading final
{
public:
	bool                                              ReturnValue;
};

struct UCommonLazyWidget_GetContent final
{
public:
	class UUserWidget*                                ReturnValue;
};

struct UCommonListView_SetEntrySpacing final
{
public:
	float                                             InEntrySpacing;
};

struct ULoadGuardSlot_SetVerticalAlignment final
{
public:
	enum class EEVerticalAlignment                    InVerticalAlignment;
};

struct ULoadGuardSlot_SetPadding final
{
public:
	struct FMargin                                    InPadding;
};

struct ULoadGuardSlot_SetHorizontalAlignment final
{
public:
	enum class EEHorizontalAlignment                  InHorizontalAlignment;
};

struct UCommonLoadGuard_SetLoadingText final
{
public:
	class FText                                       InLoadingText;
};

struct UCommonLoadGuard_SetIsLoading final
{
public:
	bool                                              bInIsLoading;
};

struct UCommonLoadGuard_IsLoading final
{
public:
	bool                                              ReturnValue;
};

struct UCommonLoadGuard_BP_GuardAndLoadAsset final
{
public:
	TSoftObjectPtr<class UObject>                     InLazyAsset;
	struct FDelegateProperty_                         OnAssetLoaded;
};

struct UCommonNumericTextBlock_SetNumericType final
{
public:
	enum class EECommonNumericType                    InNumericType;
};

struct UCommonNumericTextBlock_SetCurrentValue final
{
public:
	float                                             NewValue;
};

struct UCommonNumericTextBlock_IsInterpolatingNumericValue final
{
public:
	bool                                              ReturnValue;
};

struct UCommonNumericTextBlock_InterpolateToValue final
{
public:
	float                                             TargetValue;
	float                                             MaximumInterpolationDuration;
	float                                             MinimumChangeRate;
	float                                             OutroOffset;
};

struct UCommonNumericTextBlock_GetTargetValue final
{
public:
	float                                             ReturnValue;
};

struct UCommonRichTextBlock_SetScrollingEnabled final
{
public:
	bool                                              bInIsScrollingEnabled;
};

struct UCommonRotator_SetSelectedItem final
{
public:
	int32                                             InValue;
};

struct UCommonRotator_PopulateTextLabels final
{
public:
	TArray<class FText>                               Labels;
};

struct UCommonRotator_GetSelectedText final
{
public:
	class FText                                       ReturnValue;
};

struct UCommonRotator_GetSelectedIndex final
{
public:
	int32                                             ReturnValue;
};

struct UCommonRotator_BP_OnOptionsPopulated final
{
public:
	int32                                             Count;
};

struct UCommonRotator_BP_OnOptionSelected final
{
public:
	int32                                             Index;
};

struct UCommonTabListWidgetBase_SetTabVisibility final
{
public:
	class FName                                       TabNameID;
	enum class EESlateVisibility                      NewVisibility;
};

struct UCommonTabListWidgetBase_SetTabInteractionEnabled final
{
public:
	class FName                                       TabNameID;
	bool                                              bEnable;
};

struct UCommonTabListWidgetBase_SetTabEnabled final
{
public:
	class FName                                       TabNameID;
	bool                                              bEnable;
};

struct UCommonTabListWidgetBase_SetListeningForInput final
{
public:
	bool                                              bShouldListen;
};

struct UCommonTabListWidgetBase_SetLinkedSwitcher final
{
public:
	class UCommonAnimatedSwitcher*                    CommonSwitcher;
};

struct UCommonTabListWidgetBase_SelectTabByID final
{
public:
	class FName                                       TabNameID;
	bool                                              bSuppressClickFeedback;
	bool                                              ReturnValue;
};

struct UCommonTabListWidgetBase_RemoveTab final
{
public:
	class FName                                       TabNameID;
	bool                                              ReturnValue;
};

struct UCommonTabListWidgetBase_RegisterTab final
{
public:
	class FName                                       TabNameID;
	uint8                                             Pad_0[0x0004];
	class UClass*                                     ButtonWidgetType;
	class UWidget*                                    ContentWidget;
	int32                                             TabIndex;
	bool                                              ReturnValue;
};

struct UCommonTabListWidgetBase_HandleTabRemoval final
{
public:
	class FName                                       TabNameID;
	uint8                                             Pad_0[0x0004];
	class UCommonButtonBase*                          TabButton;
};

struct UCommonTabListWidgetBase_HandleTabCreation final
{
public:
	class FName                                       TabNameID;
	uint8                                             Pad_0[0x0004];
	class UCommonButtonBase*                          TabButton;
};

struct UCommonTabListWidgetBase_HandleTabButtonSelected final
{
public:
	class UCommonButtonBase*                          SelectedTabButton;
	int32                                             ButtonIndex;
};

struct UCommonTabListWidgetBase_HandlePreviousTabInputAction final
{
public:
	bool                                              bPassthrough;
};

struct UCommonTabListWidgetBase_HandleNextTabInputAction final
{
public:
	bool                                              bPassthrough;
};

struct UCommonTabListWidgetBase_GetTabIdAtIndex final
{
public:
	int32                                             Index;
	class FName                                       ReturnValue;
};

struct UCommonTabListWidgetBase_GetTabCount final
{
public:
	int32                                             ReturnValue;
};

struct UCommonTabListWidgetBase_GetTabButtonBaseByID final
{
public:
	class FName                                       TabNameID;
	class UCommonButtonBase*                          ReturnValue;
};

struct UCommonTabListWidgetBase_GetSelectedTabId final
{
public:
	class FName                                       ReturnValue;
};

struct UCommonTabListWidgetBase_GetLinkedSwitcher final
{
public:
	class UCommonAnimatedSwitcher*                    ReturnValue;
};

struct UCommonTabListWidgetBase_GetActiveTab final
{
public:
	class FName                                       ReturnValue;
};

struct UCommonTabListWidgetBase_DisableTabWithReason final
{
public:
	class FName                                       TabNameID;
	uint8                                             Pad_0[0x0004];
	class FText                                       Reason;
};

struct UCommonTextStyle_GetStrikeBrush final
{
public:
	struct FSlateBrush                                OutStrikeBrush;
};

struct UCommonTextStyle_GetShadowOffset final
{
public:
	struct FVector2D                                  OutShadowOffset;
};

struct UCommonTextStyle_GetShadowColor final
{
public:
	struct FLinearColor                               OutColor;
};

struct UCommonTextStyle_GetMargin final
{
public:
	struct FMargin                                    OutMargin;
};

struct UCommonTextStyle_GetLineHeightPercentage final
{
public:
	float                                             ReturnValue;
};

struct UCommonTextStyle_GetFont final
{
public:
	struct FSlateFontInfo                             OutFont;
};

struct UCommonTextStyle_GetColor final
{
public:
	struct FLinearColor                               OutColor;
};

struct UCommonUILibrary_FindParentWidgetOfType final
{
public:
	class UWidget*                                    StartingWidget;
	class UClass*                                     Type;
	class UWidget*                                    ReturnValue;
};

struct UCommonUISubsystemBase_GetInputActionButtonIcon final
{
public:
	struct FDataTableRowHandle                        InputActionRowHandle;
	enum class EECommonInputType                      InputType;
	uint8                                             Pad_0[0x0003];
	class FName                                       GamepadName;
	struct FSlateBrush                                ReturnValue;
};

struct UCommonUISubsystemBase_GetEnhancedInputActionButtonIcon final
{
public:
	class UInputAction*                               InputAction;
	class ULocalPlayer*                               LocalPlayer;
	struct FSlateBrush                                ReturnValue;
};

struct UCommonVisibilitySwitcher_SetActiveWidgetIndex final
{
public:
	int32                                             Index;
};

struct UCommonVisibilitySwitcher_SetActiveWidget final
{
public:
	class UWidget*                                    Widget;
};

struct UCommonVisibilitySwitcher_IncrementActiveWidgetIndex final
{
public:
	bool                                              bAllowWrapping;
};

struct UCommonVisibilitySwitcher_GetActiveWidgetIndex final
{
public:
	int32                                             ReturnValue;
};

struct UCommonVisibilitySwitcher_GetActiveWidget final
{
public:
	class UWidget*                                    ReturnValue;
};

struct UCommonVisibilitySwitcher_DecrementActiveWidgetIndex final
{
public:
	bool                                              bAllowWrapping;
};

struct UUCommonVisibilityWidgetBase_GetRegisteredPlatforms final
{
public:
	TArray<class FName>                               ReturnValue;
};

struct UCommonWidgetCarousel_SetActiveWidgetIndex final
{
public:
	int32                                             Index;
};

struct UCommonWidgetCarousel_SetActiveWidget final
{
public:
	class UWidget*                                    Widget;
};

struct UCommonWidgetCarousel_GetWidgetAtIndex final
{
public:
	int32                                             Index;
	class UWidget*                                    ReturnValue;
};

struct UCommonWidgetCarousel_GetActiveWidgetIndex final
{
public:
	int32                                             ReturnValue;
};

struct UCommonWidgetCarousel_BeginAutoScrolling final
{
public:
	float                                             ScrollInterval;
};

struct UCommonWidgetCarouselNavBar_SetLinkedCarousel final
{
public:
	class UCommonWidgetCarousel*                      CommonCarousel;
};

struct UCommonWidgetCarouselNavBar_HandlePageChanged final
{
public:
	class UCommonWidgetCarousel*                      CommonCarousel;
	int32                                             PageIndex;
};

struct UCommonWidgetCarouselNavBar_HandleButtonClicked final
{
public:
	class UCommonButtonBase*                          AssociatedButton;
	int32                                             ButtonIndex;
};

struct UCommonWidgetGroupBase_RemoveWidget final
{
public:
	class UWidget*                                    InWidget;
};

struct UCommonWidgetGroupBase_AddWidget final
{
public:
	class UWidget*                                    InWidget;
};

struct UCommonButtonGroupBase_SetSelectionRequired final
{
public:
	bool                                              bRequireSelection;
};

struct UCommonButtonGroupBase_SelectPreviousButton final
{
public:
	bool                                              bAllowWrap;
};

struct UCommonButtonGroupBase_SelectNextButton final
{
public:
	bool                                              bAllowWrap;
};

struct UCommonButtonGroupBase_SelectButtonAtIndex final
{
public:
	int32                                             ButtonIndex;
	bool                                              bAllowSound;
};

struct UCommonButtonGroupBase_OnSelectionStateChangedBase final
{
public:
	class UCommonButtonBase*                          BaseButton;
	bool                                              bIsSelected;
};

struct UCommonButtonGroupBase_OnHandleButtonBaseDoubleClicked final
{
public:
	class UCommonButtonBase*                          BaseButton;
};

struct UCommonButtonGroupBase_OnHandleButtonBaseClicked final
{
public:
	class UCommonButtonBase*                          BaseButton;
};

struct UCommonButtonGroupBase_OnButtonBaseUnhovered final
{
public:
	class UCommonButtonBase*                          BaseButton;
};

struct UCommonButtonGroupBase_OnButtonBaseHovered final
{
public:
	class UCommonButtonBase*                          BaseButton;
};

struct UCommonButtonGroupBase_HasAnyButtons final
{
public:
	bool                                              ReturnValue;
};

struct UCommonButtonGroupBase_GetSelectedButtonIndex final
{
public:
	int32                                             ReturnValue;
};

struct UCommonButtonGroupBase_GetSelectedButtonBase final
{
public:
	class UCommonButtonBase*                          ReturnValue;
};

struct UCommonButtonGroupBase_GetHoveredButtonIndex final
{
public:
	int32                                             ReturnValue;
};

struct UCommonButtonGroupBase_GetButtonCount final
{
public:
	int32                                             ReturnValue;
};

struct UCommonButtonGroupBase_GetButtonBaseAtIndex final
{
public:
	int32                                             Index;
	class UCommonButtonBase*                          ReturnValue;
};

struct UCommonButtonGroupBase_FindButtonIndex final
{
public:
	class UCommonButtonBase*                          ButtonToFind;
	int32                                             ReturnValue;
};

struct UCommonBoundActionBar_SetDisplayOwningPlayerActionsOnly final
{
public:
	bool                                              bShouldOnlyDisplayOwningPlayerActions;
};

struct UCommonActivatableWidgetContainerBase_SetTransitionDuration final
{
public:
	float                                             Duration;
};

struct UCommonActivatableWidgetContainerBase_RemoveWidget final
{
public:
	class UCommonActivatableWidget*                   WidgetToRemove;
};

struct UCommonActivatableWidgetContainerBase_GetTransitionDuration final
{
public:
	float                                             ReturnValue;
};

struct UCommonActivatableWidgetContainerBase_GetActiveWidget final
{
public:
	class UCommonActivatableWidget*                   ReturnValue;
};

struct UCommonActivatableWidgetContainerBase_BP_AddWidget final
{
public:
	class UClass*                                     ActivatableWidgetClass;
	class UCommonActivatableWidget*                   ReturnValue;
};

}
}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
