#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class UCoreSDKUtilsBlueprintLibrary : public UBlueprintFunctionLibrary
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("CoreSDKUtilsBlueprintLibrary");
		return Clss;
	}

	static bool IsPlatformIOS();
	static bool IsPlatformAndroid();
	static bool IsMobile();
	static bool IsBuildFromCI();
	static bool IsAutomationWorker();
	static bool IsAutomationMonitor();
	static class FString GetProjectVersionString();
	static class FString GetProjectName();
	static class FString GetPatchline();
	static class FString GetFullVersionString();
	static class FString GetCoreSDKVersionString();
	static class FString GetClientPatchline();
	static struct FDateTime GetBuildTime();
	static class FString GetBuildTargetType();
	static int32 GetBuildNumber();
	static class FString GetBuildConfiguration();
	static int32 GetBuildCompatibleChangelist();
	static int32 GetBuildChangelist();
	static class FString GetBuildBranch();
};

class UCoreSDKUtilsConfig : public UObject
{
public:
	class FString                                     CoreSDKVersion;
	int32                                             BuildNumber;
	uint8                                             Pad_0[0x0004];
	class FString                                     BuildTime;
	int32                                             Change;
	int32                                             CodeChange;
	class FString                                     Branch;
	class FString                                     TeamName;
	bool                                              bManageCrashData;
	bool                                              bCrashDataIncludesBuildInfo;
	bool                                              bCrashDataIncludesUserIdentification;
	uint8                                             Pad_1[0x0005];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("CoreSDKUtilsConfig");
		return Clss;
	}
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
