#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

struct FFloatOverrideDataflowNode : public FDataflowNode
{
public:
	class FName                                       PropertyName;
	class FName                                       KeyName;
	float                                             ValueOut;
	uint8                                             Pad_0[0x0004];
};

struct FSelectionSetDataflowNode : public FDataflowNode
{
public:
	class FString                                     Indices;
	TArray<int32>                                     IndicesOut;
};

struct FGetSkeletalMeshDataflowNode : public FDataflowNode
{
public:
	class USkeletalMesh*                              SkeletalMesh;
	class FName                                       PropertyName;
	uint8                                             Pad_0[0x0004];
};

struct FGetSkeletonDataflowNode : public FDataflowNode
{
public:
	class USkeleton*                                  Skeleton;
	class FName                                       PropertyName;
	uint8                                             Pad_0[0x0004];
};

struct FSkeletalMeshBoneDataflowNode : public FDataflowNode
{
public:
	class FName                                       BoneName;
	uint8                                             Pad_0[0x0004];
	class USkeletalMesh*                              SkeletalMesh;
	int32                                             BoneIndexOut;
	class FName                                       PropertyName;
};

struct FSkeletalMeshReferenceTransformDataflowNode : public FDataflowNode
{
public:
	class USkeletalMesh*                              SkeletalMeshIn;
	int32                                             BoneIndexIn;
	uint8                                             Pad_0[0x0004];
	struct FTransform                                 TransformOut;
};

struct FGetStaticMeshDataflowNode : public FDataflowNode
{
public:
	class UStaticMesh*                                StaticMesh;
	class FName                                       PropertyName;
	uint8                                             Pad_0[0x0004];
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
