#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class UAudioCurveSourceComponent : public UAudioComponent
{
public:
	uint8                                             Pad_0[0x0008];
	class FName                                       CurveSourceBindingName;
	float                                             CurveSyncOffset;
	uint8                                             Pad_1[0x0028];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("AudioCurveSourceComponent");
		return Clss;
	}
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
