#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

struct FFieldNotificationId
{
public:
	class FName                                       FieldName;
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
