#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

enum class EOscillatorWaveform : uint8
{
	SineWave                                  = 0,
	PerlinNoise                               = 1,
	EOscillatorWaveform_MAX                   = 2,
};

enum class EInitialOscillatorOffset : uint8
{
	EOO_OffsetRandom                          = 0,
	EOO_OffsetZero                            = 1,
	EOO_OffsetMax                             = 2,
	EOO_MAX                                   = 3,
};

enum class ECameraAnimationPlaySpace : uint8
{
	CameraLocal                               = 0,
	World                                     = 1,
	UserDefined                               = 2,
	ECameraAnimationPlaySpace_MAX             = 3,
};

enum class ECameraAnimationEasingType : uint8
{
	Linear                                    = 0,
	Sinusoidal                                = 1,
	Quadratic                                 = 2,
	Cubic                                     = 3,
	Quartic                                   = 4,
	Quintic                                   = 5,
	Exponential                               = 6,
	Circular                                  = 7,
	ECameraAnimationEasingType_MAX            = 8,
};

enum class EInitialWaveOscillatorOffsetType : uint8
{
	Random                                    = 0,
	Zero                                      = 1,
	EInitialWaveOscillatorOffsetType_MAX      = 2,
};

struct FFOscillator
{
public:
	float                                             Amplitude;
	float                                             Frequency;
	enum class EEInitialOscillatorOffset              InitialOffset;
	enum class EEOscillatorWaveform                   Waveform;
	uint8                                             Pad_0[0x0002];
};

struct FROscillator
{
public:
	struct FFOscillator                               Pitch;
	struct FFOscillator                               Yaw;
	struct FFOscillator                               Roll;
};

struct FVOscillator
{
public:
	struct FFOscillator                               X;
	struct FFOscillator                               Y;
	struct FFOscillator                               Z;
};

struct FCameraAnimationParams
{
public:
	float                                             PlayRate;
	float                                             Scale;
	enum class EECameraAnimationEasingType            EaseInType;
	uint8                                             Pad_0[0x0003];
	float                                             EaseInDuration;
	enum class EECameraAnimationEasingType            EaseOutType;
	uint8                                             Pad_1[0x0003];
	float                                             EaseOutDuration;
	bool                                              bLoop;
	uint8                                             Pad_2[0x0003];
	int32                                             StartOffset;
	bool                                              bRandomStartTime;
	uint8                                             Pad_3[0x0003];
	float                                             DurationOverride;
	enum class EECameraAnimationPlaySpace             PlaySpace;
	uint8                                             Pad_4[0x0007];
	struct FRotator                                   UserPlaySpaceRot;
};

struct FCameraAnimationHandle
{
public:
	uint8                                             Pad_0[0x0004];
};

struct FActiveCameraAnimationInfo
{
public:
	class UCameraAnimationSequence*                   Sequence;
	struct FCameraAnimationParams                     Params;
	struct FCameraAnimationHandle                     Handle;
	uint8                                             Pad_0[0x0004];
	class UCameraAnimationSequencePlayer*             Player;
	class UCameraAnimationSequenceCameraStandIn*      CameraStandIn;
	float                                             EaseInCurrentTime;
	float                                             EaseOutCurrentTime;
	bool                                              bIsEasingIn;
	bool                                              bIsEasingOut;
	uint8                                             Pad_1[0x0006];
};

struct FPerlinNoiseShaker
{
public:
	float                                             Amplitude;
	float                                             Frequency;
};

struct FWaveOscillator
{
public:
	float                                             Amplitude;
	float                                             Frequency;
	enum class EEInitialWaveOscillatorOffsetType      InitialOffsetType;
	uint8                                             Pad_0[0x0003];
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
