#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class UGameplayTask : public UObject
{
public:
	uint8                                             Pad_0[0x0008];
	class FName                                       InstanceName;
	uint8                                             Pad_1[0x0002];
	enum class EETaskResourceOverlapPolicy            ResourceOverlapPolicy;
	uint8                                             Pad_2[0x0021];
	class UGameplayTask*                              ChildTask;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GameplayTask");
		return Clss;
	}

	void ReadyForActivation();
	void EndTask();
};

class UGameplayTaskOwnerInterface : public UInterface
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GameplayTaskOwnerInterface");
		return Clss;
	}
};

class UGameplayTaskResource : public UObject
{
public:
	int32                                             ManualResourceID;
	int8                                              AutoResourceID;
	uint8                                             Pad_0[0x0003];
	uint8                                             bManuallySetID : 1;
	uint8                                             BitPad_0 : 7;
	uint8                                             Pad_1[0x0007];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GameplayTaskResource");
		return Clss;
	}
};

class UGameplayTasksComponent : public UActorComponent
{
public:
	uint8                                             Pad_0[0x0018];
	TArray<class UGameplayTask*>                      TaskPriorityQueue;
	uint8                                             Pad_1[0x0010];
	TArray<class UGameplayTask*>                      TickingTasks;
	TArray<class UGameplayTask*>                      KnownTasks;
	struct FMulticastInlineDelegateProperty_          OnClaimedResourcesChange;
	TArray<class UGameplayTask*>                      SimulatedTasks;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GameplayTasksComponent");
		return Clss;
	}

	void OnRep_SimulatedTasks(TArray<class UGameplayTask*>* PreviousSimulatedTasks);
	static enum class EEGameplayTaskRunResult K2_RunGameplayTask(TScriptInterface<class IGameplayTaskOwnerInterface> TaskOwner, class UGameplayTask* Task, uint8 Priority, const TArray<class UClass*>& AdditionalRequiredResources, const TArray<class UClass*>& AdditionalClaimedResources);
};

class UGameplayTask_ClaimResource : public UGameplayTask
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GameplayTask_ClaimResource");
		return Clss;
	}

	static class UGameplayTask_ClaimResource* ClaimResources(TScriptInterface<class IGameplayTaskOwnerInterface> InTaskOwner, const TArray<class UClass*>& ResourceClasses, uint8 Priority, const class FName& TaskInstanceName);
	static class UGameplayTask_ClaimResource* ClaimResource(TScriptInterface<class IGameplayTaskOwnerInterface> InTaskOwner, class UClass* ResourceClass, uint8 Priority, const class FName& TaskInstanceName);
};

class UGameplayTask_SpawnActor : public UGameplayTask
{
public:
	struct FMulticastInlineDelegateProperty_          Success;
	struct FMulticastInlineDelegateProperty_          DidNotSpawn;
	uint8                                             Pad_0[0x0030];
	class UClass*                                     ClassToSpawn;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GameplayTask_SpawnActor");
		return Clss;
	}

	static class UGameplayTask_SpawnActor* SpawnActor(TScriptInterface<class IGameplayTaskOwnerInterface> TaskOwner, const struct FVector& SpawnLocation, const struct FRotator& SpawnRotation, class UClass* Class, bool bSpawnOnlyOnAuthority);
	void FinishSpawningActor(class UObject* WorldContextObject, class AActor* SpawnedActor);
	bool BeginSpawningActor(class UObject* WorldContextObject, class AActor** SpawnedActor);
};

class UGameplayTask_TimeLimitedExecution : public UGameplayTask
{
public:
	struct FMulticastInlineDelegateProperty_          OnFinished;
	struct FMulticastInlineDelegateProperty_          OnTimeExpired;
	uint8                                             Pad_0[0x0018];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GameplayTask_TimeLimitedExecution");
		return Clss;
	}
};

class UGameplayTask_WaitDelay : public UGameplayTask
{
public:
	struct FMulticastInlineDelegateProperty_          OnFinish;
	uint8                                             Pad_0[0x0010];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GameplayTask_WaitDelay");
		return Clss;
	}

	static class UGameplayTask_WaitDelay* TaskWaitDelay(TScriptInterface<class IGameplayTaskOwnerInterface> TaskOwner, float Time, uint8 Priority);
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
