#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class UGLTFExportOptions : public UObject
{
public:
	float                                             ExportUniformScale;
	bool                                              bExportPreviewMesh;
	bool                                              bSkipNearDefaultValues;
	bool                                              bIncludeCopyrightNotice;
	bool                                              bExportProxyMaterials;
	bool                                              bExportUnlitMaterials;
	bool                                              bExportClearCoatMaterials;
	bool                                              bExportEmissiveStrength;
	enum class EEGLTFMaterialBakeMode                 BakeMaterialInputs;
	enum class EEGLTFMaterialBakeSizePOT              DefaultMaterialBakeSize;
	enum class ETextureFilter                         DefaultMaterialBakeFilter;
	enum class ETextureAddress                        DefaultMaterialBakeTiling;
	uint8                                             Pad_0[0x0001];
	TMap<enum class EEGLTFMaterialPropertyGroup, struct FGLTFOverrideMaterialBakeSettings> DefaultInputBakeSettings;
	int32                                             DefaultLevelOfDetail;
	bool                                              bExportVertexColors;
	bool                                              bExportVertexSkinWeights;
	bool                                              bUseMeshQuantization;
	bool                                              bExportLevelSequences;
	bool                                              bExportAnimationSequences;
	enum class EEGLTFTextureImageFormat               TextureImageFormat;
	uint8                                             Pad_1[0x0002];
	int32                                             TextureImageQuality;
	bool                                              bExportTextureTransforms;
	bool                                              bAdjustNormalmaps;
	bool                                              bExportHiddenInGame;
	bool                                              bExportLights;
	bool                                              bExportCameras;
	enum class EEGLTFMaterialVariantMode              ExportMaterialVariants;
	uint8                                             Pad_2[0x0002];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GLTFExportOptions");
		return Clss;
	}

	void ResetToDefault();
};

class UGLTFExporter : public UExporter
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GLTFExporter");
		return Clss;
	}

	static bool ExportToGLTF(class UObject* Object, const class FString& FilePath, class UGLTFExportOptions* Options, TSet<uint8[0x0] /**/>* SelectedActors, struct FGLTFExportMessages* OutMessages);
};

class UGLTFAnimSequenceExporter : public UGLTFExporter
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GLTFAnimSequenceExporter");
		return Clss;
	}
};

class UGLTFLevelExporter : public UGLTFExporter
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GLTFLevelExporter");
		return Clss;
	}
};

class UGLTFLevelSequenceExporter : public UGLTFExporter
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GLTFLevelSequenceExporter");
		return Clss;
	}
};

class UGLTFLevelVariantSetsExporter : public UGLTFExporter
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GLTFLevelVariantSetsExporter");
		return Clss;
	}
};

class UGLTFMaterialExporter : public UGLTFExporter
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GLTFMaterialExporter");
		return Clss;
	}
};

class UGLTFSkeletalMeshExporter : public UGLTFExporter
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GLTFSkeletalMeshExporter");
		return Clss;
	}
};

class UGLTFStaticMeshExporter : public UGLTFExporter
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GLTFStaticMeshExporter");
		return Clss;
	}
};

class UGLTFProxyOptions : public UObject
{
public:
	bool                                              bBakeMaterialInputs;
	enum class EEGLTFMaterialBakeSizePOT              DefaultMaterialBakeSize;
	enum class ETextureFilter                         DefaultMaterialBakeFilter;
	enum class ETextureAddress                        DefaultMaterialBakeTiling;
	uint8                                             Pad_0[0x0004];
	TMap<enum class EEGLTFMaterialPropertyGroup, struct FGLTFOverrideMaterialBakeSettings> DefaultInputBakeSettings;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GLTFProxyOptions");
		return Clss;
	}

	void ResetToDefault();
};

class UGLTFMaterialExportOptions : public UAssetUserData
{
public:
	class UMaterialInterface*                         Proxy;
	struct FGLTFOverrideMaterialBakeSettings          Default;
	uint8                                             Pad_0[0x0002];
	TMap<enum class EEGLTFMaterialPropertyGroup, struct FGLTFOverrideMaterialBakeSettings> Inputs;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("GLTFMaterialExportOptions");
		return Clss;
	}
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
