// generated by beardumper

#include "../SDK.hpp"

namespace SDK
{

void UHoudiniAssetBlueprintComponent::SetToggleValueAt(const class FString& Name, bool Value, int32 Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniAssetBlueprintComponent", "SetToggleValueAt");

	Params::UHoudiniAssetBlueprintComponent_SetToggleValueAt Parms{};
	Parms.Name = Name;
	Parms.Value = Value;
	Parms.Index = Index;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void UHoudiniAssetBlueprintComponent::SetFloatParameter(const class FString& Name, float Value, int32 Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniAssetBlueprintComponent", "SetFloatParameter");

	Params::UHoudiniAssetBlueprintComponent_SetFloatParameter Parms{};
	Parms.Name = Name;
	Parms.Value = Value;
	Parms.Index = Index;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

bool UHoudiniAssetBlueprintComponent::HasParameter(const class FString& Name)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniAssetBlueprintComponent", "HasParameter");

	Params::UHoudiniAssetBlueprintComponent_HasParameter Parms{};
	Parms.Name = Name;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

void UHoudiniStaticMesh::SetVertexPosition(uint32 InVertexIndex, struct FVector3f* InPosition)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "SetVertexPosition");

	Params::UHoudiniStaticMesh_SetVertexPosition Parms{};
	Parms.InVertexIndex = InVertexIndex;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (InPosition != nullptr)
		*InPosition = Parms.InPosition;
}

void UHoudiniStaticMesh::SetTriangleVertexVTangent(uint32 InTriangleIndex, uint8 InTriangleVertexIndex, struct FVector3f* InVTangent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "SetTriangleVertexVTangent");

	Params::UHoudiniStaticMesh_SetTriangleVertexVTangent Parms{};
	Parms.InTriangleIndex = InTriangleIndex;
	Parms.InTriangleVertexIndex = InTriangleVertexIndex;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (InVTangent != nullptr)
		*InVTangent = Parms.InVTangent;
}

void UHoudiniStaticMesh::SetTriangleVertexUV(uint32 InTriangleIndex, uint8 InTriangleVertexIndex, uint8 InUVLayer, struct FVector2f* InUV)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "SetTriangleVertexUV");

	Params::UHoudiniStaticMesh_SetTriangleVertexUV Parms{};
	Parms.InTriangleIndex = InTriangleIndex;
	Parms.InTriangleVertexIndex = InTriangleVertexIndex;
	Parms.InUVLayer = InUVLayer;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (InUV != nullptr)
		*InUV = Parms.InUV;
}

void UHoudiniStaticMesh::SetTriangleVertexUTangent(uint32 InTriangleIndex, uint8 InTriangleVertexIndex, struct FVector3f* InUTangent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "SetTriangleVertexUTangent");

	Params::UHoudiniStaticMesh_SetTriangleVertexUTangent Parms{};
	Parms.InTriangleIndex = InTriangleIndex;
	Parms.InTriangleVertexIndex = InTriangleVertexIndex;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (InUTangent != nullptr)
		*InUTangent = Parms.InUTangent;
}

void UHoudiniStaticMesh::SetTriangleVertexNormal(uint32 InTriangleIndex, uint8 InTriangleVertexIndex, struct FVector3f* InNormal)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "SetTriangleVertexNormal");

	Params::UHoudiniStaticMesh_SetTriangleVertexNormal Parms{};
	Parms.InTriangleIndex = InTriangleIndex;
	Parms.InTriangleVertexIndex = InTriangleVertexIndex;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (InNormal != nullptr)
		*InNormal = Parms.InNormal;
}

void UHoudiniStaticMesh::SetTriangleVertexIndices(uint32 InTriangleIndex, struct FIntVector* InTriangleVertexIndices)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "SetTriangleVertexIndices");

	Params::UHoudiniStaticMesh_SetTriangleVertexIndices Parms{};
	Parms.InTriangleIndex = InTriangleIndex;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (InTriangleVertexIndices != nullptr)
		*InTriangleVertexIndices = Parms.InTriangleVertexIndices;
}

void UHoudiniStaticMesh::SetTriangleVertexColor(uint32 InTriangleIndex, uint8 InTriangleVertexIndex, struct FColor* InColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "SetTriangleVertexColor");

	Params::UHoudiniStaticMesh_SetTriangleVertexColor Parms{};
	Parms.InTriangleIndex = InTriangleIndex;
	Parms.InTriangleVertexIndex = InTriangleVertexIndex;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (InColor != nullptr)
		*InColor = Parms.InColor;
}

void UHoudiniStaticMesh::SetTriangleMaterialID(uint32 InTriangleIndex, int32 InMaterialID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "SetTriangleMaterialID");

	Params::UHoudiniStaticMesh_SetTriangleMaterialID Parms{};
	Parms.InTriangleIndex = InTriangleIndex;
	Parms.InMaterialID = InMaterialID;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void UHoudiniStaticMesh::SetStaticMaterial(uint32 InMaterialIndex, struct FStaticMaterial* InStaticMaterial)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "SetStaticMaterial");

	Params::UHoudiniStaticMesh_SetStaticMaterial Parms{};
	Parms.InMaterialIndex = InMaterialIndex;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (InStaticMaterial != nullptr)
		*InStaticMaterial = Parms.InStaticMaterial;
}

void UHoudiniStaticMesh::SetNumUVLayers(uint32 InNumUVLayers)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "SetNumUVLayers");

	Params::UHoudiniStaticMesh_SetNumUVLayers Parms{};
	Parms.InNumUVLayers = InNumUVLayers;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void UHoudiniStaticMesh::SetNumStaticMaterials(uint32 InNumStaticMaterials)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "SetNumStaticMaterials");

	Params::UHoudiniStaticMesh_SetNumStaticMaterials Parms{};
	Parms.InNumStaticMaterials = InNumStaticMaterials;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void UHoudiniStaticMesh::SetHasTangents(bool bInHasTangents)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "SetHasTangents");

	Params::UHoudiniStaticMesh_SetHasTangents Parms{};
	Parms.bInHasTangents = bInHasTangents;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void UHoudiniStaticMesh::SetHasPerFaceMaterials(bool bInHasPerFaceMaterials)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "SetHasPerFaceMaterials");

	Params::UHoudiniStaticMesh_SetHasPerFaceMaterials Parms{};
	Parms.bInHasPerFaceMaterials = bInHasPerFaceMaterials;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void UHoudiniStaticMesh::SetHasNormals(bool bInHasNormals)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "SetHasNormals");

	Params::UHoudiniStaticMesh_SetHasNormals Parms{};
	Parms.bInHasNormals = bInHasNormals;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void UHoudiniStaticMesh::SetHasColors(bool bInHasColors)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "SetHasColors");

	Params::UHoudiniStaticMesh_SetHasColors Parms{};
	Parms.bInHasColors = bInHasColors;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void UHoudiniStaticMesh::Optimize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "Optimize");

	SDK::Rt::ProcessEvent(this, Func, nullptr);
}

bool UHoudiniStaticMesh::IsValid(bool bInSkipVertexIndicesCheck)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "IsValid");

	Params::UHoudiniStaticMesh_IsValid Parms{};
	Parms.bInSkipVertexIndicesCheck = bInSkipVertexIndicesCheck;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

void UHoudiniStaticMesh::Initialize(uint32 InNumVertices, uint32 InNumTriangles, uint32 InNumUVLayers, uint32 InInitialNumStaticMaterials, bool bInHasNormals, bool bInHasTangents, bool bInHasColors, bool bInHasPerFaceMaterials)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "Initialize");

	Params::UHoudiniStaticMesh_Initialize Parms{};
	Parms.InNumVertices = InNumVertices;
	Parms.InNumTriangles = InNumTriangles;
	Parms.InNumUVLayers = InNumUVLayers;
	Parms.InInitialNumStaticMaterials = InInitialNumStaticMaterials;
	Parms.bInHasNormals = bInHasNormals;
	Parms.bInHasTangents = bInHasTangents;
	Parms.bInHasColors = bInHasColors;
	Parms.bInHasPerFaceMaterials = bInHasPerFaceMaterials;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

bool UHoudiniStaticMesh::HasTangents()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "HasTangents");

	Params::UHoudiniStaticMesh_HasTangents Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

bool UHoudiniStaticMesh::HasPerFaceMaterials()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "HasPerFaceMaterials");

	Params::UHoudiniStaticMesh_HasPerFaceMaterials Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

bool UHoudiniStaticMesh::HasNormals()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "HasNormals");

	Params::UHoudiniStaticMesh_HasNormals Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

bool UHoudiniStaticMesh::HasColors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "HasColors");

	Params::UHoudiniStaticMesh_HasColors Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

TArray<struct FVector3f> UHoudiniStaticMesh::GetVertexPositions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "GetVertexPositions");

	Params::UHoudiniStaticMesh_GetVertexPositions Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

TArray<struct FVector3f> UHoudiniStaticMesh::GetVertexInstanceVTangents()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "GetVertexInstanceVTangents");

	Params::UHoudiniStaticMesh_GetVertexInstanceVTangents Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

TArray<struct FVector2f> UHoudiniStaticMesh::GetVertexInstanceUVs()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "GetVertexInstanceUVs");

	Params::UHoudiniStaticMesh_GetVertexInstanceUVs Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

TArray<struct FVector3f> UHoudiniStaticMesh::GetVertexInstanceUTangents()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "GetVertexInstanceUTangents");

	Params::UHoudiniStaticMesh_GetVertexInstanceUTangents Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

TArray<struct FVector3f> UHoudiniStaticMesh::GetVertexInstanceNormals()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "GetVertexInstanceNormals");

	Params::UHoudiniStaticMesh_GetVertexInstanceNormals Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

TArray<struct FColor> UHoudiniStaticMesh::GetVertexInstanceColors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "GetVertexInstanceColors");

	Params::UHoudiniStaticMesh_GetVertexInstanceColors Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

TArray<struct FIntVector> UHoudiniStaticMesh::GetTriangleIndices()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "GetTriangleIndices");

	Params::UHoudiniStaticMesh_GetTriangleIndices Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

TArray<struct FStaticMaterial> UHoudiniStaticMesh::GetStaticMaterials()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "GetStaticMaterials");

	Params::UHoudiniStaticMesh_GetStaticMaterials Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

uint32 UHoudiniStaticMesh::GetNumVertices()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "GetNumVertices");

	Params::UHoudiniStaticMesh_GetNumVertices Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

uint32 UHoudiniStaticMesh::GetNumVertexInstances()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "GetNumVertexInstances");

	Params::UHoudiniStaticMesh_GetNumVertexInstances Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

uint32 UHoudiniStaticMesh::GetNumUVLayers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "GetNumUVLayers");

	Params::UHoudiniStaticMesh_GetNumUVLayers Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

uint32 UHoudiniStaticMesh::GetNumTriangles()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "GetNumTriangles");

	Params::UHoudiniStaticMesh_GetNumTriangles Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

uint32 UHoudiniStaticMesh::GetNumStaticMaterials()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "GetNumStaticMaterials");

	Params::UHoudiniStaticMesh_GetNumStaticMaterials Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

int32 UHoudiniStaticMesh::GetMaterialIndex(const class FName& InMaterialSlotName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "GetMaterialIndex");

	Params::UHoudiniStaticMesh_GetMaterialIndex Parms{};
	Parms.InMaterialSlotName = InMaterialSlotName;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

TArray<int32> UHoudiniStaticMesh::GetMaterialIDsPerTriangle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "GetMaterialIDsPerTriangle");

	Params::UHoudiniStaticMesh_GetMaterialIDsPerTriangle Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

class UMaterialInterface* UHoudiniStaticMesh::GetMaterial(int32 InMaterialIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "GetMaterial");

	Params::UHoudiniStaticMesh_GetMaterial Parms{};
	Parms.InMaterialIndex = InMaterialIndex;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

void UHoudiniStaticMesh::CalculateTangents(bool bInComputeWeightedNormals)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "CalculateTangents");

	Params::UHoudiniStaticMesh_CalculateTangents Parms{};
	Parms.bInComputeWeightedNormals = bInComputeWeightedNormals;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void UHoudiniStaticMesh::CalculateNormals(bool bInComputeWeightedNormals)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "CalculateNormals");

	Params::UHoudiniStaticMesh_CalculateNormals Parms{};
	Parms.bInComputeWeightedNormals = bInComputeWeightedNormals;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

struct FBox UHoudiniStaticMesh::CalcBounds()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "CalcBounds");

	Params::UHoudiniStaticMesh_CalcBounds Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

uint32 UHoudiniStaticMesh::AddStaticMaterial(struct FStaticMaterial* InStaticMaterial)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMesh", "AddStaticMaterial");

	Params::UHoudiniStaticMesh_AddStaticMaterial Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (InStaticMaterial != nullptr)
		*InStaticMaterial = Parms.InStaticMaterial;

	return Parms.ReturnValue;
}

void UHoudiniStaticMeshComponent::SetMesh(class UHoudiniStaticMesh* InMesh)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMeshComponent", "SetMesh");

	Params::UHoudiniStaticMeshComponent_SetMesh Parms{};
	Parms.InMesh = InMesh;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void UHoudiniStaticMeshComponent::SetHoudiniIconVisible(bool bInHoudiniIconVisible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMeshComponent", "SetHoudiniIconVisible");

	Params::UHoudiniStaticMeshComponent_SetHoudiniIconVisible Parms{};
	Parms.bInHoudiniIconVisible = bInHoudiniIconVisible;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void UHoudiniStaticMeshComponent::NotifyMeshUpdated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMeshComponent", "NotifyMeshUpdated");

	SDK::Rt::ProcessEvent(this, Func, nullptr);
}

bool UHoudiniStaticMeshComponent::IsHoudiniIconVisible()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMeshComponent", "IsHoudiniIconVisible");

	Params::UHoudiniStaticMeshComponent_IsHoudiniIconVisible Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

class UHoudiniStaticMesh* UHoudiniStaticMeshComponent::GetMesh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("HoudiniStaticMeshComponent", "GetMesh");

	Params::UHoudiniStaticMeshComponent_GetMesh Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

}
