#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class UIKGoalCreatorInterface : public UInterface
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKGoalCreatorInterface");
		return Clss;
	}

	void AddIKGoals(TMap<class FName, struct FIKRigGoal>* OutGoals);
};

class UIKRigComponent : public UActorComponent
{
public:
	uint8                                             Pad_0[0x0018];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRigComponent");
		return Clss;
	}

	void SetIKRigGoalTransform(const class FName& GoalName, const struct FTransform& Transform, float PositionAlpha, float RotationAlpha);
	void SetIKRigGoalPositionAndRotation(const class FName& GoalName, const struct FVector& Position, const struct FQuat& Rotation, float PositionAlpha, float RotationAlpha);
	void SetIKRigGoal(struct FIKRigGoal* Goal);
	void ClearAllGoals();
};

class URetargetChainSettings : public UObject
{
public:
	class FName                                       SourceChain;
	class FName                                       TargetChain;
	struct FTargetChainSettings                       Settings;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RetargetChainSettings");
		return Clss;
	}
};

class URetargetRootSettings : public UObject
{
public:
	struct FTargetRootSettings                        Settings;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RetargetRootSettings");
		return Clss;
	}
};

class UIKRetargetGlobalSettings : public UObject
{
public:
	struct FRetargetGlobalSettings                    Settings;
	uint8                                             Pad_0[0x0004];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRetargetGlobalSettings");
		return Clss;
	}
};

class UIKRetargeter : public UObject
{
public:
	TSoftObjectPtr<class UIKRigDefinition>            SourceIKRigAsset;
	TSoftObjectPtr<class UIKRigDefinition>            TargetIKRigAsset;
	TArray<struct FRetargetChainMap>                  ChainMapping;
	TArray<class URetargetChainSettings*>             ChainSettings;
	class URetargetRootSettings*                      RootSettings;
	class UIKRetargetGlobalSettings*                  GlobalSettings;
	TMap<class FName, struct FRetargetProfile>        Profiles;
	class FName                                       CurrentProfile;
	uint8                                             Pad_0[0x0004];
	TMap<class FName, struct FIKRetargetPose>         SourceRetargetPoses;
	TMap<class FName, struct FIKRetargetPose>         TargetRetargetPoses;
	class FName                                       CurrentSourceRetargetPose;
	class FName                                       CurrentTargetRetargetPose;
	TMap<class FName, struct FIKRetargetPose>         RetargetPoses;
	class FName                                       CurrentRetargetPose;
	uint8                                             Pad_1[0x0004];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRetargeter");
		return Clss;
	}

	static void SetRootSettingsInRetargetProfile(struct FRetargetProfile* RetargetProfile, struct FTargetRootSettings* RootSettings);
	static void SetGlobalSettingsInRetargetProfile(struct FRetargetProfile* RetargetProfile, struct FRetargetGlobalSettings* GlobalSettings);
	static void SetChainSpeedPlantSettingsInRetargetProfile(struct FRetargetProfile* RetargetProfile, struct FTargetChainSpeedPlantSettings* SpeedPlantSettings, const class FName& TargetChainName);
	static void SetChainSettingsInRetargetProfile(struct FRetargetProfile* RetargetProfile, struct FTargetChainSettings* ChainSettings, const class FName& TargetChainName);
	static void SetChainIKSettingsInRetargetProfile(struct FRetargetProfile* RetargetProfile, struct FTargetChainIKSettings* IKSettings, const class FName& TargetChainName);
	static void SetChainFKSettingsInRetargetProfile(struct FRetargetProfile* RetargetProfile, struct FTargetChainFKSettings* FKSettings, const class FName& TargetChainName);
	static struct FTargetRootSettings GetRootSettingsFromRetargetProfile(struct FRetargetProfile* RetargetProfile);
	static void GetRootSettingsFromRetargetAsset(class UIKRetargeter* RetargetAsset, const class FName& OptionalProfileName, struct FTargetRootSettings* OutSettings);
	static struct FRetargetGlobalSettings GetGlobalSettingsFromRetargetProfile(struct FRetargetProfile* RetargetProfile);
	static void GetGlobalSettingsFromRetargetAsset(class UIKRetargeter* RetargetAsset, const class FName& OptionalProfileName, struct FRetargetGlobalSettings* OutSettings);
	static struct FTargetChainSettings GetChainUsingGoalFromRetargetAsset(class UIKRetargeter* RetargetAsset, const class FName& IKGoalName);
	static struct FTargetChainSettings GetChainSettingsFromRetargetProfile(struct FRetargetProfile* RetargetProfile, const class FName& TargetChainName);
	static struct FTargetChainSettings GetChainSettingsFromRetargetAsset(class UIKRetargeter* RetargetAsset, const class FName& TargetChainName, const class FName& OptionalProfileName);
};

class UIKRetargetProcessor : public UObject
{
public:
	uint8                                             Pad_0[0x0160];
	class UIKRigProcessor*                            IKRigProcessor;
	uint8                                             Pad_1[0x0208];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRetargetProcessor");
		return Clss;
	}
};

class UIKRigEffectorGoal : public UObject
{
public:
	class FName                                       GoalName;
	class FName                                       BoneName;
	float                                             PositionAlpha;
	float                                             RotationAlpha;
	struct FTransform                                 CurrentTransform;
	struct FTransform                                 InitialTransform;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRigEffectorGoal");
		return Clss;
	}
};

class UIKRigDefinition : public UObject
{
public:
	uint8                                             Pad_0[0x0008];
	TSoftObjectPtr<class USkeletalMesh>               PreviewSkeletalMesh;
	struct FIKRigSkeleton                             Skeleton;
	TArray<class UIKRigEffectorGoal*>                 Goals;
	TArray<class UIKRigSolver*>                       Solvers;
	struct FRetargetDefinition                        RetargetDefinition;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRigDefinition");
		return Clss;
	}
};

class UIKRigProcessor : public UObject
{
public:
	uint8                                             Pad_0[0x0040];
	TArray<class UIKRigSolver*>                       Solvers;
	uint8                                             Pad_1[0x00D8];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRigProcessor");
		return Clss;
	}
};

class UIKRigSolver : public UObject
{
public:
	bool                                              bIsEnabled;
	uint8                                             Pad_0[0x0007];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRigSolver");
		return Clss;
	}
};

class UIKRig_BodyMoverEffector : public UObject
{
public:
	class FName                                       GoalName;
	class FName                                       BoneName;
	float                                             InfluenceMultiplier;
	uint8                                             Pad_0[0x0004];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRig_BodyMoverEffector");
		return Clss;
	}
};

class UIKRig_BodyMover : public UIKRigSolver
{
public:
	class FName                                       RootBone;
	float                                             PositionAlpha;
	float                                             PositionPositiveX;
	float                                             PositionNegativeX;
	float                                             PositionPositiveY;
	float                                             PositionNegativeY;
	float                                             PositionPositiveZ;
	float                                             PositionNegativeZ;
	float                                             RotationAlpha;
	float                                             RotateXAlpha;
	float                                             RotateYAlpha;
	float                                             RotateZAlpha;
	TArray<class UIKRig_BodyMoverEffector*>           Effectors;
	uint8                                             Pad_0[0x0008];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRig_BodyMover");
		return Clss;
	}
};

class UIKRig_LimbEffector : public UObject
{
public:
	class FName                                       GoalName;
	class FName                                       BoneName;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRig_LimbEffector");
		return Clss;
	}
};

class UIKRig_LimbSolver : public UIKRigSolver
{
public:
	class FName                                       RootName;
	float                                             ReachPrecision;
	enum class EEAxis                                 HingeRotationAxis;
	uint8                                             Pad_0[0x0003];
	int32                                             MaxIterations;
	bool                                              bEnableLimit;
	uint8                                             Pad_1[0x0003];
	float                                             MinRotationAngle;
	bool                                              bAveragePull;
	uint8                                             Pad_2[0x0003];
	float                                             PullDistribution;
	float                                             ReachStepAlpha;
	bool                                              bEnableTwistCorrection;
	enum class EEAxis                                 EndBoneForwardAxis;
	uint8                                             Pad_3[0x0002];
	class UIKRig_LimbEffector*                        Effector;
	uint8                                             Pad_4[0x0028];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRig_LimbSolver");
		return Clss;
	}
};

class UIKRig_FBIKEffector : public UObject
{
public:
	class FName                                       GoalName;
	class FName                                       BoneName;
	float                                             StrengthAlpha;
	float                                             PullChainAlpha;
	float                                             PinRotation;
	int32                                             IndexInSolver;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRig_FBIKEffector");
		return Clss;
	}
};

class UIKRig_FBIKBoneSettings : public UObject
{
public:
	class FName                                       Bone;
	float                                             RotationStiffness;
	float                                             PositionStiffness;
	enum class EEPBIKLimitType                        X;
	uint8                                             Pad_0[0x0003];
	float                                             MinX;
	float                                             MaxX;
	enum class EEPBIKLimitType                        Y;
	uint8                                             Pad_1[0x0003];
	float                                             MinY;
	float                                             MaxY;
	enum class EEPBIKLimitType                        Z;
	uint8                                             Pad_2[0x0003];
	float                                             MinZ;
	float                                             MaxZ;
	bool                                              bUsePreferredAngles;
	uint8                                             Pad_3[0x0007];
	struct FVector                                    PreferredAngles;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRig_FBIKBoneSettings");
		return Clss;
	}
};

class UIKRigFBIKSolver : public UIKRigSolver
{
public:
	class FName                                       RootBone;
	int32                                             Iterations;
	float                                             MassMultiplier;
	bool                                              bAllowStretch;
	enum class EEPBIKRootBehavior                     RootBehavior;
	uint8                                             Pad_0[0x0002];
	struct FRootPrePullSettings                       PrePullRootSettings;
	float                                             PullChainAlpha;
	float                                             MaxAngle;
	float                                             OverRelaxation;
	bool                                              bStartSolveFromInputPose;
	uint8                                             Pad_1[0x0003];
	TArray<class UIKRig_FBIKEffector*>                Effectors;
	TArray<class UIKRig_FBIKBoneSettings*>            BoneSettings;
	uint8                                             Pad_2[0x0068];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRigFBIKSolver");
		return Clss;
	}
};

class UIKRig_PoleSolverEffector : public UObject
{
public:
	class FName                                       GoalName;
	class FName                                       BoneName;
	float                                             Alpha;
	uint8                                             Pad_0[0x0004];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRig_PoleSolverEffector");
		return Clss;
	}
};

class UIKRig_PoleSolver : public UIKRigSolver
{
public:
	class FName                                       RootName;
	class FName                                       EndName;
	class UIKRig_PoleSolverEffector*                  Effector;
	uint8                                             Pad_0[0x0020];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRig_PoleSolver");
		return Clss;
	}
};

class UIKRig_SetTransformEffector : public UObject
{
public:
	bool                                              bEnablePosition;
	bool                                              bEnableRotation;
	uint8                                             Pad_0[0x0002];
	float                                             Alpha;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRig_SetTransformEffector");
		return Clss;
	}
};

class UIKRig_SetTransform : public UIKRigSolver
{
public:
	class FName                                       Goal;
	class FName                                       RootBone;
	class UIKRig_SetTransformEffector*                Effector;
	uint8                                             Pad_0[0x0008];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("IKRig_SetTransform");
		return Clss;
	}
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
