#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class UImgMediaSettings : public UObject
{
public:
	struct FFrameRate                                 DefaultFrameRate;
	bool                                              BandwidthThrottlingEnabled;
	uint8                                             Pad_0[0x0003];
	float                                             CacheBehindPercentage;
	float                                             CacheSizeGB;
	int32                                             CacheThreads;
	int32                                             CacheThreadStackSizeKB;
	float                                             GlobalCacheSizeGB;
	bool                                              UseGlobalCache;
	uint8                                             Pad_1[0x0003];
	uint32                                            ExrDecoderThreads;
	class FString                                     DefaultProxy;
	bool                                              UseDefaultProxy;
	uint8                                             Pad_2[0x0007];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ImgMediaSettings");
		return Clss;
	}
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
