#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

enum class EGizmoElementState : uint8
{
	None                                      = 0,
	Visible                                   = 2,
	Hittable                                  = 4,
	VisibleAndHittable                        = 6,
	EGizmoElementState_MAX                    = 7,
};

enum class EGizmoElementInteractionState : uint8
{
	None                                      = 0,
	Hovering                                  = 1,
	Interacting                               = 2,
	EGizmoElementInteractionState_MAX         = 3,
};

enum class EGizmoElementViewDependentType : uint8
{
	None                                      = 0,
	Axis                                      = 1,
	Plane                                     = 2,
	EGizmoElementViewDependentType_MAX        = 3,
};

enum class EGizmoElementViewAlignType : uint8
{
	None                                      = 0,
	PointOnly                                 = 1,
	PointEye                                  = 2,
	PointScreen                               = 3,
	Axial                                     = 4,
	EGizmoElementViewAlignType_MAX            = 5,
};

enum class EGizmoElementPartialType : uint8
{
	None                                      = 0,
	Partial                                   = 1,
	PartialViewDependent                      = 2,
	EGizmoElementPartialType_MAX              = 3,
};

enum class EStandardToolContextMaterials : uint8
{
	VertexColorMaterial                       = 1,
	EStandardToolContextMaterials_MAX         = 2,
};

enum class EToolContextCoordinateSystem : uint8
{
	World                                     = 0,
	Local                                     = 1,
	EToolContextCoordinateSystem_MAX          = 2,
};

enum class EToolContextTransformGizmoMode : uint8
{
	NoGizmo                                   = 0,
	Translation                               = 1,
	Rotation                                  = 2,
	Scale                                     = 3,
	Combined                                  = 8,
	EToolContextTransformGizmoMode_MAX        = 9,
};

enum class EToolMessageLevel : uint8
{
	Internal                                  = 0,
	UserMessage                               = 1,
	UserNotification                          = 2,
	UserWarning                               = 3,
	UserError                                 = 4,
	EToolMessageLevel_MAX                     = 5,
};

enum class ESelectedObjectsModificationType : uint8
{
	Replace                                   = 0,
	Add                                       = 1,
	Remove                                    = 2,
	Clear                                     = 3,
	ESelectedObjectsModificationType_MAX      = 4,
};

enum class EViewInteractionState : uint8
{
	None                                      = 0,
	Hovered                                   = 1,
	Focused                                   = 2,
	EViewInteractionState_MAX                 = 3,
};

enum class EGizmoElementArrowHeadType : uint8
{
	Cone                                      = 0,
	Cube                                      = 1,
	EGizmoElementArrowHeadType_MAX            = 2,
};

enum class EInputCaptureSide : uint8
{
	None                                      = 0,
	Left                                      = 1,
	Right                                     = 2,
	Both                                      = 3,
	Any                                       = 99,
	EInputCaptureSide_MAX                     = 100,
};

enum class EInputCaptureRequestType : uint8
{
	Begin                                     = 1,
	Ignore                                    = 2,
	EInputCaptureRequestType_MAX              = 3,
};

enum class EInputCaptureState : uint8
{
	Begin                                     = 1,
	Continue                                  = 2,
	End                                       = 3,
	Ignore                                    = 4,
	EInputCaptureState_MAX                    = 5,
};

enum class EInputDevices : uint16
{
	None                                      = 0,
	Keyboard                                  = 1,
	Mouse                                     = 2,
	Gamepad                                   = 4,
	OculusTouch                               = 8,
	HTCViveWands                              = 16,
	AnySpatialDevice                          = 24,
	TabletFingers                             = 1024,
	EInputDevices_MAX                         = 1025,
};

enum class ETransformGizmoSubElements : uint32
{
	None                                      = 0,
	TranslateAxisX                            = 2,
	TranslateAxisY                            = 4,
	TranslateAxisZ                            = 8,
	TranslateAllAxes                          = 14,
	TranslatePlaneXY                          = 16,
	TranslatePlaneXZ                          = 32,
	TranslatePlaneYZ                          = 64,
	TranslateAllPlanes                        = 112,
	RotateAxisX                               = 128,
	RotateAxisY                               = 256,
	RotateAxisZ                               = 512,
	RotateAllAxes                             = 896,
	ScaleAxisX                                = 1024,
	ScaleAxisY                                = 2048,
	ScaleAxisZ                                = 4096,
	ScaleAllAxes                              = 7168,
	ScalePlaneYZ                              = 8192,
	ScalePlaneXZ                              = 16384,
	ScalePlaneXY                              = 32768,
	ScaleAllPlanes                            = 57344,
	ScaleUniform                              = 65536,
	StandardTranslateRotate                   = 1022,
	TranslateRotateUniformScale               = 66558,
	FullTranslateRotateScale                  = 131070,
	ETransformGizmoSubElements_MAX            = 131071,
};

enum class EToolShutdownType : uint8
{
	Completed                                 = 0,
	Accept                                    = 1,
	Cancel                                    = 2,
	EToolShutdownType_MAX                     = 3,
};

enum class EToolSide : uint8
{
	Left                                      = 1,
	Mouse                                     = 1,
	Right                                     = 2,
	EToolSide_MAX                             = 3,
};

enum class EToolChangeTrackingMode : uint8
{
	NoChangeTracking                          = 1,
	UndoToExit                                = 2,
	FullUndoRedo                              = 3,
	EToolChangeTrackingMode_MAX               = 4,
};

enum class ESceneSnapQueryType : uint8
{
	Position                                  = 1,
	Rotation                                  = 2,
	ESceneSnapQueryType_MAX                   = 3,
};

enum class ESceneSnapQueryTargetType : uint8
{
	None                                      = 0,
	MeshVertex                                = 1,
	MeshEdge                                  = 2,
	Grid                                      = 4,
	All                                       = 7,
	ESceneSnapQueryTargetType_MAX             = 8,
};

struct FGizmoVec2ParameterChange
{
public:
	struct FVector2D                                  InitialValue;
	struct FVector2D                                  CurrentValue;
};

struct FGizmoElementColorAttribute
{
public:
	struct FLinearColor                               Value;
	bool                                              bHasValue;
	bool                                              bOverridesChildState;
	uint8                                             Pad_0[0x0002];
};

struct FGizmoElementMaterialAttribute
{
public:
	TWeakObjectPtr<class UMaterialInterface>          Value;
	bool                                              bOverridesChildState;
	uint8                                             Pad_0[0x0003];
};

struct FGizmoElementMeshRenderStateAttributes
{
public:
	struct FGizmoElementMaterialAttribute             Material;
	struct FGizmoElementMaterialAttribute             HoverMaterial;
	struct FGizmoElementMaterialAttribute             InteractMaterial;
	struct FGizmoElementColorAttribute                VertexColor;
	struct FGizmoElementColorAttribute                HoverVertexColor;
	struct FGizmoElementColorAttribute                InteractVertexColor;
};

struct FGizmoElementLineRenderStateAttributes
{
public:
	struct FGizmoElementColorAttribute                LineColor;
	struct FGizmoElementColorAttribute                HoverLineColor;
	struct FGizmoElementColorAttribute                InteractLineColor;
};

struct FGizmoFloatParameterChange
{
public:
	float                                             InitialValue;
	float                                             CurrentValue;
};

struct FBrushStampData
{
public:
	uint8                                             Pad_0[0x0130];
};

struct FBehaviorInfo
{
public:
	class UInputBehavior*                             Behavior;
	uint8                                             Pad_0[0x0018];
};

struct FInputRayHit
{
public:
	bool                                              bHit;
	uint8                                             Pad_0[0x0007];
	double                                            HitDepth;
	struct FVector                                    HitNormal;
	bool                                              bHasHitNormal;
	uint8                                             Pad_1[0x0003];
	int32                                             HitIdentifier;
	uint8                                             Pad_2[0x0008];
	TWeakObjectPtr<class UObject>                     HitObject;
};

struct FInputDeviceRay
{
public:
	struct FRay                                       WorldRay;
	bool                                              bHas2D;
	uint8                                             Pad_0[0x0007];
	struct FVector2D                                  ScreenPosition;
};

struct FActiveGizmo
{
public:
	class UInteractiveGizmo*                          Gizmo;
	uint8                                             Pad_0[0x0028];
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
