#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class UInterchangeAnimationTrackSetFactoryNode : public UInterchangeFactoryBaseNode
{
public:
	uint8                                             Pad_0[0x0030];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeAnimationTrackSetFactoryNode");
		return Clss;
	}

	bool SetCustomFrameRate(float* AttributeValue);
	bool RemoveCustomAnimationTrackUid(const class FString& AnimationTrackUid);
	class UClass* GetObjectClass();
	bool GetCustomFrameRate(float* AttributeValue);
	void GetCustomAnimationTrackUids(TArray<class FString>* OutAnimationTrackUids);
	int32 GetCustomAnimationTrackUidCount();
	void GetCustomAnimationTrackUid(int32 Index, class FString* OutAnimationTrackUid);
	bool AddCustomAnimationTrackUid(const class FString& AnimationTrackUid);
};

class UInterchangeActorFactoryNode : public UInterchangeFactoryBaseNode
{
public:
	uint8                                             Pad_0[0x0030];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeActorFactoryNode");
		return Clss;
	}

	bool SetCustomMobility(uint8* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomGlobalTransform(struct FTransform* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomActorClassName(const class FString& AttributeValue);
	bool GetCustomMobility(uint8* AttributeValue);
	bool GetCustomGlobalTransform(struct FTransform* AttributeValue);
	bool GetCustomActorClassName(class FString* AttributeValue);
};

class UInterchangePhysicalCameraFactoryNode : public UInterchangeActorFactoryNode
{
public:
	uint8                                             Pad_0[0x0040];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangePhysicalCameraFactoryNode");
		return Clss;
	}

	bool SetCustomSensorWidth(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomSensorHeight(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomFocusMethod(enum class EECameraFocusMethod* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomFocalLength(float* AttributeValue, bool bAddApplyDelegate);
	bool GetCustomSensorWidth(float* AttributeValue);
	bool GetCustomSensorHeight(float* AttributeValue);
	bool GetCustomFocusMethod(enum class EECameraFocusMethod* AttributeValue);
	bool GetCustomFocalLength(float* AttributeValue);
};

class UInterchangeStandardCameraFactoryNode : public UInterchangeActorFactoryNode
{
public:
	uint8                                             Pad_0[0x0060];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeStandardCameraFactoryNode");
		return Clss;
	}

	bool SetCustomWidth(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomProjectionMode(enum class EECameraProjectionMode* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomNearClipPlane(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomFieldOfView(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomFarClipPlane(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomAspectRatio(float* AttributeValue, bool bAddApplyDelegate);
	bool GetCustomWidth(float* AttributeValue);
	bool GetCustomProjectionMode(enum class EECameraProjectionMode* AttributeValue);
	bool GetCustomNearClipPlane(float* AttributeValue);
	bool GetCustomFieldOfView(float* AttributeValue);
	bool GetCustomFarClipPlane(float* AttributeValue);
	bool GetCustomAspectRatio(float* AttributeValue);
};

class UInterchangeBaseLightFactoryNode : public UInterchangeActorFactoryNode
{
public:
	uint8                                             Pad_0[0x0040];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeBaseLightFactoryNode");
		return Clss;
	}

	bool SetCustomUseTemperature(bool AttributeValue, bool bAddApplyDelegate);
	bool SetCustomTemperature(float AttributeValue, bool bAddApplyDelegate);
	bool SetCustomLightColor(struct FColor* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomIntensity(float AttributeValue, bool bAddApplyDelegate);
	bool GetCustomUseTemperature(bool* AttributeValue);
	bool GetCustomTemperature(float* AttributeValue);
	bool GetCustomLightColor(struct FColor* AttributeValue);
	bool GetCustomIntensity(float* AttributeValue);
};

class UInterchangeDirectionalLightFactoryNode : public UInterchangeBaseLightFactoryNode
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeDirectionalLightFactoryNode");
		return Clss;
	}
};

class UInterchangeLightFactoryNode : public UInterchangeBaseLightFactoryNode
{
public:
	uint8                                             Pad_0[0x0030];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeLightFactoryNode");
		return Clss;
	}

	bool SetCustomIntensityUnits(enum class EELightUnits AttributeValue, bool bAddApplyDelegate);
	bool SetCustomIESTexture(const class FString& AttributeValue);
	bool SetCustomAttenuationRadius(float AttributeValue, bool bAddApplyDelegate);
	bool GetCustomIntensityUnits(enum class EELightUnits* AttributeValue);
	bool GetCustomIESTexture(class FString* AttributeValue);
	bool GetCustomAttenuationRadius(float* AttributeValue);
};

class UInterchangeRectLightFactoryNode : public UInterchangeLightFactoryNode
{
public:
	uint8                                             Pad_0[0x0020];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeRectLightFactoryNode");
		return Clss;
	}

	bool SetCustomSourceWidth(float AttributeValue, bool bAddApplyDelegate);
	bool SetCustomSourceHeight(float AttributeValue, bool bAddApplyDelegate);
	bool GetCustomSourceWidth(float* AttributeValue);
	bool GetCustomSourceHeight(float* AttributeValue);
};

class UInterchangePointLightFactoryNode : public UInterchangeLightFactoryNode
{
public:
	uint8                                             Pad_0[0x0020];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangePointLightFactoryNode");
		return Clss;
	}

	bool SetCustomUseInverseSquaredFalloff(bool AttributeValue, bool bAddApplyDelegate);
	bool SetCustomLightFalloffExponent(float AttributeValue, bool bAddApplyDelegate);
	bool GetCustomUseInverseSquaredFalloff(bool* AttributeValue);
	bool GetCustomLightFalloffExponent(float* AttributeValue);
};

class UInterchangeSpotLightFactoryNode : public UInterchangePointLightFactoryNode
{
public:
	uint8                                             Pad_0[0x0020];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeSpotLightFactoryNode");
		return Clss;
	}

	bool SetCustomOuterConeAngle(float AttributeValue, bool bAddApplyDelegate);
	bool SetCustomInnerConeAngle(float AttributeValue, bool bAddApplyDelegate);
	bool GetCustomOuterConeAngle(float* AttributeValue);
	bool GetCustomInnerConeAngle(float* AttributeValue);
};

class UInterchangePhysicsAssetFactoryNode : public UInterchangeFactoryBaseNode
{
public:
	uint8                                             Pad_0[0x0030];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangePhysicsAssetFactoryNode");
		return Clss;
	}

	bool SetCustomSkeletalMeshUid(const class FString& AttributeValue);
	void InitializePhysicsAssetNode(const class FString& UniqueID, const class FString& DisplayLabel, const class FString& InAssetClass);
	class UClass* GetObjectClass();
	bool GetCustomSkeletalMeshUid(class FString* AttributeValue);
};

class UInterchangeSceneVariantSetsFactoryNode : public UInterchangeFactoryBaseNode
{
public:
	uint8                                             Pad_0[0x0020];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeSceneVariantSetsFactoryNode");
		return Clss;
	}

	bool RemoveCustomVariantSetUid(const class FString& VariantUid);
	class UClass* GetObjectClass();
	void GetCustomVariantSetUids(TArray<class FString>* OutVariantUids);
	int32 GetCustomVariantSetUidCount();
	void GetCustomVariantSetUid(int32 Index, class FString* OutVariantUid);
	bool AddCustomVariantSetUid(const class FString& VariantUid);
};

class UInterchangeSkeletonFactoryNode : public UInterchangeFactoryBaseNode
{
public:
	uint8                                             Pad_0[0x0050];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeSkeletonFactoryNode");
		return Clss;
	}

	bool SetCustomUseTimeZeroForBindPose(bool* AttributeValue);
	bool SetCustomSkeletalMeshFactoryNodeUid(const class FString& AttributeValue);
	bool SetCustomRootJointUid(const class FString& AttributeValue);
	void InitializeSkeletonNode(const class FString& UniqueID, const class FString& DisplayLabel, const class FString& InAssetClass);
	class UClass* GetObjectClass();
	bool GetCustomUseTimeZeroForBindPose(bool* AttributeValue);
	bool GetCustomSkeletalMeshFactoryNodeUid(class FString* AttributeValue);
	bool GetCustomRootJointUid(class FString* AttributeValue);
};

class UInterchangeTextureFactoryNode : public UInterchangeFactoryBaseNode
{
public:
	uint8                                             Pad_0[0x0290];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeTextureFactoryNode");
		return Clss;
	}

	bool SetCustomVirtualTextureStreaming(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomTranslatedTextureNodeUid(const class FString& AttributeValue);
	bool SetCustomSRGB(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomPreferCompressedSourceData(bool* AttributeValue);
	bool SetCustomPowerOfTwoMode(uint8* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomPaddingColor(struct FColor* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomMipLoadOptions(uint8* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomMipGenSettings(uint8* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomMaxTextureSize(int32* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomLossyCompressionAmount(uint8* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomLODGroup(uint8* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomLODBias(int32* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomFilter(uint8* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomDownscaleOptions(uint8* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomDownscale(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomDeferCompression(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomCompressionSettings(uint8* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomCompressionQuality(uint8* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomCompressionNoAlpha(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomCompositeTextureMode(uint8* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomCompositePower(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomChromaKeyThreshold(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomChromaKeyColor(struct FColor* AttributeValue, bool bAddApplyDelegate);
	bool SetCustombUseLegacyGamma(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustombPreserveBorder(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustombFlipGreenChannel(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustombDoScaleMipsForAlphaCoverage(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustombChromaKeyTexture(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomAlphaCoverageThresholds(struct FVector4* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomAllowNonPowerOfTwo(bool* AttributeValue);
	bool SetCustomAdjustVibrance(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomAdjustSaturation(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomAdjustRGBCurve(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomAdjustMinAlpha(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomAdjustMaxAlpha(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomAdjustHue(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomAdjustBrightnessCurve(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomAdjustBrightness(float* AttributeValue, bool bAddApplyDelegate);
	void InitializeTextureNode(const class FString& UniqueID, const class FString& DisplayLabel, const class FString& InAssetName);
	class UClass* GetObjectClass();
	bool GetCustomVirtualTextureStreaming(bool* AttributeValue);
	bool GetCustomTranslatedTextureNodeUid(class FString* AttributeValue);
	bool GetCustomSRGB(bool* AttributeValue);
	bool GetCustomPreferCompressedSourceData(bool* AttributeValue);
	bool GetCustomPowerOfTwoMode(uint8* AttributeValue);
	bool GetCustomPaddingColor(struct FColor* AttributeValue);
	bool GetCustomMipLoadOptions(uint8* AttributeValue);
	bool GetCustomMipGenSettings(uint8* AttributeValue);
	bool GetCustomMaxTextureSize(int32* AttributeValue);
	bool GetCustomLossyCompressionAmount(uint8* AttributeValue);
	bool GetCustomLODGroup(uint8* AttributeValue);
	bool GetCustomLODBias(int32* AttributeValue);
	bool GetCustomFilter(uint8* AttributeValue);
	bool GetCustomDownscaleOptions(uint8* AttributeValue);
	bool GetCustomDownscale(float* AttributeValue);
	bool GetCustomDeferCompression(bool* AttributeValue);
	bool GetCustomCompressionSettings(uint8* AttributeValue);
	bool GetCustomCompressionQuality(uint8* AttributeValue);
	bool GetCustomCompressionNoAlpha(bool* AttributeValue);
	bool GetCustomCompositeTextureMode(uint8* AttributeValue);
	bool GetCustomCompositePower(float* AttributeValue);
	bool GetCustomChromaKeyThreshold(float* AttributeValue);
	bool GetCustomChromaKeyColor(struct FColor* AttributeValue);
	bool GetCustombUseLegacyGamma(bool* AttributeValue);
	bool GetCustombPreserveBorder(bool* AttributeValue);
	bool GetCustombFlipGreenChannel(bool* AttributeValue);
	bool GetCustombDoScaleMipsForAlphaCoverage(bool* AttributeValue);
	bool GetCustombChromaKeyTexture(bool* AttributeValue);
	bool GetCustomAlphaCoverageThresholds(struct FVector4* AttributeValue);
	bool GetCustomAllowNonPowerOfTwo(bool* AttributeValue);
	bool GetCustomAdjustVibrance(float* AttributeValue);
	bool GetCustomAdjustSaturation(float* AttributeValue);
	bool GetCustomAdjustRGBCurve(float* AttributeValue);
	bool GetCustomAdjustMinAlpha(float* AttributeValue);
	bool GetCustomAdjustMaxAlpha(float* AttributeValue);
	bool GetCustomAdjustHue(float* AttributeValue);
	bool GetCustomAdjustBrightnessCurve(float* AttributeValue);
	bool GetCustomAdjustBrightness(float* AttributeValue);
};

class UInterchangeTexture2DArrayFactoryNode : public UInterchangeTextureFactoryNode
{
public:
	uint8                                             Pad_0[0x0030];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeTexture2DArrayFactoryNode");
		return Clss;
	}

	bool SetCustomAddressZ(uint8 AttributeValue, bool bAddApplyDelegate);
	bool GetCustomAddressZ(uint8* AttributeValue);
	bool GetCustomAddressY(uint8* AttributeValue);
	bool GetCustomAddressX(uint8* AttributeValue);
};

class UInterchangeTexture2DFactoryNode : public UInterchangeTextureFactoryNode
{
public:
	uint8                                             Pad_0[0x0098];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeTexture2DFactoryNode");
		return Clss;
	}

	void SetSourceBlocks(TMap<int32, class FString>* InSourceBlocks);
	void SetSourceBlockByCoordinates(int32 X, int32 Y, const class FString& InSourceFile);
	void SetSourceBlock(int32 BlockIndex, const class FString& InSourceFile);
	bool SetCustomAddressY(enum class ETextureAddress AttributeValue, bool bAddApplyDelegate);
	bool SetCustomAddressX(enum class ETextureAddress AttributeValue, bool bAddApplyDelegate);
	TMap<int32, class FString> GetSourceBlocks();
	bool GetSourceBlockByCoordinates(int32 X, int32 Y, class FString* OutSourceFile);
	bool GetSourceBlock(int32 BlockIndex, class FString* OutSourceFile);
	bool GetCustomAddressY(enum class ETextureAddress* AttributeValue);
	bool GetCustomAddressX(enum class ETextureAddress* AttributeValue);
};

class UInterchangeTextureCubeArrayFactoryNode : public UInterchangeTextureFactoryNode
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeTextureCubeArrayFactoryNode");
		return Clss;
	}
};

class UInterchangeTextureCubeFactoryNode : public UInterchangeTextureFactoryNode
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeTextureCubeFactoryNode");
		return Clss;
	}
};

class UInterchangeTextureLightProfileFactoryNode : public UInterchangeTexture2DFactoryNode
{
public:
	uint8                                             Pad_0[0x0020];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeTextureLightProfileFactoryNode");
		return Clss;
	}

	bool SetCustomTextureMultiplier(float AttributeValue, bool bAddApplyDelegate);
	bool SetCustomBrightness(float AttributeValue, bool bAddApplyDelegate);
	bool GetCustomTextureMultiplier(float* AttributeValue);
	bool GetCustomBrightness(float* AttributeValue);
};

class UInterchangeVolumeTextureFactoryNode : public UInterchangeTextureFactoryNode
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeVolumeTextureFactoryNode");
		return Clss;
	}
};

class UInterchangeAnimSequenceFactoryNode : public UInterchangeFactoryBaseNode
{
public:
	uint8                                             Pad_0[0x0340];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeAnimSequenceFactoryNode");
		return Clss;
	}

	bool SetCustomSkeletonSoftObjectPath(struct FSoftObjectPath* AttributeValue);
	bool SetCustomSkeletonFactoryNodeUid(const class FString& AttributeValue);
	bool SetCustomRemoveCurveRedundantKeys(bool* AttributeValue);
	bool SetCustomMaterialDriveParameterOnCustomAttribute(bool* AttributeValue);
	bool SetCustomImportBoneTracksSampleRate(double* AttributeValue);
	bool SetCustomImportBoneTracksRangeStop(double* AttributeValue);
	bool SetCustomImportBoneTracksRangeStart(double* AttributeValue);
	bool SetCustomImportBoneTracks(bool* AttributeValue);
	bool SetCustomImportAttributeCurves(bool* AttributeValue);
	bool SetCustomDoNotImportCurveWithZero(bool* AttributeValue);
	bool SetCustomDeleteExistingNonCurveCustomAttributes(bool* AttributeValue);
	bool SetCustomDeleteExistingMorphTargetCurves(bool* AttributeValue);
	bool SetCustomDeleteExistingCustomAttributeCurves(bool* AttributeValue);
	bool SetCustomAddCurveMetadataToSkeleton(bool* AttributeValue);
	void SetAnimationPayloadKeysForSceneNodeUids(TMap<class FString, class FString>* SceneNodeAnimationPayloadKeyUids, TMap<class FString, uint8>* SceneNodeAnimationPayloadKeyTypes);
	void SetAnimationPayloadKeysForMorphTargetNodeUids(TMap<class FString, class FString>* MorphTargetAnimationPayloadKeyUids, TMap<class FString, uint8>* MorphTargetAnimationPayloadKeyTypes);
	bool SetAnimatedMaterialCurveSuffixe(const class FString& MaterialCurveSuffixe);
	bool SetAnimatedAttributeStepCurveName(const class FString& AttributeStepCurveName);
	bool SetAnimatedAttributeCurveName(const class FString& AttributeCurveName);
	bool RemoveAnimatedMaterialCurveSuffixe(const class FString& MaterialCurveSuffixe);
	bool RemoveAnimatedAttributeStepCurveName(const class FString& AttributeStepCurveName);
	bool RemoveAnimatedAttributeCurveName(const class FString& AttributeCurveName);
	void InitializeAnimSequenceNode(const class FString& UniqueID, const class FString& DisplayLabel);
	void GetSceneNodeAnimationPayloadKeys(TMap<class FString, struct FInterchangeAnimationPayLoadKey>* OutSceneNodeAnimationPayloadKeys);
	class UClass* GetObjectClass();
	void GetMorphTargetNodeAnimationPayloadKeys(TMap<class FString, struct FInterchangeAnimationPayLoadKey>* OutMorphTargetNodeAnimationPayloads);
	bool GetCustomSkeletonSoftObjectPath(struct FSoftObjectPath* AttributeValue);
	bool GetCustomSkeletonFactoryNodeUid(class FString* AttributeValue);
	bool GetCustomRemoveCurveRedundantKeys(bool* AttributeValue);
	bool GetCustomMaterialDriveParameterOnCustomAttribute(bool* AttributeValue);
	bool GetCustomImportBoneTracksSampleRate(double* AttributeValue);
	bool GetCustomImportBoneTracksRangeStop(double* AttributeValue);
	bool GetCustomImportBoneTracksRangeStart(double* AttributeValue);
	bool GetCustomImportBoneTracks(bool* AttributeValue);
	bool GetCustomImportAttributeCurves(bool* AttributeValue);
	bool GetCustomDoNotImportCurveWithZero(bool* AttributeValue);
	bool GetCustomDeleteExistingNonCurveCustomAttributes(bool* AttributeValue);
	bool GetCustomDeleteExistingMorphTargetCurves(bool* AttributeValue);
	bool GetCustomDeleteExistingCustomAttributeCurves(bool* AttributeValue);
	bool GetCustomAddCurveMetadataToSkeleton(bool* AttributeValue);
	int32 GetAnimatedMaterialCurveSuffixesCount();
	void GetAnimatedMaterialCurveSuffixes(TArray<class FString>* OutMaterialCurveSuffixes);
	void GetAnimatedMaterialCurveSuffixe(int32 Index, class FString* OutMaterialCurveSuffixe);
	int32 GetAnimatedAttributeStepCurveNamesCount();
	void GetAnimatedAttributeStepCurveNames(TArray<class FString>* OutAttributeStepCurveNames);
	void GetAnimatedAttributeStepCurveName(int32 Index, class FString* OutAttributeStepCurveName);
	int32 GetAnimatedAttributeCurveNamesCount();
	void GetAnimatedAttributeCurveNames(TArray<class FString>* OutAttributeCurveNames);
	void GetAnimatedAttributeCurveName(int32 Index, class FString* OutAttributeCurveName);
};

class UInterchangeCommonPipelineDataFactoryNode : public UInterchangeFactoryBaseNode
{
public:
	uint8                                             Pad_0[0x0020];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeCommonPipelineDataFactoryNode");
		return Clss;
	}

	bool SetCustomGlobalOffsetTransform(class UInterchangeBaseNodeContainer* NodeContainer, struct FTransform* AttributeValue);
	bool SetBakeMeshes(class UInterchangeBaseNodeContainer* NodeContainer, bool* AttributeValue);
	bool GetCustomGlobalOffsetTransform(struct FTransform* AttributeValue);
	bool GetBakeMeshes(bool* AttributeValue);
};

class UInterchangeBaseMaterialFactoryNode : public UInterchangeFactoryBaseNode
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeBaseMaterialFactoryNode");
		return Clss;
	}
};

class UInterchangeMaterialFactoryNode : public UInterchangeBaseMaterialFactoryNode
{
public:
	uint8                                             Pad_0[0x0070];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeMaterialFactoryNode");
		return Clss;
	}

	bool SetCustomTwoSided(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomTranslucencyLightingMode(enum class EETranslucencyLightingMode* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomShadingModel(enum class EEMaterialShadingModel* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomScreenSpaceReflections(bool* AttributeValue);
	bool SetCustomRefractionMethod(enum class EERefractionMode* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomOpacityMaskClipValue(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomBlendMode(enum class EEBlendMode* AttributeValue, bool bAddApplyDelegate);
	bool GetTransmissionColorConnection(class FString* ExpressionNodeUid, class FString* OutputName);
	bool GetTangentConnection(class FString* ExpressionNodeUid, class FString* OutputName);
	bool GetSubsurfaceConnection(class FString* ExpressionNodeUid, class FString* OutputName);
	bool GetSpecularConnection(class FString* ExpressionNodeUid, class FString* OutputName);
	bool GetRoughnessConnection(class FString* ExpressionNodeUid, class FString* OutputName);
	bool GetRefractionConnection(class FString* ExpressionNodeUid, class FString* OutputName);
	bool GetOpacityConnection(class FString* ExpressionNodeUid, class FString* OutputName);
	bool GetOcclusionConnection(class FString* ExpressionNodeUid, class FString* OutputName);
	class UClass* GetObjectClass();
	bool GetNormalConnection(class FString* ExpressionNodeUid, class FString* OutputName);
	bool GetMetallicConnection(class FString* ExpressionNodeUid, class FString* OutputName);
	bool GetFuzzColorConnection(class FString* ExpressionNodeUid, class FString* OutputName);
	bool GetEmissiveColorConnection(class FString* ExpressionNodeUid, class FString* OutputName);
	bool GetCustomTwoSided(bool* AttributeValue);
	bool GetCustomTranslucencyLightingMode(enum class EETranslucencyLightingMode* AttributeValue);
	bool GetCustomShadingModel(enum class EEMaterialShadingModel* AttributeValue);
	bool GetCustomScreenSpaceReflections(bool* AttributeValue);
	bool GetCustomRefractionMethod(enum class EERefractionMode* AttributeValue);
	bool GetCustomOpacityMaskClipValue(float* AttributeValue);
	bool GetCustomBlendMode(enum class EEBlendMode* AttributeValue);
	bool GetClothConnection(class FString* ExpressionNodeUid, class FString* OutputName);
	bool GetClearCoatRoughnessConnection(class FString* ExpressionNodeUid, class FString* OutputName);
	bool GetClearCoatNormalConnection(class FString* ExpressionNodeUid, class FString* OutputName);
	bool GetClearCoatConnection(class FString* ExpressionNodeUid, class FString* OutputName);
	bool GetBaseColorConnection(class FString* ExpressionNodeUid, class FString* OutputName);
	bool GetAnisotropyConnection(class FString* ExpressionNodeUid, class FString* OutputName);
	bool ConnectToTransmissionColor(const class FString& AttributeValue);
	bool ConnectToTangent(const class FString& ExpressionNodeUid);
	bool ConnectToSubsurface(const class FString& ExpressionNodeUid);
	bool ConnectToSpecular(const class FString& ExpressionNodeUid);
	bool ConnectToRoughness(const class FString& ExpressionNodeUid);
	bool ConnectToRefraction(const class FString& AttributeValue);
	bool ConnectToOpacity(const class FString& AttributeValue);
	bool ConnectToOcclusion(const class FString& AttributeValue);
	bool ConnectToNormal(const class FString& ExpressionNodeUid);
	bool ConnectToMetallic(const class FString& AttributeValue);
	bool ConnectToFuzzColor(const class FString& AttributeValue);
	bool ConnectToEmissiveColor(const class FString& ExpressionNodeUid);
	bool ConnectToCloth(const class FString& AttributeValue);
	bool ConnectToClearCoatRoughness(const class FString& AttributeValue);
	bool ConnectToClearCoatNormal(const class FString& AttributeValue);
	bool ConnectToClearCoat(const class FString& AttributeValue);
	bool ConnectToBaseColor(const class FString& AttributeValue);
	bool ConnectToAnisotropy(const class FString& ExpressionNodeUid);
	bool ConnectOutputToTransmissionColor(const class FString& ExpressionNodeUid, const class FString& OutputName);
	bool ConnectOutputToTangent(const class FString& ExpressionNodeUid, const class FString& OutputName);
	bool ConnectOutputToSubsurface(const class FString& ExpressionNodeUid, const class FString& OutputName);
	bool ConnectOutputToSpecular(const class FString& ExpressionNodeUid, const class FString& OutputName);
	bool ConnectOutputToRoughness(const class FString& ExpressionNodeUid, const class FString& OutputName);
	bool ConnectOutputToRefraction(const class FString& ExpressionNodeUid, const class FString& OutputName);
	bool ConnectOutputToOpacity(const class FString& ExpressionNodeUid, const class FString& OutputName);
	bool ConnectOutputToOcclusion(const class FString& ExpressionNodeUid, const class FString& OutputName);
	bool ConnectOutputToNormal(const class FString& ExpressionNodeUid, const class FString& OutputName);
	bool ConnectOutputToMetallic(const class FString& ExpressionNodeUid, const class FString& OutputName);
	bool ConnectOutputToFuzzColor(const class FString& ExpressionNodeUid, const class FString& OutputName);
	bool ConnectOutputToEmissiveColor(const class FString& ExpressionNodeUid, const class FString& OutputName);
	bool ConnectOutputToCloth(const class FString& ExpressionNodeUid, const class FString& OutputName);
	bool ConnectOutputToClearCoatRoughness(const class FString& ExpressionNodeUid, const class FString& OutputName);
	bool ConnectOutputToClearCoatNormal(const class FString& ExpressionNodeUid, const class FString& OutputName);
	bool ConnectOutputToClearCoat(const class FString& ExpressionNodeUid, const class FString& OutputName);
	bool ConnectOutputToBaseColor(const class FString& ExpressionNodeUid, const class FString& OutputName);
	bool ConnectOutputToAnisotropy(const class FString& ExpressionNodeUid, const class FString& OutputName);
};

class UInterchangeMaterialExpressionFactoryNode : public UInterchangeFactoryBaseNode
{
public:
	uint8                                             Pad_0[0x0010];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeMaterialExpressionFactoryNode");
		return Clss;
	}

	bool SetCustomExpressionClassName(const class FString& AttributeValue);
	bool GetCustomExpressionClassName(class FString* AttributeValue);
};

class UInterchangeMaterialInstanceFactoryNode : public UInterchangeBaseMaterialFactoryNode
{
public:
	uint8                                             Pad_0[0x0020];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeMaterialInstanceFactoryNode");
		return Clss;
	}

	bool SetCustomParent(const class FString& AttributeValue);
	bool SetCustomInstanceClassName(const class FString& AttributeValue);
	bool GetCustomParent(class FString* AttributeValue);
	bool GetCustomInstanceClassName(class FString* AttributeValue);
};

class UInterchangeMaterialFunctionCallExpressionFactoryNode : public UInterchangeMaterialExpressionFactoryNode
{
public:
	uint8                                             Pad_0[0x0010];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeMaterialFunctionCallExpressionFactoryNode");
		return Clss;
	}

	bool SetCustomMaterialFunctionDependency(const class FString& AttributeValue);
	bool GetCustomMaterialFunctionDependency(class FString* AttributeValue);
};

class UInterchangeMaterialFunctionFactoryNode : public UInterchangeBaseMaterialFactoryNode
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeMaterialFunctionFactoryNode");
		return Clss;
	}

	class UClass* GetObjectClass();
	bool GetInputConnection(const class FString& InputName, class FString* ExpressionNodeUid, class FString* OutputName);
};

class UInterchangeMeshActorFactoryNode : public UInterchangeActorFactoryNode
{
public:
	uint8                                             Pad_0[0x0098];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeMeshActorFactoryNode");
		return Clss;
	}

	bool SetSlotMaterialDependencyUid(const class FString& SlotName, const class FString& MaterialDependencyUid);
	bool SetCustomGeometricTransform(struct FTransform* AttributeValue);
	bool SetCustomAnimationAssetUidToPlay(const class FString& AttributeValue);
	bool RemoveSlotMaterialDependencyUid(const class FString& SlotName);
	bool GetSlotMaterialDependencyUid(const class FString& SlotName, class FString* OutMaterialDependency);
	void GetSlotMaterialDependencies(TMap<class FString, class FString>* OutMaterialDependencies);
	bool GetCustomGeometricTransform(struct FTransform* AttributeValue);
	bool GetCustomAnimationAssetUidToPlay(class FString* AttributeValue);
};

class UInterchangeMeshFactoryNode : public UInterchangeFactoryBaseNode
{
public:
	uint8                                             Pad_0[0x0170];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeMeshFactoryNode");
		return Clss;
	}

	bool SetSlotMaterialDependencyUid(const class FString& SlotName, const class FString& MaterialDependencyUid);
	bool SetCustomVertexColorReplace(bool* AttributeValue);
	bool SetCustomVertexColorOverride(struct FColor* AttributeValue);
	bool SetCustomVertexColorIgnore(bool* AttributeValue);
	bool SetCustomUseMikkTSpace(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomUseHighPrecisionTangentBasis(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomUseFullPrecisionUVs(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomUseBackwardsCompatibleF16TruncUVs(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomRemoveDegenerates(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomRecomputeTangents(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomRecomputeNormals(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomLODGroup(class FName* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomComputeWeightedNormals(bool* AttributeValue, bool bAddApplyDelegate);
	bool RemoveSlotMaterialDependencyUid(const class FString& SlotName);
	bool RemoveLodDataUniqueId(const class FString& LodDataUniqueId);
	bool GetSlotMaterialDependencyUid(const class FString& SlotName, class FString* OutMaterialDependency);
	void GetSlotMaterialDependencies(TMap<class FString, class FString>* OutMaterialDependencies);
	void GetLodDataUniqueIds(TArray<class FString>* OutLodDataUniqueIds);
	int32 GetLodDataCount();
	bool GetCustomVertexColorReplace(bool* AttributeValue);
	bool GetCustomVertexColorOverride(struct FColor* AttributeValue);
	bool GetCustomVertexColorIgnore(bool* AttributeValue);
	bool GetCustomUseMikkTSpace(bool* AttributeValue);
	bool GetCustomUseHighPrecisionTangentBasis(bool* AttributeValue);
	bool GetCustomUseFullPrecisionUVs(bool* AttributeValue);
	bool GetCustomUseBackwardsCompatibleF16TruncUVs(bool* AttributeValue);
	bool GetCustomRemoveDegenerates(bool* AttributeValue);
	bool GetCustomRecomputeTangents(bool* AttributeValue);
	bool GetCustomRecomputeNormals(bool* AttributeValue);
	bool GetCustomLODGroup(class FName* AttributeValue);
	bool GetCustomComputeWeightedNormals(bool* AttributeValue);
	bool AddLodDataUniqueId(const class FString& LodDataUniqueId);
};

class UInterchangeSceneImportAssetFactoryNode : public UInterchangeFactoryBaseNode
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeSceneImportAssetFactoryNode");
		return Clss;
	}
};

class UInterchangeSkeletalMeshFactoryNode : public UInterchangeMeshFactoryNode
{
public:
	uint8                                             Pad_0[0x00C8];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeSkeletalMeshFactoryNode");
		return Clss;
	}

	bool SetCustomUseHighPrecisionSkinWeights(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomThresholdUV(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomThresholdTangentNormal(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomThresholdPosition(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomSkeletonSoftObjectPath(struct FSoftObjectPath* AttributeValue);
	bool SetCustomPhysicAssetSoftObjectPath(struct FSoftObjectPath* AttributeValue);
	bool SetCustomMorphThresholdPosition(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomImportMorphTarget(bool* AttributeValue);
	bool SetCustomImportContentType(enum class EEInterchangeSkeletalMeshContentType* AttributeValue);
	bool SetCustomCreatePhysicsAsset(bool* AttributeValue);
	bool SetCustomBoneInfluenceLimit(int32* AttributeValue, bool bAddApplyDelegate);
	void InitializeSkeletalMeshNode(const class FString& UniqueID, const class FString& DisplayLabel, const class FString& InAssetClass);
	class UClass* GetObjectClass();
	bool GetCustomUseHighPrecisionSkinWeights(bool* AttributeValue);
	bool GetCustomThresholdUV(float* AttributeValue);
	bool GetCustomThresholdTangentNormal(float* AttributeValue);
	bool GetCustomThresholdPosition(float* AttributeValue);
	bool GetCustomSkeletonSoftObjectPath(struct FSoftObjectPath* AttributeValue);
	bool GetCustomPhysicAssetSoftObjectPath(struct FSoftObjectPath* AttributeValue);
	bool GetCustomMorphThresholdPosition(float* AttributeValue);
	bool GetCustomImportMorphTarget(bool* AttributeValue);
	bool GetCustomImportContentType(enum class EEInterchangeSkeletalMeshContentType* AttributeValue);
	bool GetCustomCreatePhysicsAsset(bool* AttributeValue);
	bool GetCustomBoneInfluenceLimit(int32* AttributeValue);
};

class UInterchangeSkeletalMeshLodDataNode : public UInterchangeFactoryBaseNode
{
public:
	uint8                                             Pad_0[0x0030];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeSkeletalMeshLodDataNode");
		return Clss;
	}

	bool SetCustomSkeletonUid(const class FString& AttributeValue);
	bool RemoveMeshUid(const class FString& MeshName);
	bool RemoveAllMeshes();
	int32 GetMeshUidsCount();
	void GetMeshUids(TArray<class FString>* OutMeshNames);
	bool GetCustomSkeletonUid(class FString* AttributeValue);
	bool AddMeshUid(const class FString& MeshName);
};

class UInterchangeStaticMeshFactoryNode : public UInterchangeMeshFactoryNode
{
public:
	uint8                                             Pad_0[0x00E8];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeStaticMeshFactoryNode");
		return Clss;
	}

	bool SetCustomSupportFaceRemap(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomSrcLightmapIndex(int32* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomMinLightmapResolution(int32* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomMaxLumenMeshCards(int32* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomGenerateLightmapUVs(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomGenerateDistanceFieldAsIfTwoSided(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomDstLightmapIndex(int32* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomDistanceFieldResolutionScale(float* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomDistanceFieldReplacementMesh(struct FSoftObjectPath* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomBuildScale3D(struct FVector* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomBuildReversedIndexBuffer(bool* AttributeValue, bool bAddApplyDelegate);
	bool SetCustomBuildNanite(bool* AttributeValue, bool bAddApplyDelegate);
	bool RemoveSocketUd(const class FString& SocketUid);
	void InitializeStaticMeshNode(const class FString& UniqueID, const class FString& DisplayLabel, const class FString& InAssetClass);
	void GetSocketUids(TArray<class FString>* OutSocketUids);
	int32 GetSocketUidCount();
	class UClass* GetObjectClass();
	bool GetCustomSupportFaceRemap(bool* AttributeValue);
	bool GetCustomSrcLightmapIndex(int32* AttributeValue);
	bool GetCustomMinLightmapResolution(int32* AttributeValue);
	bool GetCustomMaxLumenMeshCards(int32* AttributeValue);
	bool GetCustomGenerateLightmapUVs(bool* AttributeValue);
	bool GetCustomGenerateDistanceFieldAsIfTwoSided(bool* AttributeValue);
	bool GetCustomDstLightmapIndex(int32* AttributeValue);
	bool GetCustomDistanceFieldResolutionScale(float* AttributeValue);
	bool GetCustomDistanceFieldReplacementMesh(struct FSoftObjectPath* AttributeValue);
	bool GetCustomBuildScale3D(struct FVector* AttributeValue);
	bool GetCustomBuildReversedIndexBuffer(bool* AttributeValue);
	bool GetCustomBuildNanite(bool* AttributeValue);
	bool AddSocketUids(TArray<class FString>* InSocketUids);
	bool AddSocketUid(const class FString& SocketUid);
};

class UInterchangeStaticMeshLodDataNode : public UInterchangeFactoryBaseNode
{
public:
	uint8                                             Pad_0[0x00C0];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("InterchangeStaticMeshLodDataNode");
		return Clss;
	}

	bool SetOneConvexHullPerUCX(bool AttributeValue);
	bool SetImportCollision(bool AttributeValue);
	bool RemoveSphereCollisionMeshUid(const class FString& MeshName);
	bool RemoveMeshUid(const class FString& MeshName);
	bool RemoveConvexCollisionMeshUid(const class FString& MeshName);
	bool RemoveCapsuleCollisionMeshUid(const class FString& MeshName);
	bool RemoveBoxCollisionMeshUid(const class FString& MeshName);
	bool RemoveAllSphereCollisionMeshes();
	bool RemoveAllMeshes();
	bool RemoveAllConvexCollisionMeshes();
	bool RemoveAllCapsuleCollisionMeshes();
	bool RemoveAllBoxCollisionMeshes();
	int32 GetSphereCollisionMeshUidsCount();
	void GetSphereCollisionMeshUids(TArray<class FString>* OutMeshNames);
	bool GetOneConvexHullPerUCX(bool* AttributeValue);
	int32 GetMeshUidsCount();
	void GetMeshUids(TArray<class FString>* OutMeshNames);
	bool GetImportCollision(bool* AttributeValue);
	int32 GetConvexCollisionMeshUidsCount();
	void GetConvexCollisionMeshUids(TArray<class FString>* OutMeshNames);
	int32 GetCapsuleCollisionMeshUidsCount();
	void GetCapsuleCollisionMeshUids(TArray<class FString>* OutMeshNames);
	int32 GetBoxCollisionMeshUidsCount();
	void GetBoxCollisionMeshUids(TArray<class FString>* OutMeshNames);
	bool AddSphereCollisionMeshUid(const class FString& MeshName);
	bool AddMeshUid(const class FString& MeshName);
	bool AddConvexCollisionMeshUid(const class FString& MeshName);
	bool AddCapsuleCollisionMeshUid(const class FString& MeshName);
	bool AddBoxCollisionMeshUid(const class FString& MeshName);
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
