#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

enum class ECollisionLimitType : uint8
{
	None                                      = 0,
	Spherical                                 = 1,
	Capsule                                   = 2,
	Box                                       = 3,
	Planar                                    = 4,
	ECollisionLimitType_MAX                   = 5,
};

enum class ECollisionSourceType : uint8
{
	AnimNode                                  = 0,
	DataAsset                                 = 1,
	PhysicsAsset                              = 2,
	ECollisionSourceType_MAX                  = 3,
};

enum class EKawaiiPhysicsSimulationSpace : uint8
{
	ComponentSpace                            = 0,
	WorldSpace                                = 1,
	BaseBoneSpace                             = 2,
	EKawaiiPhysicsSimulationSpace_MAX         = 3,
};

enum class EPlanarConstraint : uint8
{
	None                                      = 0,
	X                                         = 1,
	Y                                         = 2,
	Z                                         = 3,
	EPlanarConstraint_MAX                     = 4,
};

enum class EBoneForwardAxis : uint8
{
	X_Positive                                = 0,
	X_Negative                                = 1,
	Y_Positive                                = 2,
	Y_Negative                                = 3,
	Z_Positive                                = 4,
	Z_Negative                                = 5,
	EBoneForwardAxis_MAX                      = 6,
};

enum class EXPBDComplianceType : uint8
{
	Concrete                                  = 0,
	Wood                                      = 1,
	Leather                                   = 2,
	Tendon                                    = 3,
	Rubber                                    = 4,
	Muscle                                    = 5,
	Fat                                       = 6,
	EXPBDComplianceType_MAX                   = 7,
};

enum class EKawaiiPhysicsSetAlphaSource : uint8
{
	Curve                                     = 0,
	Constant                                  = 1,
	EKawaiiPhysicsSetAlphaSource_MAX          = 2,
};

enum class EExternalForceSpace : uint8
{
	ComponentSpace                            = 0,
	WorldSpace                                = 1,
	BoneSpace                                 = 2,
	EExternalForceSpace_MAX                   = 3,
};

enum class EExternalForceCurveEvaluateType : uint8
{
	Single                                    = 0,
	Average                                   = 1,
	Max                                       = 2,
	Min                                       = 3,
	EExternalForceCurveEvaluateType_MAX       = 4,
};

enum class EKawaiiPhysicsAccessExternalForceResult : uint8
{
	Valid                                     = 0,
	NotValid                                  = 1,
	EKawaiiPhysicsAccessExternalForceResult_MAX = 2,
};

enum class ESyncBoneDirection : uint8
{
	Both                                      = 0,
	Positive                                  = 1,
	Negative                                  = 2,
	None                                      = 3,
	ESyncBoneDirection_MAX                    = 4,
};

struct FCollisionLimitBase
{
public:
	struct FBoneReference                             DrivingBone;
	uint8                                             Pad_0[0x0004];
	struct FVector                                    OffsetLocation;
	struct FRotator                                   OffsetRotation;
	struct FVector                                    Location;
	struct FQuat                                      Rotation;
	bool                                              bEnable;
	enum class EECollisionSourceType                  SourceType;
	uint8                                             Pad_1[0x000E];
};

struct FSphericalLimit : public FCollisionLimitBase
{
public:
};

struct FCapsuleLimit : public FCollisionLimitBase
{
public:
};

struct FBoxLimit : public FCollisionLimitBase
{
public:
	uint8                                             Pad_0[0x0010];
};

struct FPlanarLimit : public FCollisionLimitBase
{
public:
	struct FPlane                                     Plane;
};

struct FKawaiiPhysicsSharedCollisionData
{
public:
	uint8                                             Pad_0[0x0040];
};

struct FKawaiiPhysicsRootBoneSetting
{
public:
	struct FBoneReference                             RootBone;
	uint8                                             Pad_0[0x0004];
	TArray<struct FBoneReference>                     OverrideExcludeBones;
	bool                                              bUseOverrideExcludeBones;
	uint8                                             Pad_1[0x0007];
};

struct FKawaiiPhysicsSettings
{
public:
	float                                             Damping;
	float                                             Stiffness;
	float                                             WorldDampingLocation;
	float                                             WorldDampingRotation;
	float                                             Radius;
	float                                             LimitAngle;
};

struct FKawaiiPhysicsModifyBone
{
public:
	struct FBoneReference                             BoneRef;
	int32                                             Index;
	int32                                             ParentIndex;
	uint8                                             Pad_0[0x0004];
	TArray<int32>                                     ChildIndices;
	struct FKawaiiPhysicsSettings                     PhysicsSettings;
	struct FVector                                    Location;
	struct FVector                                    PrevLocation;
	uint8                                             Pad_1[0x0008];
	struct FQuat                                      PrevRotation;
	struct FVector                                    PoseLocation;
	uint8                                             Pad_2[0x0008];
	struct FQuat                                      PoseRotation;
	struct FVector                                    PoseScale;
	float                                             BoneLength;
	float                                             LengthFromRoot;
	float                                             LengthRateFromRoot;
	bool                                              bDummy;
	bool                                              bSkipSimulate;
	uint8                                             Pad_3[0x000A];
};

struct FModifyBoneConstraint
{
public:
	struct FBoneReference                             Bone1;
	struct FBoneReference                             Bone2;
	bool                                              bOverrideCompliance;
	enum class EEXPBDComplianceType                   ComplianceType;
	uint8                                             Pad_0[0x0002];
	int32                                             ModifyBoneIndex1;
	int32                                             ModifyBoneIndex2;
	float                                             Length;
	bool                                              bIsDummy;
	uint8                                             Pad_1[0x0003];
	float                                             Lambda;
};

struct FAnimNode_KawaiiPhysics : public FAnimNode_SkeletalControlBase
{
public:
	struct FBoneReference                             RootBone;
	uint8                                             Pad_0[0x0004];
	TArray<struct FBoneReference>                     ExcludeBones;
	TArray<struct FKawaiiPhysicsRootBoneSetting>      AdditionalRootBones;
	float                                             DummyBoneLength;
	enum class EEBoneForwardAxis                      BoneForwardAxis;
	uint8                                             Pad_1[0x0003];
	struct FKawaiiPhysicsSettings                     PhysicsSettings;
	enum class EEKawaiiPhysicsSimulationSpace         SimulationSpace;
	uint8                                             Pad_2[0x0003];
	struct FBoneReference                             SimulationBaseBone;
	int32                                             TargetFramerate;
	bool                                              OverrideTargetFramerate;
	uint8                                             Pad_3[0x0003];
	int32                                             WarmUpFrames;
	bool                                              bUseWarmUpWhenResetDynamics;
	bool                                              bNeedWarmUp;
	uint8                                             Pad_4[0x0002];
	float                                             TeleportDistanceThreshold;
	float                                             TeleportRotationThreshold;
	enum class EEPlanarConstraint                     PlanarConstraint;
	uint8                                             Pad_5[0x0007];
	struct FVector                                    SkelCompMoveScale;
	bool                                              bUpdatePhysicsSettingsInGame;
	bool                                              ResetBoneTransformWhenBoneNotFound;
	uint8                                             Pad_6[0x0006];
	struct FRuntimeFloatCurve                         DampingCurveData;
	struct FRuntimeFloatCurve                         StiffnessCurveData;
	struct FRuntimeFloatCurve                         WorldDampingLocationCurveData;
	struct FRuntimeFloatCurve                         WorldDampingRotationCurveData;
	struct FRuntimeFloatCurve                         RadiusCurveData;
	struct FRuntimeFloatCurve                         LimitAngleCurveData;
	TArray<struct FSphericalLimit>                    SphericalLimits;
	TArray<struct FCapsuleLimit>                      CapsuleLimits;
	TArray<struct FBoxLimit>                          BoxLimits;
	TArray<struct FPlanarLimit>                       PlanarLimits;
	class UKawaiiPhysicsLimitsDataAsset*              LimitsDataAsset;
	class UPhysicsAsset*                              PhysicsAssetForLimits;
	TArray<struct FSphericalLimit>                    SphericalLimitsData;
	TArray<struct FCapsuleLimit>                      CapsuleLimitsData;
	TArray<struct FBoxLimit>                          BoxLimitsData;
	TArray<struct FPlanarLimit>                       PlanarLimitsData;
	bool                                              bSharedCollisionSource;
	bool                                              bUseSharedCollision;
	uint8                                             Pad_7[0x0002];
	struct FGameplayTag                               SharedCollisionGroupTag;
	enum class EEXPBDComplianceType                   BoneConstraintGlobalComplianceType;
	uint8                                             Pad_8[0x0003];
	int32                                             BoneConstraintIterationCountBeforeCollision;
	int32                                             BoneConstraintIterationCountAfterCollision;
	bool                                              bAutoAddChildDummyBoneConstraint;
	uint8                                             Pad_9[0x0003];
	TArray<struct FModifyBoneConstraint>              BoneConstraints;
	class UKawaiiPhysicsBoneConstraintsDataAsset*     BoneConstraintsDataAsset;
	TArray<struct FModifyBoneConstraint>              BoneConstraintsData;
	TArray<struct FModifyBoneConstraint>              MergedBoneConstraints;
	TArray<struct FKawaiiPhysicsSyncBone>             SyncBones;
	struct FVector                                    Gravity;
	bool                                              bUseLegacyGravity;
	bool                                              bUseDefaultGravityZProjectSetting;
	bool                                              bUseWorldSpaceGravity;
	bool                                              bEnableWind;
	float                                             WindScale;
	float                                             WindDirectionNoiseAngle;
	uint8                                             Pad_A[0x0004];
	struct FVector                                    SimpleExternalForce;
	bool                                              bUseWorldSpaceSimpleExternalForce;
	uint8                                             Pad_B[0x0007];
	TArray<struct FInstancedStruct>                   ExternalForces;
	TArray<class UKawaiiPhysics_CustomExternalForce*> CustomExternalForces;
	bool                                              bAllowWorldCollision;
	bool                                              bOverrideCollisionParams;
	uint8                                             Pad_C[0x0006];
	struct FBodyInstance                              CollisionChannelSettings;
	bool                                              bIgnoreSelfComponent;
	uint8                                             Pad_D[0x0007];
	TArray<struct FBoneReference>                     IgnoreBones;
	TArray<class FName>                               IgnoreBoneNamePrefix;
	struct FGameplayTag                               KawaiiPhysicsTag;
	uint8                                             Pad_E[0x0004];
	TArray<struct FKawaiiPhysicsModifyBone>           ModifyBones;
	float                                             DeltaTime;
	uint8                                             Pad_F[0x03AC];
};

struct FKawaiiPhysicsSyncBone
{
public:
	struct FBoneReference                             Bone;
	uint8                                             Pad_0[0x0004];
	TArray<struct FKawaiiPhysicsSyncTargetRoot>       TargetRoots;
	struct FVector                                    GlobalScale;
	struct FRuntimeFloatCurve                         ScaleCurveByDeltaDistance;
	enum class EESyncBoneDirection                    ApplyDirectionX;
	enum class EESyncBoneDirection                    ApplyDirectionY;
	enum class EESyncBoneDirection                    ApplyDirectionZ;
	uint8                                             Pad_1[0x0005];
	struct FVector                                    InitialPoseLocation;
	bool                                              bEnableDistanceAttenuation;
	uint8                                             Pad_2[0x0003];
	float                                             AttenuationInnerRadius;
	float                                             AttenuationOuterRadius;
	float                                             MaxAttenuationRate;
};

struct FKawaiiPhysicsSyncTarget
{
public:
	uint8                                             Pad_0[0x0008];
	float                                             ScaleByLengthRateCurve;
	float                                             LengthRateFromSyncTargetRoot;
	int32                                             ModifyBoneIndex;
	uint8                                             Pad_1[0x0004];
};

struct FKawaiiPhysicsSyncTargetRoot : public FKawaiiPhysicsSyncTarget
{
public:
	struct FBoneReference                             Bone;
	bool                                              bIncludeChildBones;
	uint8                                             Pad_0[0x0003];
	struct FRuntimeFloatCurve                         ScaleCurveByBoneLengthRate;
	TArray<struct FKawaiiPhysicsSyncTarget>           ChildTargets;
};

struct FKawaiiPhysics_ExternalForce
{
public:
	uint8                                             Pad_0[0x0010];
	bool                                              bIsEnabled;
	bool                                              bDrawDebug;
	uint8                                             Pad_1[0x0006];
	TArray<struct FBoneReference>                     ApplyBoneFilter;
	TArray<struct FBoneReference>                     IgnoreBoneFilter;
	enum class EEExternalForceSpace                   ExternalForceSpace;
	uint8                                             Pad_2[0x0003];
	struct FFloatInterval                             RandomForceScaleRange;
	uint8                                             Pad_3[0x0004];
	class UObject*                                    ExternalOwner;
	bool                                              bIsOneShot;
	uint8                                             Pad_4[0x0003];
	float                                             RandomizedForceScale;
	struct FVector                                    Force;
	struct FTransform                                 ComponentTransform;
	bool                                              bCanSelectForceSpace;
	uint8                                             Pad_5[0x000F];
};

struct FKawaiiPhysics_ExternalForce_Basic : public FKawaiiPhysics_ExternalForce
{
public:
	uint8                                             Pad_0[0x0010];
	struct FRuntimeFloatCurve                         ForceRateByBoneLengthRate;
	float                                             Interval;
	float                                             Time;
	float                                             PrevTime;
	uint8                                             Pad_1[0x000C];
};

struct FKawaiiPhysics_ExternalForce_Curve : public FKawaiiPhysics_ExternalForce
{
public:
	uint8                                             Pad_0[0x0180];
	enum class EEExternalForceCurveEvaluateType       CurveEvaluateType;
	uint8                                             Pad_1[0x0003];
	int32                                             SubstepCount;
	float                                             TimeScale;
	uint8                                             Pad_2[0x0004];
	struct FRuntimeFloatCurve                         ForceRateByBoneLengthRate;
	float                                             Time;
	float                                             PrevTime;
	float                                             MaxCurveTime;
	uint8                                             Pad_3[0x000C];
};

struct FKawaiiPhysics_ExternalForce_Gravity : public FKawaiiPhysics_ExternalForce
{
public:
	uint8                                             Pad_0[0x0080];
	bool                                              bUseCharacterGravityDirection;
	bool                                              bUseCharacterGravityScale;
	uint8                                             Pad_1[0x0006];
	struct FVector                                    OverrideGravityDirection;
	bool                                              bUseOverrideGravityDirection;
	uint8                                             Pad_2[0x0007];
	class ACharacter*                                 OwnerCharacter;
};

struct FKawaiiPhysics_ExternalForce_Wind : public FKawaiiPhysics_ExternalForce
{
public:
	uint8                                             Pad_0[0x0080];
	float                                             WindDirectionNoiseAngle;
	uint8                                             Pad_1[0x0004];
	class UWorld*                                     World;
};

struct FModifyBoneConstraintData
{
public:
	class FName                                       BoneName1;
	class FName                                       BoneName2;
	struct FBoneReference                             BoneReference1;
	struct FBoneReference                             BoneReference2;
	bool                                              bOverrideCompliance;
	enum class EEXPBDComplianceType                   ComplianceType;
	uint8                                             Pad_0[0x0002];
};

struct FRegexPatternBoneSet
{
public:
	class FString                                     RegexPatternBone1;
	class FString                                     RegexPatternBone2;
};

struct FKawaiiPhysicsReference : public FAnimNodeReference
{
public:
};

struct FCollisionLimitDataBase
{
public:
	struct FBoneReference                             DrivingBoneReference;
	class FName                                       DrivingBoneName;
	struct FVector                                    OffsetLocation;
	struct FRotator                                   OffsetRotation;
	struct FVector                                    Location;
	uint8                                             Pad_0[0x0008];
	struct FQuat                                      Rotation;
	struct FGuid                                      Guid;
};

struct FSphericalLimitData : public FCollisionLimitDataBase
{
public:
	float                                             Radius;
	enum class EESphericalLimitType                   LimitType;
	uint8                                             Pad_0[0x000B];
};

struct FCapsuleLimitData : public FCollisionLimitDataBase
{
public:
	float                                             Radius;
	float                                             Length;
	uint8                                             Pad_0[0x0008];
};

struct FBoxLimitData : public FCollisionLimitDataBase
{
public:
	struct FVector                                    Extent;
	uint8                                             Pad_0[0x0008];
};

struct FPlanarLimitData : public FCollisionLimitDataBase
{
public:
	struct FPlane                                     Plane;
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
