#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

namespace Params
{

struct ALandscapeProxy_SetVirtualTextureRenderPassType final
{
public:
	enum class EERuntimeVirtualTextureMainPassType    InType;
};

struct ALandscapeProxy_SetLandscapeMaterialVectorParameterValue final
{
public:
	class FName                                       ParameterName;
	struct FLinearColor                               Value;
};

struct ALandscapeProxy_SetLandscapeMaterialTextureParameterValue final
{
public:
	class FName                                       ParameterName;
	uint8                                             Pad_0[0x0004];
	class UTexture*                                   Value;
};

struct ALandscapeProxy_SetLandscapeMaterialScalarParameterValue final
{
public:
	class FName                                       ParameterName;
	float                                             Value;
};

struct ALandscapeProxy_LandscapeExportHeightmapToRenderTarget final
{
public:
	class UTextureRenderTarget2D*                     InRenderTarget;
	bool                                              InExportHeightIntoRGChannel;
	bool                                              InExportLandscapeProxies;
	bool                                              ReturnValue;
};

struct ALandscapeProxy_GetLandscapeActor final
{
public:
	class ALandscape*                                 ReturnValue;
};

struct ALandscapeProxy_EditorSetLandscapeMaterial final
{
public:
	class UMaterialInterface*                         NewLandscapeMaterial;
};

struct ALandscapeProxy_EditorApplySpline final
{
public:
	class USplineComponent*                           InSplineComponent;
	float                                             StartWidth;
	float                                             EndWidth;
	float                                             StartSideFalloff;
	float                                             EndSideFalloff;
	float                                             StartRoll;
	float                                             EndRoll;
	int32                                             NumSubdivisions;
	bool                                              bRaiseHeights;
	bool                                              bLowerHeights;
	uint8                                             Pad_0[0x0002];
	class ULandscapeLayerInfoObject*                  PaintLayer;
	class FName                                       EditLayerName;
};

struct ALandscapeProxy_ChangeLODDistanceFactor final
{
public:
	float                                             InLODDistanceFactor;
};

struct ALandscapeProxy_ChangeComponentScreenSizeToUseSubSections final
{
public:
	float                                             InComponentScreenSizeToUseSubSections;
};

struct ALandscape_RenderHeightmap final
{
public:
	struct FTransform                                 InWorldTransform;
	struct FBox2D                                     InExtents;
	class UTextureRenderTarget2D*                     OutRenderTarget;
};

struct ULandscapeComponent_SetLODBias final
{
public:
	int32                                             InLODBias;
};

struct ULandscapeComponent_SetForcedLOD final
{
public:
	int32                                             InForcedLOD;
};

struct ULandscapeComponent_GetMaterialInstanceDynamic final
{
public:
	int32                                             InIndex;
	class UMaterialInstanceDynamic*                   ReturnValue;
};

struct ULandscapeComponent_EditorGetPaintLayerWeightByNameAtLocation final
{
public:
	struct FVector                                    InLocation;
	class FName                                       InPaintLayerName;
	float                                             ReturnValue;
};

struct ULandscapeComponent_EditorGetPaintLayerWeightAtLocation final
{
public:
	struct FVector                                    InLocation;
	class ULandscapeLayerInfoObject*                  PaintLayer;
	float                                             ReturnValue;
};

struct ULandscapeHeightfieldCollisionComponent_GetRenderComponent final
{
public:
	class ULandscapeComponent*                        ReturnValue;
};

struct ULandscapeSplinesComponent_GetSplineMeshComponents final
{
public:
	TArray<class USplineMeshComponent*>               ReturnValue;
};

struct ALandscapeBlueprintBrushBase_RequestLandscapeUpdate final
{
public:
	bool                                              bInUserTriggered;
};

struct ALandscapeBlueprintBrushBase_RenderLayer final
{
public:
	struct FLandscapeBrushParameters                  InParameters;
	class UTextureRenderTarget2D*                     ReturnValue;
};

struct ALandscapeBlueprintBrushBase_Render final
{
public:
	bool                                              InIsHeightmap;
	uint8                                             Pad_0[0x0007];
	class UTextureRenderTarget2D*                     InCombinedResult;
	class FName                                       InWeightmapLayerName;
	class UTextureRenderTarget2D*                     ReturnValue;
};

struct ALandscapeBlueprintBrushBase_Initialize final
{
public:
	struct FTransform                                 InLandscapeTransform;
	struct FIntPoint                                  InLandscapeSize;
	struct FIntPoint                                  InLandscapeRenderTargetSize;
};

struct ALandscapeBlueprintBrushBase_GetBlueprintRenderDependencies final
{
public:
	TArray<class UObject*>                            OutStreamableAssets;
};

}
}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
