// generated by beardumper

#include "../SDK.hpp"

namespace SDK
{

void ULevelSequence::RemoveMetaDataByClass(class UClass* InClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequence", "RemoveMetaDataByClass");

	Params::ULevelSequence_RemoveMetaDataByClass Parms{};
	Parms.InClass = InClass;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

class UObject* ULevelSequence::FindOrAddMetaDataByClass(class UClass* InClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequence", "FindOrAddMetaDataByClass");

	Params::ULevelSequence_FindOrAddMetaDataByClass Parms{};
	Parms.InClass = InClass;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

class UObject* ULevelSequence::FindMetaDataByClass(class UClass* InClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequence", "FindMetaDataByClass");

	Params::ULevelSequence_FindMetaDataByClass Parms{};
	Parms.InClass = InClass;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

class UObject* ULevelSequence::CopyMetaData(class UObject* InMetaData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequence", "CopyMetaData");

	Params::ULevelSequence_CopyMetaData Parms{};
	Parms.InMetaData = InMetaData;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

void ULevelSequenceBurnInOptions::SetBurnIn(const struct FSoftClassPath& InBurnInClass)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceBurnInOptions", "SetBurnIn");

	Params::ULevelSequenceBurnInOptions_SetBurnIn Parms{};
	Parms.InBurnInClass = InBurnInClass;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void ALevelSequenceActor::ShowBurnin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceActor", "ShowBurnin");

	SDK::Rt::ProcessEvent(this, Func, nullptr);
}

void ALevelSequenceActor::SetSequence(class ULevelSequence* InSequence)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceActor", "SetSequence");

	Params::ALevelSequenceActor_SetSequence Parms{};
	Parms.InSequence = InSequence;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void ALevelSequenceActor::SetReplicatePlayback(bool ReplicatePlayback)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceActor", "SetReplicatePlayback");

	Params::ALevelSequenceActor_SetReplicatePlayback Parms{};
	Parms.ReplicatePlayback = ReplicatePlayback;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void ALevelSequenceActor::SetBindingByTag(const class FName& BindingTag, TArray<class AActor*>* Actors, bool bAllowBindingsFromAsset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceActor", "SetBindingByTag");

	Params::ALevelSequenceActor_SetBindingByTag Parms{};
	Parms.BindingTag = BindingTag;
	Parms.bAllowBindingsFromAsset = bAllowBindingsFromAsset;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (Actors != nullptr)
		*Actors = Parms.Actors;
}

void ALevelSequenceActor::SetBinding(const struct FMovieSceneObjectBindingID& Binding, TArray<class AActor*>* Actors, bool bAllowBindingsFromAsset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceActor", "SetBinding");

	Params::ALevelSequenceActor_SetBinding Parms{};
	Parms.Binding = Binding;
	Parms.bAllowBindingsFromAsset = bAllowBindingsFromAsset;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (Actors != nullptr)
		*Actors = Parms.Actors;
}

void ALevelSequenceActor::ResetBindings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceActor", "ResetBindings");

	SDK::Rt::ProcessEvent(this, Func, nullptr);
}

void ALevelSequenceActor::ResetBinding(const struct FMovieSceneObjectBindingID& Binding)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceActor", "ResetBinding");

	Params::ALevelSequenceActor_ResetBinding Parms{};
	Parms.Binding = Binding;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void ALevelSequenceActor::RemoveBindingByTag(const class FName& Tag, class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceActor", "RemoveBindingByTag");

	Params::ALevelSequenceActor_RemoveBindingByTag Parms{};
	Parms.Tag = Tag;
	Parms.Actor = Actor;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void ALevelSequenceActor::RemoveBinding(const struct FMovieSceneObjectBindingID& Binding, class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceActor", "RemoveBinding");

	Params::ALevelSequenceActor_RemoveBinding Parms{};
	Parms.Binding = Binding;
	Parms.Actor = Actor;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void ALevelSequenceActor::HideBurnin()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceActor", "HideBurnin");

	SDK::Rt::ProcessEvent(this, Func, nullptr);
}

class ULevelSequencePlayer* ALevelSequenceActor::GetSequencePlayer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceActor", "GetSequencePlayer");

	Params::ALevelSequenceActor_GetSequencePlayer Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

class ULevelSequence* ALevelSequenceActor::GetSequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceActor", "GetSequence");

	Params::ALevelSequenceActor_GetSequence Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

TArray<struct FMovieSceneObjectBindingID> ALevelSequenceActor::FindNamedBindings(const class FName& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceActor", "FindNamedBindings");

	Params::ALevelSequenceActor_FindNamedBindings Parms{};
	Parms.Tag = Tag;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

struct FMovieSceneObjectBindingID ALevelSequenceActor::FindNamedBinding(const class FName& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceActor", "FindNamedBinding");

	Params::ALevelSequenceActor_FindNamedBinding Parms{};
	Parms.Tag = Tag;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

void ALevelSequenceActor::AddBindingByTag(const class FName& BindingTag, class AActor* Actor, bool bAllowBindingsFromAsset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceActor", "AddBindingByTag");

	Params::ALevelSequenceActor_AddBindingByTag Parms{};
	Parms.BindingTag = BindingTag;
	Parms.Actor = Actor;
	Parms.bAllowBindingsFromAsset = bAllowBindingsFromAsset;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void ALevelSequenceActor::AddBinding(const struct FMovieSceneObjectBindingID& Binding, class AActor* Actor, bool bAllowBindingsFromAsset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceActor", "AddBinding");

	Params::ALevelSequenceActor_AddBinding Parms{};
	Parms.Binding = Binding;
	Parms.Actor = Actor;
	Parms.bAllowBindingsFromAsset = bAllowBindingsFromAsset;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void ULevelSequenceBurnIn::SetSettings(class UObject* InSettings)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceBurnIn", "SetSettings");

	Params::ULevelSequenceBurnIn_SetSettings Parms{};
	Parms.InSettings = InSettings;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

class UClass* ULevelSequenceBurnIn::GetSettingsClass()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceBurnIn", "GetSettingsClass");

	Params::ULevelSequenceBurnIn_GetSettingsClass Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

void ULevelSequenceDirector::OnCreated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceDirector", "OnCreated");

	SDK::Rt::ProcessEvent(this, Func, nullptr);
}

class UMovieSceneSequence* ULevelSequenceDirector::GetSequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceDirector", "GetSequence");

	Params::ULevelSequenceDirector_GetSequence Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

struct FQualifiedFrameTime ULevelSequenceDirector::GetRootSequenceTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceDirector", "GetRootSequenceTime");

	Params::ULevelSequenceDirector_GetRootSequenceTime Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

struct FQualifiedFrameTime ULevelSequenceDirector::GetMasterSequenceTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceDirector", "GetMasterSequenceTime");

	Params::ULevelSequenceDirector_GetMasterSequenceTime Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

struct FQualifiedFrameTime ULevelSequenceDirector::GetCurrentTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceDirector", "GetCurrentTime");

	Params::ULevelSequenceDirector_GetCurrentTime Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

TArray<class UObject*> ULevelSequenceDirector::GetBoundObjects(const struct FMovieSceneObjectBindingID& ObjectBinding)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceDirector", "GetBoundObjects");

	Params::ULevelSequenceDirector_GetBoundObjects Parms{};
	Parms.ObjectBinding = ObjectBinding;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

class UObject* ULevelSequenceDirector::GetBoundObject(const struct FMovieSceneObjectBindingID& ObjectBinding)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceDirector", "GetBoundObject");

	Params::ULevelSequenceDirector_GetBoundObject Parms{};
	Parms.ObjectBinding = ObjectBinding;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

TArray<class AActor*> ULevelSequenceDirector::GetBoundActors(const struct FMovieSceneObjectBindingID& ObjectBinding)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceDirector", "GetBoundActors");

	Params::ULevelSequenceDirector_GetBoundActors Parms{};
	Parms.ObjectBinding = ObjectBinding;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

class AActor* ULevelSequenceDirector::GetBoundActor(const struct FMovieSceneObjectBindingID& ObjectBinding)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceDirector", "GetBoundActor");

	Params::ULevelSequenceDirector_GetBoundActor Parms{};
	Parms.ObjectBinding = ObjectBinding;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

class UCameraComponent* ULevelSequencePlayer::GetActiveCameraComponent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequencePlayer", "GetActiveCameraComponent");

	Params::ULevelSequencePlayer_GetActiveCameraComponent Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

class ULevelSequencePlayer* ULevelSequencePlayer::CreateLevelSequencePlayer(class UObject* WorldContextObject, class ULevelSequence* LevelSequence, const struct FMovieSceneSequencePlaybackSettings& Settings, class ALevelSequenceActor** OutActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequencePlayer", "CreateLevelSequencePlayer");

	Params::ULevelSequencePlayer_CreateLevelSequencePlayer Parms{};
	Parms.WorldContextObject = WorldContextObject;
	Parms.LevelSequence = LevelSequence;
	Parms.Settings = Settings;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (OutActor != nullptr)
		*OutActor = Parms.OutActor;

	return Parms.ReturnValue;
}

void ALevelSequenceMediaController::SynchronizeToServer(float DesyncThresholdSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceMediaController", "SynchronizeToServer");

	Params::ALevelSequenceMediaController_SynchronizeToServer Parms{};
	Parms.DesyncThresholdSeconds = DesyncThresholdSeconds;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

}

void ALevelSequenceMediaController::Play()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceMediaController", "Play");

	SDK::Rt::ProcessEvent(this, Func, nullptr);
}

void ALevelSequenceMediaController::OnRep_ServerStartTimeSeconds()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceMediaController", "OnRep_ServerStartTimeSeconds");

	SDK::Rt::ProcessEvent(this, Func, nullptr);
}

class ALevelSequenceActor* ALevelSequenceMediaController::GetSequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceMediaController", "GetSequence");

	Params::ALevelSequenceMediaController_GetSequence Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

class UMediaComponent* ALevelSequenceMediaController::GetMediaComponent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("LevelSequenceMediaController", "GetMediaComponent");

	Params::ALevelSequenceMediaController_GetMediaComponent Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

}
