// generated by beardumper

#include "../SDK.hpp"

namespace SDK
{

enum class EESetParamResult UMetasoundParameterPack::SetTrigger(const class FName& ParameterName, bool OnlyIfExists)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("MetasoundParameterPack", "SetTrigger");

	Params::UMetasoundParameterPack_SetTrigger Parms{};
	Parms.ParameterName = ParameterName;
	Parms.OnlyIfExists = OnlyIfExists;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

enum class EESetParamResult UMetasoundParameterPack::SetString(const class FName& ParameterName, const class FString& InValue, bool OnlyIfExists)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("MetasoundParameterPack", "SetString");

	Params::UMetasoundParameterPack_SetString Parms{};
	Parms.ParameterName = ParameterName;
	Parms.InValue = InValue;
	Parms.OnlyIfExists = OnlyIfExists;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

enum class EESetParamResult UMetasoundParameterPack::SetInt(const class FName& ParameterName, int32 InValue, bool OnlyIfExists)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("MetasoundParameterPack", "SetInt");

	Params::UMetasoundParameterPack_SetInt Parms{};
	Parms.ParameterName = ParameterName;
	Parms.InValue = InValue;
	Parms.OnlyIfExists = OnlyIfExists;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

enum class EESetParamResult UMetasoundParameterPack::SetFloat(const class FName& ParameterName, float InValue, bool OnlyIfExists)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("MetasoundParameterPack", "SetFloat");

	Params::UMetasoundParameterPack_SetFloat Parms{};
	Parms.ParameterName = ParameterName;
	Parms.InValue = InValue;
	Parms.OnlyIfExists = OnlyIfExists;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

enum class EESetParamResult UMetasoundParameterPack::SetBool(const class FName& ParameterName, bool InValue, bool OnlyIfExists)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("MetasoundParameterPack", "SetBool");

	Params::UMetasoundParameterPack_SetBool Parms{};
	Parms.ParameterName = ParameterName;
	Parms.InValue = InValue;
	Parms.OnlyIfExists = OnlyIfExists;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

class UMetasoundParameterPack* UMetasoundParameterPack::MakeMetasoundParameterPack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("MetasoundParameterPack", "MakeMetasoundParameterPack");

	Params::UMetasoundParameterPack_MakeMetasoundParameterPack Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

bool UMetasoundParameterPack::HasTrigger(const class FName& ParameterName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("MetasoundParameterPack", "HasTrigger");

	Params::UMetasoundParameterPack_HasTrigger Parms{};
	Parms.ParameterName = ParameterName;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

bool UMetasoundParameterPack::HasString(const class FName& ParameterName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("MetasoundParameterPack", "HasString");

	Params::UMetasoundParameterPack_HasString Parms{};
	Parms.ParameterName = ParameterName;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

bool UMetasoundParameterPack::HasInt(const class FName& ParameterName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("MetasoundParameterPack", "HasInt");

	Params::UMetasoundParameterPack_HasInt Parms{};
	Parms.ParameterName = ParameterName;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

bool UMetasoundParameterPack::HasFloat(const class FName& ParameterName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("MetasoundParameterPack", "HasFloat");

	Params::UMetasoundParameterPack_HasFloat Parms{};
	Parms.ParameterName = ParameterName;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

bool UMetasoundParameterPack::HasBool(const class FName& ParameterName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("MetasoundParameterPack", "HasBool");

	Params::UMetasoundParameterPack_HasBool Parms{};
	Parms.ParameterName = ParameterName;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

bool UMetasoundParameterPack::GetTrigger(const class FName& ParameterName, enum class EESetParamResult* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("MetasoundParameterPack", "GetTrigger");

	Params::UMetasoundParameterPack_GetTrigger Parms{};
	Parms.ParameterName = ParameterName;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;

	return Parms.ReturnValue;
}

class FString UMetasoundParameterPack::GetString(const class FName& ParameterName, enum class EESetParamResult* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("MetasoundParameterPack", "GetString");

	Params::UMetasoundParameterPack_GetString Parms{};
	Parms.ParameterName = ParameterName;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;

	return Parms.ReturnValue;
}

int32 UMetasoundParameterPack::GetInt(const class FName& ParameterName, enum class EESetParamResult* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("MetasoundParameterPack", "GetInt");

	Params::UMetasoundParameterPack_GetInt Parms{};
	Parms.ParameterName = ParameterName;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;

	return Parms.ReturnValue;
}

float UMetasoundParameterPack::GetFloat(const class FName& ParameterName, enum class EESetParamResult* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("MetasoundParameterPack", "GetFloat");

	Params::UMetasoundParameterPack_GetFloat Parms{};
	Parms.ParameterName = ParameterName;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;

	return Parms.ReturnValue;
}

bool UMetasoundParameterPack::GetBool(const class FName& ParameterName, enum class EESetParamResult* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("MetasoundParameterPack", "GetBool");

	Params::UMetasoundParameterPack_GetBool Parms{};
	Parms.ParameterName = ParameterName;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;

	return Parms.ReturnValue;
}

}
