#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class AModularAIController : public AAIController
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ModularAIController");
		return Clss;
	}
};

class AModularCharacter : public ACharacter
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ModularCharacter");
		return Clss;
	}
};

class AModularGameModeBase : public AGameModeBase
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ModularGameModeBase");
		return Clss;
	}
};

class AModularGameMode : public AGameMode
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ModularGameMode");
		return Clss;
	}
};

class AModularGameStateBase : public AGameStateBase
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ModularGameStateBase");
		return Clss;
	}
};

class AModularGameState : public AGameState
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ModularGameState");
		return Clss;
	}
};

class AModularHUD : public AHUD
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ModularHUD");
		return Clss;
	}
};

class AModularPawn : public APawn
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ModularPawn");
		return Clss;
	}
};

class AModularPlayerController : public APlayerController
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ModularPlayerController");
		return Clss;
	}
};

class AModularPlayerState : public APlayerState
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ModularPlayerState");
		return Clss;
	}
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
