#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

namespace Params
{

struct UTurnBasedMatchInterface_OnMatchReceivedTurn final
{
public:
	class FString                                     Match;
	bool                                              bDidBecomeActive;
};

struct UTurnBasedMatchInterface_OnMatchEnded final
{
public:
	class FString                                     Match;
};

}
}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
