#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

namespace Params
{

struct URGIOPRiotGamesApiEditorSettings_GetPatchlineOptions final
{
public:
	TArray<class FString>                             ReturnValue;
};

}
}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
