#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

struct FOverlayItem
{
public:
	struct FTimespan                                  StartTime;
	struct FTimespan                                  EndTime;
	class FString                                     Text;
	struct FVector2D                                  Position;
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
