#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

enum class ESpriteCollisionMode : uint8
{
	None                                      = 0,
	Use2DPhysics                              = 1,
	Use3DPhysics                              = 2,
	ESpriteCollisionMode_MAX                  = 3,
};

enum class ESpriteShapeType : uint8
{
	Box                                       = 0,
	Circle                                    = 1,
	Polygon                                   = 2,
	ESpriteShapeType_MAX                      = 3,
};

enum class ESpritePolygonMode : uint8
{
	SourceBoundingBox                         = 0,
	TightBoundingBox                          = 1,
	ShrinkWrapped                             = 2,
	FullyCustom                               = 3,
	Diced                                     = 4,
	ESpritePolygonMode_MAX                    = 5,
};

enum class ESpritePivotMode : uint8
{
	Top_Left                                  = 0,
	Top_Center                                = 1,
	Top_Right                                 = 2,
	Center_Left                               = 3,
	Center_Center                             = 4,
	Center_Right                              = 5,
	Bottom_Left                               = 6,
	Bottom_Center                             = 7,
	Bottom_Right                              = 8,
	Custom                                    = 9,
	ESpritePivotMode_MAX                      = 10,
};

enum class EFlipbookCollisionMode : uint8
{
	NoCollision                               = 0,
	FirstFrameCollision                       = 1,
	EachFrameCollision                        = 2,
	EFlipbookCollisionMode_MAX                = 3,
};

enum class EPaperSpriteAtlasPadding : uint8
{
	DilateBorder                              = 0,
	PadWithZero                               = 1,
	EPaperSpriteAtlasPadding_MAX              = 2,
};

enum class ETileMapProjectionMode : uint8
{
	Orthogonal                                = 0,
	IsometricDiamond                          = 1,
	IsometricStaggered                        = 2,
	HexagonalStaggered                        = 3,
	ETileMapProjectionMode_MAX                = 4,
};

struct FIntMargin
{
public:
	int32                                             Left;
	int32                                             Top;
	int32                                             Right;
	int32                                             Bottom;
};

struct FSpriteDrawCallRecord
{
public:
	struct FVector                                    Destination;
	class UTexture*                                   BaseTexture;
	uint8                                             Pad_0[0x0030];
	struct FColor                                     Color;
	uint8                                             Pad_1[0x00EC];
};

struct FSpriteGeometryShape
{
public:
	enum class EESpriteShapeType                      ShapeType;
	uint8                                             Pad_0[0x0007];
	TArray<struct FVector2D>                          Vertices;
	struct FVector2D                                  BoxSize;
	struct FVector2D                                  BoxPosition;
	float                                             Rotation;
	bool                                              bNegativeWinding;
	uint8                                             Pad_1[0x0003];
};

struct FSpriteGeometryCollection
{
public:
	TArray<struct FSpriteGeometryShape>               Shapes;
	enum class EESpritePolygonMode                    GeometryType;
	uint8                                             Pad_0[0x0003];
	int32                                             PixelsPerSubdivisionX;
	int32                                             PixelsPerSubdivisionY;
	bool                                              bAvoidVertexMerging;
	uint8                                             Pad_1[0x0003];
	float                                             AlphaThreshold;
	float                                             DetailAmount;
	float                                             SimplifyEpsilon;
	uint8                                             Pad_2[0x0004];
};

struct FSpriteAssetInitParameters
{
public:
	uint8                                             Pad_0[0x0040];
};

struct FPaperFlipbookKeyFrame
{
public:
	class UPaperSprite*                               Sprite;
	int32                                             FrameRun;
	uint8                                             Pad_0[0x0004];
};

struct FSpriteInstanceData
{
public:
	struct FMatrix                                    Transform;
	class UPaperSprite*                               SourceSprite;
	struct FColor                                     VertexColor;
	int32                                             MaterialIndex;
};

struct FPaperSpriteSocket
{
public:
	struct FTransform                                 LocalTransform;
	class FName                                       SocketName;
	uint8                                             Pad_0[0x0004];
};

struct FPaperSpriteAtlasSlot
{
public:
	TSoftObjectPtr<class UPaperSprite>                SpriteRef;
	int32                                             AtlasIndex;
	int32                                             X;
	int32                                             Y;
	int32                                             Width;
	int32                                             Height;
	uint8                                             Pad_0[0x0004];
};

struct FPaperTileInfo
{
public:
	class UPaperTileSet*                              TileSet;
	int32                                             PackedTileIndex;
	uint8                                             Pad_0[0x0004];
};

struct FPaperTileMetadata
{
public:
	class FName                                       UserDataName;
	uint8                                             Pad_0[0x0004];
	struct FSpriteGeometryCollection                  CollisionData;
	uint8                                             TerrainMembership[0x04];
	uint8                                             Pad_1[0x0004];
};

struct FPaperTileSetTerrain
{
public:
	class FString                                     TerrainName;
	int32                                             CenterTileIndex;
	uint8                                             Pad_0[0x0004];
};

struct FPaperTerrainMaterialRule
{
public:
	class UPaperSprite*                               StartCap;
	TArray<class UPaperSprite*>                       Body;
	class UPaperSprite*                               EndCap;
	float                                             MinimumAngle;
	float                                             MaximumAngle;
	bool                                              bEnableCollision;
	uint8                                             Pad_0[0x0003];
	float                                             CollisionOffset;
	int32                                             DrawOrder;
	uint8                                             Pad_1[0x0004];
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
