#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class APaperCharacter : public ACharacter
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperCharacter");
		return Clss;
	}
};

class UPaperFlipbook : public UObject
{
public:
	float                                             FramesPerSecond;
	uint8                                             Pad_0[0x0004];
	TArray<struct FPaperFlipbookKeyFrame>             KeyFrames;
	class UMaterialInterface*                         DefaultMaterial;
	enum class EEFlipbookCollisionMode                CollisionSource;
	uint8                                             Pad_1[0x0007];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperFlipbook");
		return Clss;
	}

	bool IsValidKeyFrameIndex(int32 Index);
	float GetTotalDuration();
	class UPaperSprite* GetSpriteAtTime(float Time, bool bClampToEnds);
	class UPaperSprite* GetSpriteAtFrame(int32 FrameIndex);
	int32 GetNumKeyFrames();
	int32 GetNumFrames();
	int32 GetKeyFrameIndexAtTime(float Time, bool bClampToEnds);
};

class APaperFlipbookActor : public AActor
{
public:
	class UPaperFlipbookComponent*                    RenderComponent;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperFlipbookActor");
		return Clss;
	}
};

class UPaperFlipbookComponent : public UMeshComponent
{
public:
	class UPaperFlipbook*                             SourceFlipbook;
	class UMaterialInterface*                         Material;
	float                                             PlayRate;
	uint8                                             bLooping : 1;
	uint8                                             bReversePlayback : 1;
	uint8                                             bPlaying : 1;
	uint8                                             BitPad_0 : 5;
	uint8                                             Pad_0[0x0003];
	float                                             AccumulatedTime;
	int32                                             CachedFrameIndex;
	struct FLinearColor                               SpriteColor;
	class UBodySetup*                                 CachedBodySetup;
	struct FMulticastInlineDelegateProperty_          OnFinishedPlaying;
	uint8                                             Pad_1[0x0008];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperFlipbookComponent");
		return Clss;
	}

	void Stop();
	void SetSpriteColor(const struct FLinearColor& NewColor);
	void SetPlayRate(float NewRate);
	void SetPlaybackPositionInFrames(int32 NewFramePosition, bool bFireEvents);
	void SetPlaybackPosition(float NewPosition, bool bFireEvents);
	void SetNewTime(float NewTime);
	void SetLooping(bool bNewLooping);
	bool SetFlipbook(class UPaperFlipbook* NewFlipbook);
	void ReverseFromEnd();
	void Reverse();
	void PlayFromStart();
	void Play();
	void OnRep_SourceFlipbook(class UPaperFlipbook* OldFlipbook);
	bool IsReversing();
	bool IsPlaying();
	bool IsLooping();
	struct FLinearColor GetSpriteColor();
	float GetPlayRate();
	int32 GetPlaybackPositionInFrames();
	float GetPlaybackPosition();
	int32 GetFlipbookLengthInFrames();
	float GetFlipbookLength();
	float GetFlipbookFramerate();
	class UPaperFlipbook* GetFlipbook();
};

class APaperGroupedSpriteActor : public AActor
{
public:
	class UPaperGroupedSpriteComponent*               RenderComponent;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperGroupedSpriteActor");
		return Clss;
	}
};

class UPaperGroupedSpriteComponent : public UMeshComponent
{
public:
	TArray<class UMaterialInterface*>                 InstanceMaterials;
	TArray<struct FSpriteInstanceData>                PerInstanceSpriteData;
	uint8                                             Pad_0[0x0010];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperGroupedSpriteComponent");
		return Clss;
	}

	bool UpdateInstanceTransform(int32 InstanceIndex, struct FTransform* NewInstanceTransform, bool bWorldSpace, bool bMarkRenderStateDirty, bool bTeleport);
	bool UpdateInstanceColor(int32 InstanceIndex, const struct FLinearColor& NewInstanceColor, bool bMarkRenderStateDirty);
	void SortInstancesAlongAxis(const struct FVector& WorldSpaceSortAxis);
	bool RemoveInstance(int32 InstanceIndex);
	bool GetInstanceTransform(int32 InstanceIndex, struct FTransform* OutInstanceTransform, bool bWorldSpace);
	int32 GetInstanceCount();
	void ClearInstances();
	int32 AddInstance(struct FTransform* Transform, class UPaperSprite* Sprite, bool bWorldSpace, const struct FLinearColor& Color);
};

class UPaperRuntimeSettings : public UObject
{
public:
	bool                                              bEnableSpriteAtlasGroups;
	bool                                              bEnableTerrainSplineEditing;
	bool                                              bResizeSpriteDataToMatchTextures;
	uint8                                             Pad_0[0x0005];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperRuntimeSettings");
		return Clss;
	}
};

class UPaperSprite : public UObject
{
public:
	uint8                                             Pad_0[0x0010];
	TArray<class UTexture*>                           AdditionalSourceTextures;
	struct FVector2D                                  BakedSourceUV;
	struct FVector2D                                  BakedSourceDimension;
	class UTexture2D*                                 BakedSourceTexture;
	class UMaterialInterface*                         DefaultMaterial;
	class UMaterialInterface*                         AlternateMaterial;
	TArray<struct FPaperSpriteSocket>                 Sockets;
	enum class EESpriteCollisionMode                  SpriteCollisionDomain;
	uint8                                             Pad_1[0x0003];
	float                                             PixelsPerUnrealUnit;
	class UBodySetup*                                 BodySetup;
	int32                                             AlternateMaterialSplitIndex;
	uint8                                             Pad_2[0x0004];
	TArray<struct FVector4>                           BakedRenderData;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperSprite");
		return Clss;
	}
};

class APaperSpriteActor : public AActor
{
public:
	class UPaperSpriteComponent*                      RenderComponent;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperSpriteActor");
		return Clss;
	}
};

class UPaperSpriteAtlas : public UObject
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperSpriteAtlas");
		return Clss;
	}
};

class UPaperSpriteBlueprintLibrary : public UBlueprintFunctionLibrary
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperSpriteBlueprintLibrary");
		return Clss;
	}

	static struct FSlateBrush MakeBrushFromSprite(class UPaperSprite* Sprite, int32 Width, int32 Height);
};

class UPaperSpriteComponent : public UMeshComponent
{
public:
	class UPaperSprite*                               SourceSprite;
	class UMaterialInterface*                         MaterialOverride;
	struct FLinearColor                               SpriteColor;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperSpriteComponent");
		return Clss;
	}

	void SetSpriteColor(const struct FLinearColor& NewColor);
	bool SetSprite(class UPaperSprite* NewSprite);
	class UPaperSprite* GetSprite();
};

class UPaperTileLayer : public UObject
{
public:
	class FText                                       LayerName;
	int32                                             LayerWidth;
	int32                                             LayerHeight;
	uint8                                             bHiddenInGame : 1;
	uint8                                             bLayerCollides : 1;
	uint8                                             bOverrideCollisionThickness : 1;
	uint8                                             bOverrideCollisionOffset : 1;
	uint8                                             BitPad_0 : 4;
	uint8                                             Pad_0[0x0003];
	float                                             CollisionThicknessOverride;
	float                                             CollisionOffsetOverride;
	struct FLinearColor                               LayerColor;
	int32                                             AllocatedWidth;
	int32                                             AllocatedHeight;
	uint8                                             Pad_1[0x0004];
	TArray<struct FPaperTileInfo>                     AllocatedCells;
	class UPaperTileSet*                              TileSet;
	TArray<int32>                                     AllocatedGrid;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperTileLayer");
		return Clss;
	}
};

class UPaperTileMap : public UObject
{
public:
	int32                                             MapWidth;
	int32                                             MapHeight;
	int32                                             TileWidth;
	int32                                             TileHeight;
	float                                             PixelsPerUnrealUnit;
	float                                             SeparationPerTileX;
	float                                             SeparationPerTileY;
	float                                             SeparationPerLayer;
	TSoftObjectPtr<class UPaperTileSet>               SelectedTileSet;
	class UMaterialInterface*                         Material;
	TArray<class UPaperTileLayer*>                    TileLayers;
	float                                             CollisionThickness;
	enum class EESpriteCollisionMode                  SpriteCollisionDomain;
	enum class EETileMapProjectionMode                ProjectionMode;
	uint8                                             Pad_0[0x0002];
	int32                                             HexSideLength;
	uint8                                             Pad_1[0x0004];
	class UBodySetup*                                 BodySetup;
	int32                                             LayerNameIndex;
	uint8                                             Pad_2[0x0004];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperTileMap");
		return Clss;
	}
};

class APaperTileMapActor : public AActor
{
public:
	class UPaperTileMapComponent*                     RenderComponent;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperTileMapActor");
		return Clss;
	}
};

class UPaperTileMapComponent : public UMeshComponent
{
public:
	int32                                             MapWidth;
	int32                                             MapHeight;
	int32                                             TileWidth;
	int32                                             TileHeight;
	class UPaperTileSet*                              DefaultLayerTileSet;
	class UMaterialInterface*                         Material;
	TArray<class UPaperTileLayer*>                    TileLayers;
	struct FLinearColor                               TileMapColor;
	int32                                             UseSingleLayerIndex;
	bool                                              bUseSingleLayer;
	uint8                                             Pad_0[0x0003];
	class UPaperTileMap*                              TileMap;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperTileMapComponent");
		return Clss;
	}

	void SetTileMapColor(const struct FLinearColor& NewColor);
	bool SetTileMap(class UPaperTileMap* NewTileMap);
	void SetTile(int32 X, int32 Y, int32 Layer, const struct FPaperTileInfo& NewValue);
	void SetLayerColor(const struct FLinearColor& NewColor, int32 Layer);
	void SetLayerCollision(int32 Layer, bool bHasCollision, bool bOverrideThickness, float CustomThickness, bool bOverrideOffset, float CustomOffset, bool bRebuildCollision);
	void SetDefaultCollisionThickness(float Thickness, bool bRebuildCollision);
	void ResizeMap(int32 NewWidthInTiles, int32 NewHeightInTiles);
	void RebuildCollision();
	bool OwnsTileMap();
	void MakeTileMapEditable();
	void GetTilePolygon(int32 TileX, int32 TileY, TArray<struct FVector>* Points, int32 LayerIndex, bool bWorldSpace);
	struct FLinearColor GetTileMapColor();
	struct FVector GetTileCornerPosition(int32 TileX, int32 TileY, int32 LayerIndex, bool bWorldSpace);
	struct FVector GetTileCenterPosition(int32 TileX, int32 TileY, int32 LayerIndex, bool bWorldSpace);
	struct FPaperTileInfo GetTile(int32 X, int32 Y, int32 Layer);
	void GetMapSize(int32* MapWidth, int32* MapHeight, int32* NumLayers);
	struct FLinearColor GetLayerColor(int32 Layer);
	void CreateNewTileMap(int32 MapWidth, int32 MapHeight, int32 TileWidth, int32 TileHeight, float PixelsPerUnrealUnit, bool bCreateLayer);
	class UPaperTileLayer* AddNewLayer();
};

class UPaperTileSet : public UObject
{
public:
	struct FIntPoint                                  TileSize;
	class UTexture2D*                                 TileSheet;
	TArray<class UTexture*>                           AdditionalSourceTextures;
	struct FIntMargin                                 BorderMargin;
	struct FIntPoint                                  PerTileSpacing;
	struct FIntPoint                                  DrawingOffset;
	int32                                             WidthInTiles;
	int32                                             HeightInTiles;
	int32                                             AllocatedWidth;
	int32                                             AllocatedHeight;
	TArray<struct FPaperTileMetadata>                 PerTileData;
	TArray<struct FPaperTileSetTerrain>               Terrains;
	int32                                             TileWidth;
	int32                                             TileHeight;
	int32                                             Margin;
	int32                                             Spacing;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperTileSet");
		return Clss;
	}
};

class UMaterialExpressionSpriteTextureSampler : public UMaterialExpressionTextureSampleParameter2D
{
public:
	bool                                              bSampleAdditionalTextures;
	uint8                                             Pad_0[0x0003];
	int32                                             AdditionalSlotIndex;
	class FText                                       SlotDisplayName;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("MaterialExpressionSpriteTextureSampler");
		return Clss;
	}
};

class APaperTerrainActor : public AActor
{
public:
	class USceneComponent*                            DummyRoot;
	class UPaperTerrainSplineComponent*               SplineComponent;
	class UPaperTerrainComponent*                     RenderComponent;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperTerrainActor");
		return Clss;
	}
};

class UPaperTerrainComponent : public UPrimitiveComponent
{
public:
	bool                                              bClosedSpline;
	bool                                              bFilledSpline;
	uint8                                             Pad_0[0x0006];
	class UPaperTerrainSplineComponent*               AssociatedSpline;
	int32                                             RandomSeed;
	float                                             SegmentOverlapAmount;
	struct FLinearColor                               TerrainColor;
	int32                                             ReparamStepsPerSegment;
	enum class EESpriteCollisionMode                  SpriteCollisionDomain;
	uint8                                             Pad_1[0x0003];
	float                                             CollisionThickness;
	uint8                                             Pad_2[0x0004];
	class UBodySetup*                                 CachedBodySetup;
	uint8                                             Pad_3[0x0010];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperTerrainComponent");
		return Clss;
	}

	void SetTerrainColor(const struct FLinearColor& NewColor);
};

class UPaperTerrainMaterial : public UDataAsset
{
public:
	TArray<struct FPaperTerrainMaterialRule>          Rules;
	class UPaperSprite*                               InteriorFill;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperTerrainMaterial");
		return Clss;
	}
};

class UPaperTerrainSplineComponent : public USplineComponent
{
public:
	uint8                                             Pad_0[0x0010];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PaperTerrainSplineComponent");
		return Clss;
	}
};

class UTileMapBlueprintLibrary : public UBlueprintFunctionLibrary
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("TileMapBlueprintLibrary");
		return Clss;
	}

	static struct FPaperTileInfo MakeTile(int32 TileIndex, class UPaperTileSet* TileSet, bool bFlipH, bool bFlipV, bool bFlipD);
	static class FName GetTileUserData(const struct FPaperTileInfo& Tile);
	static struct FTransform GetTileTransform(const struct FPaperTileInfo& Tile);
	static void BreakTile(const struct FPaperTileInfo& Tile, int32* TileIndex, class UPaperTileSet** TileSet, bool* bFlipH, bool* bFlipV, bool* bFlipD);
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
