#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

namespace Params
{

struct UPlatformUIFRE_SetHotfixAvailability final
{
public:
	enum class EEPlatformUIHotFixAvailability         HotfixAvailability;
	bool                                              ReturnValue;
};

}
}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
