#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

enum class ELoadingIndicatorType : uint8
{
	INDETERMINATE_LOADER                      = 0,
	PROGRESS_BAR                              = 1,
	LoadingIndicatorType_MAX                  = 2,
};

enum class EPlatformUIHotFixAvailability : uint8
{
	Unknown                                   = 0,
	UpdateRequired                            = 1,
	Ready                                     = 2,
	EPlatformUIHotFixAvailability_MAX         = 3,
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
