#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class UPropertyPathTestObject : public UObject
{
public:
	bool                                              Bool;
	enum class EEPropertyPathTestEnum                 EnumOne;
	enum class EEPropertyPathTestEnum                 EnumTwo;
	enum class EEPropertyPathTestEnum                 EnumThree;
	enum class EEPropertyPathTestEnum                 EnumFour;
	uint8                                             Pad_0[0x0003];
	int32                                             Integer;
	uint8                                             Pad_1[0x0004];
	class FString                                     String;
	float                                             Float;
	uint8                                             Pad_2[0x0004];
	struct FPropertyPathTestStruct                    Struct;
	struct FPropertyPathTestStruct                    StructRef;
	struct FPropertyPathTestStruct                    StructConstRef;
	class UPropertyPathTestObject*                    InnerObject;
	uint8                                             Pad_3[0x0008];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PropertyPathTestObject");
		return Clss;
	}

	void SetStructRef(const struct FPropertyPathTestStruct& InStruct);
	void SetStructConstRef(const struct FPropertyPathTestStruct& InStruct);
	void SetStruct(const struct FPropertyPathTestStruct& InStruct);
	void SetFloat(float InFloat);
	struct FPropertyPathTestStruct GetStructRef();
	struct FPropertyPathTestStruct GetStructConstRef();
	struct FPropertyPathTestStruct GetStruct();
	float GetFloat();
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
