#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class UProvisionerGameDataEventReceiver : public UBaseGameDataEventReceiver
{
public:
	uint8                                             Pad_0[0x0010];
	class UGameDataExporter*                          GameDataExporter;
	uint8                                             Pad_1[0x0008];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("ProvisionerGameDataEventReceiver");
		return Clss;
	}
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
