#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

namespace Params
{

struct UReflexBlueprintLibrary_SetReflexMode final
{
public:
	enum class EEReflexMode                           Mode;
};

struct UReflexBlueprintLibrary_SetFlashIndicatorEnabled final
{
public:
	bool                                              bEnabled;
};

struct UReflexBlueprintLibrary_GetRenderLatencyInMs final
{
public:
	float                                             ReturnValue;
};

struct UReflexBlueprintLibrary_GetReflexMode final
{
public:
	enum class EEReflexMode                           ReturnValue;
};

struct UReflexBlueprintLibrary_GetReflexAvailable final
{
public:
	bool                                              ReturnValue;
};

struct UReflexBlueprintLibrary_GetGameToRenderLatencyInMs final
{
public:
	float                                             ReturnValue;
};

struct UReflexBlueprintLibrary_GetGameLatencyInMs final
{
public:
	float                                             ReturnValue;
};

struct UReflexBlueprintLibrary_GetFlashIndicatorEnabled final
{
public:
	bool                                              ReturnValue;
};

}
}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
