#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

namespace Params
{

struct URCVirtualPropertyBase_SetValueVector final
{
public:
	struct FVector                                    InVector;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_SetValueUint64 final
{
public:
	uint64                                            InUInt64;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_SetValueUInt32 final
{
public:
	uint32                                            InUInt32;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_SetValueUint16 final
{
public:
	uint16                                            InUInt16;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_SetValueText final
{
public:
	class FText                                       InTextValue;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_SetValueString final
{
public:
	class FString                                     InStringValue;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_SetValueRotator final
{
public:
	struct FRotator                                   InRotator;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_SetValueNumericInteger final
{
public:
	int64                                             InInt64Value;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_SetValueName final
{
public:
	class FName                                       InNameValue;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_SetValueInt8 final
{
public:
	int8                                              InInt8;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_SetValueInt64 final
{
public:
	int64                                             InInt64;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_SetValueInt32 final
{
public:
	int32                                             InInt32;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_SetValueInt16 final
{
public:
	int16                                             InInt16;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_SetValueFloat final
{
public:
	float                                             InFloat;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_SetValueDouble final
{
public:
	double                                            InDouble;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_SetValueColor final
{
public:
	struct FColor                                     InColor;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_SetValueByte final
{
public:
	uint8                                             InByte;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_SetValueBool final
{
public:
	bool                                              InBoolValue;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetValueVector final
{
public:
	struct FVector                                    OutVector;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetValueUint64 final
{
public:
	uint64                                            OuyUInt64;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetValueUInt32 final
{
public:
	uint32                                            OutUInt32;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetValueUint16 final
{
public:
	uint16                                            OutUInt16;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetValueText final
{
public:
	class FText                                       OutTextValue;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetValueString final
{
public:
	class FString                                     OutStringValue;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetValueRotator final
{
public:
	struct FRotator                                   OutRotator;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetValueObject final
{
public:
	class UObject*                                    ReturnValue;
};

struct URCVirtualPropertyBase_GetValueNumericInteger final
{
public:
	int64                                             OutInt64Value;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetValueName final
{
public:
	class FName                                       OutNameValue;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetValueInt8 final
{
public:
	int8                                              OutInt8;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetValueInt64 final
{
public:
	int64                                             OuyInt64;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetValueInt32 final
{
public:
	int32                                             OutInt32;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetValueInt16 final
{
public:
	int16                                             OutInt16;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetValueFloat final
{
public:
	float                                             OutFloat;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetValueDouble final
{
public:
	double                                            OutDouble;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetValueColor final
{
public:
	struct FColor                                     OutColor;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetValueByte final
{
public:
	uint8                                             OutByte;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetValueBool final
{
public:
	bool                                              OutBoolValue;
	bool                                              ReturnValue;
};

struct URCVirtualPropertyBase_GetPropertyName final
{
public:
	class FName                                       ReturnValue;
};

struct URCVirtualPropertyBase_GetDisplayValueAsString final
{
public:
	class FString                                     ReturnValue;
};

struct URemoteControlDeltaAPITestObject_SetInt32WithSetterValue final
{
public:
	int32                                             NewValue;
};

struct URemoteControlDeltaAPITestObject_GetInt32WithSetterValue final
{
public:
	int32                                             ReturnValue;
};

struct URemoteControlFunctionLibrary_ExposeProperty final
{
public:
	class URemoteControlPreset*                       Preset;
	class UObject*                                    SourceObject;
	class FString                                     Property;
	struct FRemoteControlOptionalExposeArgs           Args;
	bool                                              ReturnValue;
};

struct URemoteControlFunctionLibrary_ExposeFunction final
{
public:
	class URemoteControlPreset*                       Preset;
	class UObject*                                    SourceObject;
	class FString                                     Function;
	struct FRemoteControlOptionalExposeArgs           Args;
	bool                                              ReturnValue;
};

struct URemoteControlFunctionLibrary_ExposeActor final
{
public:
	class URemoteControlPreset*                       Preset;
	class AActor*                                     Actor;
	struct FRemoteControlOptionalExposeArgs           Args;
	bool                                              ReturnValue;
};

struct URemoteControlFunctionLibrary_ApplyColorWheelDelta final
{
public:
	class UObject*                                    TargetObject;
	class FString                                     PropertyName;
	struct FColorWheelColor                           DeltaValue;
	struct FColorWheelColor                           ReferenceColor;
	bool                                              bIsInteractive;
	bool                                              ReturnValue;
};

struct URemoteControlFunctionLibrary_ApplyColorGradingWheelDelta final
{
public:
	class UObject*                                    TargetObject;
	class FString                                     PropertyName;
	struct FColorGradingWheelColor                    DeltaValue;
	struct FColorGradingWheelColor                    ReferenceColor;
	bool                                              bIsInteractive;
	uint8                                             Pad_0[0x0003];
	float                                             MinValue;
	float                                             MaxValue;
	bool                                              ReturnValue;
};

struct URemoteControlInterceptionTestObject_TestFunction final
{
public:
	struct FRemoteControlInterceptionFunctionParamStruct InStruct;
	int32                                             InTestFactor;
	struct FRemoteControlInterceptionFunctionParamStruct ReturnValue;
};

}
}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
