#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class URCPropertyContainerBase : public UObject
{
public:
	uint8                                             Pad_0[0x0028];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RCPropertyContainerBase");
		return Clss;
	}
};

class URCPropertyContainerRegistry : public UEngineSubsystem
{
public:
	TMap<struct FRCPropertyContainerKey, class UClass*> CachedContainerClasses;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RCPropertyContainerRegistry");
		return Clss;
	}
};

class UPropertyContainerTestObject : public UObject
{
public:
	bool                                              bSomeBool;
	uint8                                             Pad_0[0x0003];
	uint32                                            SomeUInt32;
	float                                             SomeFloat;
	uint8                                             Pad_1[0x0004];
	struct FVector                                    SomeVector;
	struct FRotator                                   SomeRotator;
	int32                                             SomeClampedInt;
	int32                                             SomeClampedInt2;
	int32                                             SomeUIClampedInt;
	float                                             SomeClampedFloat;
	float                                             SomeUIClampedFloat;
	float                                             SomeClampedFloat2;
	class FString                                     SomeString;
	class FText                                       SomeText;
	TArray<float>                                     SomeFloatArray;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("PropertyContainerTestObject");
		return Clss;
	}
};

class URemoteControlSettings : public UDeveloperSettings
{
public:
	bool                                              bProtocolsGenerateTransactions;
	uint8                                             Pad_0[0x0007];
	class FString                                     RemoteControlWebInterfaceBindAddress;
	uint32                                            RemoteControlWebInterfacePort;
	bool                                              bForceWebAppBuildAtStartup;
	bool                                              bWebAppLogRequestDuration;
	bool                                              bAutoStartWebServer;
	bool                                              bAutoStartWebSocketServer;
	uint32                                            RemoteControlHttpServerPort;
	uint8                                             Pad_1[0x0004];
	class FString                                     RemoteControlWebsocketServerBindAddress;
	uint32                                            RemoteControlWebSocketServerPort;
	bool                                              bDisplayInEditorOnlyWarnings;
	uint8                                             Pad_2[0x0003];
	float                                             TreeBindingSplitRatio;
	bool                                              bUseRebindingContext;
	bool                                              bIgnoreProtectedCheck;
	bool                                              bIgnoreGetterSetterCheck;
	bool                                              bIgnoreWarnings;
	bool                                              bRestrictServerAccess;
	bool                                              bEnableRemotePythonExecution;
	uint8                                             Pad_3[0x0006];
	TSet<uint8[0x0] /**/>                             AllowlistedClients;
	class FString                                     AllowedOrigin;
	bool                                              bEnforcePassphraseForRemoteClients;
	uint8                                             Pad_4[0x0007];
	TArray<struct FRCPassphrase>                      Passphrases;
	bool                                              bShowPassphraseDisabledWarning;
	bool                                              bSecuritySettingsReviewed;
	uint8                                             Pad_5[0x0006];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RemoteControlSettings");
		return Clss;
	}
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
