#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

namespace Params
{

struct URGIFriendsConversionFunctionLibrary_GetRGISocialStatusFromRGIFriendsStatus final
{
public:
	enum class EERGIFriendsFriendStatus               InStatus;
	enum class EERGISocialSharedPresenceStatus        ReturnValue;
};

struct URGIFriendsConversionFunctionLibrary_GetRGISocialPlatformFromRGIFriendsPlatform final
{
public:
	enum class EERGIFriendsPlatform                   InPlatform;
	enum class EERGISocialSharedPlatform              ReturnValue;
};

struct URGIFriendsConversionFunctionLibrary_GetRGIFriendsStatusFromRGISocialStatus final
{
public:
	enum class EERGISocialSharedPresenceStatus        InStatus;
	enum class EERGIFriendsFriendStatus               ReturnValue;
};

struct URGIFriendsConversionFunctionLibrary_GetRGIFriendsPlatformFromRGISocialPlatform final
{
public:
	enum class EERGISocialSharedPlatform              InPlatform;
	enum class EERGIFriendsPlatform                   ReturnValue;
};

struct URGIFriendsPlayerViewModel_SetStatus final
{
public:
	enum class EERGIFriendsFriendStatus               Value;
};

struct URGIFriendsPlayerViewModel_SetPreviousAliases final
{
public:
	TArray<class URGIFriendsPreviousAlias*>           InPreviousAliases;
};

struct URGIFriendsPlayerViewModel_SetPresenceState final
{
public:
	class FString                                     Value;
};

struct URGIFriendsPlayerViewModel_SetMessage final
{
public:
	class FString                                     Value;
};

struct URGIFriendsPlayerViewModel_SetIsSelectedFriend final
{
public:
	bool                                              InIsSelectedFriend;
};

struct URGIFriendsPlayerViewModel_SetFirstPartyBAlias final
{
public:
	class FText                                       NewFirstPartyBAlias;
};

struct URGIFriendsPlayerViewModel_SetFirstPartyAAlias final
{
public:
	class FText                                       NewFirstPartyAAlias;
};

struct URGIFriendsPlayerViewModel_SetAccountRank final
{
public:
	class FString                                     Value;
};

struct URGIFriendsPlayerViewModel_OnPreviousAliasesUpdated final
{
public:
	struct FRGIFriendsAliasList                       InPreviousAliases;
};

struct URGIFriendsPlayerViewModel_IsSelectedFriend final
{
public:
	bool                                              ReturnValue;
};

struct URGIFriendsPlayerViewModel_IsPlayingSameProduct final
{
public:
	bool                                              ReturnValue;
};

struct URGIFriendsPlayerViewModel_IsDiscordFriend final
{
public:
	bool                                              ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetVoiceSessionId final
{
public:
	class FString                                     ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetStatus final
{
public:
	enum class EERGIFriendsFriendStatus               ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetPuuid final
{
public:
	class FString                                     ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetProductPresenceName final
{
public:
	class FString                                     ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetProduct final
{
public:
	class FString                                     ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetPreviousAliases final
{
public:
	TArray<class URGIFriendsPreviousAlias*>           ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetPresenceState final
{
public:
	class FString                                     ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetPreferredDisplayName final
{
public:
	class FString                                     ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetPlatform final
{
public:
	enum class EERGIFriendsPlatform                   ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetMessage final
{
public:
	class FString                                     ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetIsRiotFriend final
{
public:
	bool                                              ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetIsRiotBlocked final
{
public:
	bool                                              ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetIsAllBlocked final
{
public:
	bool                                              ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetHasPreviousAlias final
{
public:
	bool                                              ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetHasFirstPartyBAlias final
{
public:
	bool                                              ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetHasFirstPartyAAlias final
{
public:
	bool                                              ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetHasAnyFirstPartyAliases final
{
public:
	bool                                              ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetGameTag final
{
public:
	class FString                                     ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetGameName final
{
public:
	class FString                                     ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetFirstPartyBAlias final
{
public:
	class FText                                       ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetFirstPartyAAlias final
{
public:
	class FText                                       ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetDiscordDisplayName final
{
public:
	class FString                                     ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetCustomPresenceMessage final
{
public:
	class FText                                       ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetCombinedGameNameTagAsText final
{
public:
	class FText                                       ReturnValue;
};

struct URGIFriendsPlayerViewModel_GetAccountRank final
{
public:
	class FString                                     ReturnValue;
};

struct URGIFriendsLoggedPlayerViewModel_SetModel final
{
public:
	TScriptInterface<class IRGIFriendsDataStore>      InDataStore;
	class FString                                     InPuuid;
};

struct URGIFriendsPlayer_SetIsDiscordFriend final
{
public:
	bool                                              bValue;
};

struct URGIFriendsPlayer_SetDiscordDisplayName final
{
public:
	class FString                                     Value;
};

struct URGIFriendsPlayer_IsDiscordFriend final
{
public:
	bool                                              ReturnValue;
};

struct URGIFriendsPlayer_GetDiscordDisplayName final
{
public:
	class FString                                     ReturnValue;
};

struct UFriendsMockedDataStore_OnCustomPrivateDataUpdated final
{
public:
	class FString                                     SerializedData;
};

struct URGIFriendsSubsystem_ViewFirstPartyProfile final
{
public:
	class FString                                     Id;
	struct FDelegateProperty_                         OnSuccess;
	struct FDelegateProperty_                         OnError;
	bool                                              bIsFirstPartyId;
};

struct URGIFriendsSubsystem_UnblockPlayer final
{
public:
	class FString                                     Puuid;
	struct FDelegateProperty_                         OnSuccess;
	struct FDelegateProperty_                         OnError;
};

struct URGIFriendsSubsystem_SetBuddyNote final
{
public:
	class FString                                     Puuid;
	class FString                                     NoteString;
	struct FDelegateProperty_                         OnSuccess;
	struct FDelegateProperty_                         OnError;
};

struct URGIFriendsSubsystem_SendPresence final
{
public:
	struct FDelegateProperty_                         OnSuccess;
	struct FDelegateProperty_                         OnError;
};

struct URGIFriendsSubsystem_SendFriendRequest final
{
public:
	class FString                                     GameNameAndTagLine;
	struct FDelegateProperty_                         OnSuccess;
	struct FDelegateProperty_                         OnError;
};

struct URGIFriendsSubsystem_RemoveFriend final
{
public:
	class FString                                     Puuid;
	struct FDelegateProperty_                         OnSuccess;
	struct FDelegateProperty_                         OnError;
};

struct URGIFriendsSubsystem_GetVersion final
{
public:
	class FText                                       ReturnValue;
};

struct URGIFriendsSubsystem_GetPlayerNamesFromPuuids final
{
public:
	TArray<class FString>                             Puuids;
	struct FDelegateProperty_                         OnSuccess;
};

struct URGIFriendsSubsystem_GetLoggedPlayerPresenceLocalizedContent final
{
public:
	struct FRGIFriendsPresenceLocalizedContent        ReturnValue;
};

struct URGIFriendsSubsystem_GetLoggedPlayer final
{
public:
	class URGIFriendsPlayer*                          ReturnValue;
};

struct URGIFriendsSubsystem_GetIsReady final
{
public:
	bool                                              ReturnValue;
};

struct URGIFriendsSubsystem_GetFriendViewModel final
{
public:
	class FString                                     Puuid;
	class URGIFriendsPlayerViewModel*                 ReturnValue;
};

struct URGIFriendsSubsystem_GetFriends final
{
public:
	struct FRGIFriendsPlayers                         ReturnValue;
};

struct URGIFriendsSubsystem_GetFriendRequestViewModel final
{
public:
	class FString                                     Puuid;
	class URGIFriendsFriendRequestViewModel*          ReturnValue;
};

struct URGIFriendsSubsystem_GetFriendRequests final
{
public:
	struct FRGIFriendsFriendRequests                  ReturnValue;
};

struct URGIFriendsSubsystem_GetFriend final
{
public:
	class FString                                     Puuid;
	class URGIFriendsPlayer*                          ReturnValue;
};

struct URGIFriendsSubsystem_GetCustomPrivateDataObject final
{
public:
	class UObject*                                    ReturnValue;
};

struct URGIFriendsSubsystem_GetBlockedPlayers final
{
public:
	struct FRGIFriendsPlayers                         ReturnValue;
};

struct URGIFriendsSubsystem_DeclineFriendRequest final
{
public:
	class FString                                     Puuid;
	struct FDelegateProperty_                         OnSuccess;
	struct FDelegateProperty_                         OnError;
};

struct URGIFriendsSubsystem_BlockPlayer final
{
public:
	class FString                                     Puuid;
	struct FDelegateProperty_                         OnSuccess;
	struct FDelegateProperty_                         OnError;
};

struct URGIFriendsSubsystem_AcceptFriendRequest final
{
public:
	class FString                                     Puuid;
	struct FDelegateProperty_                         OnSuccess;
	struct FDelegateProperty_                         OnError;
};

struct URGIFriendsAddFriendModalViewModel_SetInputText final
{
public:
	class FText                                       InText;
};

struct URGIFriendsCollectionViewModel_RemoveFriendByPuuid final
{
public:
	class FString                                     FriendPuuid;
};

struct URGIFriendsCollectionViewModel_RemoveFriend final
{
public:
	class URGIFriendsPlayerViewModel*                 FriendToRemove;
};

struct URGIFriendsCollectionViewModel_InitializeViewModel final
{
public:
	class UGameInstance*                              GameInstance;
};

struct URGIFriendsCollectionViewModel_HandleFriendsUpdated final
{
public:
	struct FRGIFriendsPlayers                         FriendList;
};

struct URGIFriendsCollectionViewModel_GetSelectedFriendsPlayerViewModel final
{
public:
	class URGIFriendsPlayerViewModel*                 ReturnValue;
};

struct URGIFriendsCollectionViewModel_GetFriendsCount final
{
public:
	int32                                             ReturnValue;
};

struct URGIFriendsCollectionViewModel_GetFriendByPuuid final
{
public:
	class FString                                     Puuid;
	class URGIFriendsPlayerViewModel*                 ReturnValue;
};

struct URGIFriendsCollectionViewModel_AddFriendToCollection final
{
public:
	class URGIFriendsPlayer*                          FriendData;
	class URGIFriendsPlayerViewModel*                 ReturnValue;
};

struct URGIFriendsFriendRequestCollectionViewModel_SendFriendRequest final
{
public:
	class FString                                     GameNameTag;
};

struct URGIFriendsFriendRequestCollectionViewModel_MakeContext final
{
public:
	struct FMVVMViewModelContext                      ReturnValue;
};

struct URGIFriendsFriendRequestCollectionViewModel_GetOutboundFriendRequestCollection final
{
public:
	TArray<class URGIFriendsFriendRequestViewModel*>  ReturnValue;
};

struct URGIFriendsFriendRequestCollectionViewModel_GetInboundFriendRequestViewModelAtIndex final
{
public:
	int32                                             Index;
	class URGIFriendsFriendRequestViewModel*          ReturnValue;
};

struct URGIFriendsFriendRequestCollectionViewModel_GetInboundFriendRequestCollection final
{
public:
	TArray<class URGIFriendsFriendRequestViewModel*>  ReturnValue;
};

struct URGIFriendsFriendRequestCollectionViewModel_GetFriendRequestViewModel final
{
public:
	class FString                                     Puuid;
	class URGIFriendsFriendRequestViewModel*          ReturnValue;
};

struct URGIFriendsFriendRequestCollectionViewModel_GetAllFriendRequestViewModels final
{
public:
	TArray<class URGIFriendsFriendRequestViewModel*>  ReturnValue;
};

struct URGIFriendsFriendRequestViewModel_GetRequestType final
{
public:
	enum class EERGIFriendRequestType                 ReturnValue;
};

struct URGIFriendsFriendRequestViewModel_GetPuuid final
{
public:
	class FString                                     ReturnValue;
};

struct URGIFriendsFriendRequestViewModel_GetPlatform final
{
public:
	enum class EERGIFriendsPlatform                   ReturnValue;
};

struct URGIFriendsFriendRequestViewModel_GetGameTag final
{
public:
	class FString                                     ReturnValue;
};

struct URGIFriendsFriendRequestViewModel_GetGameName final
{
public:
	class FString                                     ReturnValue;
};

struct URGIFriendsFriendRequestViewModel_GetFullRiotID final
{
public:
	class FString                                     ReturnValue;
};

struct URGIFriendsFriendRequestViewModel_DeclineFriendRequest final
{
public:
	struct FDelegateProperty_                         OnSuccess;
	struct FDelegateProperty_                         OnError;
};

struct URGIFriendsFriendRequestViewModel_AcceptFriendRequest final
{
public:
	struct FDelegateProperty_                         OnSuccess;
	struct FDelegateProperty_                         OnError;
};

struct URGIFriendsRecentPlayerCollectionViewModel_SetRecentPlayers final
{
public:
	TArray<class URGIFriendsRecentPlayerViewModel*>   InRecentPlayers;
};

struct URGIFriendsRecentPlayerCollectionViewModel_RemoveRecentPlayer final
{
public:
	class URGIFriendsRecentPlayerViewModel*           RecentPlayer;
};

struct URGIFriendsRecentPlayerCollectionViewModel_MakeContext final
{
public:
	struct FMVVMViewModelContext                      ReturnValue;
};

struct URGIFriendsRecentPlayerCollectionViewModel_GetRecentPlayers final
{
public:
	TArray<class URGIFriendsRecentPlayerViewModel*>   ReturnValue;
};

struct URGIFriendsRecentPlayerCollectionViewModel_AddRecentPlayer final
{
public:
	class URGIFriendsRecentPlayerViewModel*           NewRecentPlayer;
};

struct URGIFriendsRecentPlayerViewModel_SetPuuid final
{
public:
	class FString                                     InPuuid;
	bool                                              ReturnValue;
};

struct URGIFriendsRecentPlayerViewModel_SetPlatform final
{
public:
	enum class EERGISocialSharedPlatform              InPlatform;
	bool                                              ReturnValue;
};

struct URGIFriendsRecentPlayerViewModel_SetLastSeenTimeStamp final
{
public:
	struct FDateTime                                  InTimeStamp;
	bool                                              ReturnValue;
};

struct URGIFriendsRecentPlayerViewModel_SetIsRiotFriend final
{
public:
	bool                                              bInIsRiotFriend;
	bool                                              ReturnValue;
};

struct URGIFriendsRecentPlayerViewModel_SetGameTag final
{
public:
	class FString                                     InGameTag;
	bool                                              ReturnValue;
};

struct URGIFriendsRecentPlayerViewModel_SetGameName final
{
public:
	class FString                                     InGameName;
	bool                                              ReturnValue;
};

struct URGIFriendsRecentPlayerViewModel_GetPuuid final
{
public:
	class FString                                     ReturnValue;
};

struct URGIFriendsRecentPlayerViewModel_GetPlatform final
{
public:
	enum class EERGISocialSharedPlatform              ReturnValue;
};

struct URGIFriendsRecentPlayerViewModel_GetLastSeenTimeStamp final
{
public:
	struct FDateTime                                  ReturnValue;
};

struct URGIFriendsRecentPlayerViewModel_GetIsRiotFriend final
{
public:
	bool                                              ReturnValue;
};

struct URGIFriendsRecentPlayerViewModel_GetGameTag final
{
public:
	class FString                                     ReturnValue;
};

struct URGIFriendsRecentPlayerViewModel_GetGameName final
{
public:
	class FString                                     ReturnValue;
};

struct URGIFriendsSendPartyInviteViewModel_OnTextSubmitted final
{
public:
	class FText                                       Text;
};

struct URGISocialPartyCollectionViewModel_SetParties final
{
public:
	TArray<class URGISocialPartyViewModel*>           NewParties;
};

struct URGISocialPartyCollectionViewModel_SetAllPartyInvites final
{
public:
	TArray<class URGISocialPartyInviteViewModel*>     NewInvites;
};

struct URGISocialPartyCollectionViewModel_RemoveParty final
{
public:
	class URGISocialPartyViewModel*                   PartyViewModel;
};

struct URGISocialPartyCollectionViewModel_RemoveInvite final
{
public:
	class FString                                     InviteId;
};

struct URGISocialPartyCollectionViewModel_PartyInviteSelected final
{
public:
	class URGISocialPartyInviteViewModel*             PartyInviteViewModel;
};

struct URGISocialPartyCollectionViewModel_OnPartyUpdated final
{
public:
	class FString                                     PartyId;
	class UObject*                                    OptionalContext;
};

struct URGISocialPartyCollectionViewModel_OnPartyInviteSubmitted final
{
public:
	class FString                                     InviteePuuid;
	class FString                                     InviterPuuid;
	class UObject*                                    OptionalContext;
};

struct URGISocialPartyCollectionViewModel_OnPartyInviteListSubmitted final
{
public:
	TArray<class FString>                             InviteePuuids;
	class FString                                     InviterPuuid;
	class UObject*                                    OptionalContext;
};

struct URGISocialPartyCollectionViewModel_OnPartyCreated final
{
public:
	class FString                                     PartyId;
	class UObject*                                    OptionalContext;
};

struct URGISocialPartyCollectionViewModel_OnLeaveParty final
{
public:
	class URGISocialPartyViewModel*                   Party;
};

struct URGISocialPartyCollectionViewModel_OnInviteReceived final
{
public:
	class FString                                     InviteId;
	class UObject*                                    OptionalContext;
};

struct URGISocialPartyCollectionViewModel_OnInviteExpired final
{
public:
	class URGISocialPartyInviteViewModel*             PartyInviteViewModel;
};

struct URGISocialPartyCollectionViewModel_OnInviteDeclined final
{
public:
	class URGISocialPartyInviteViewModel*             PartyInviteViewModel;
};

struct URGISocialPartyCollectionViewModel_OnInviteCancelled final
{
public:
	class URGISocialPartyInviteViewModel*             PartyInviteViewModel;
};

struct URGISocialPartyCollectionViewModel_OnInviteAccepted final
{
public:
	class URGISocialPartyInviteViewModel*             PartyInviteViewModel;
};

struct URGISocialPartyCollectionViewModel_MakeContext final
{
public:
	struct FMVVMViewModelContext                      ReturnValue;
};

struct URGISocialPartyCollectionViewModel_GetRelevantPartyViewModel final
{
public:
	class UObject*                                    OptionalObject;
	class URGISocialPartyViewModel*                   ReturnValue;
};

struct URGISocialPartyCollectionViewModel_GetPartyInviteOutgoingByPuuid final
{
public:
	class FString                                     Puuid;
	class URGISocialPartyInviteViewModel*             ReturnValue;
};

struct URGISocialPartyCollectionViewModel_GetPartyInviteIncomingByPuuid final
{
public:
	class FString                                     Puuid;
	class URGISocialPartyInviteViewModel*             ReturnValue;
};

struct URGISocialPartyCollectionViewModel_GetPartyInvite final
{
public:
	class FString                                     InviteId;
	class URGISocialPartyInviteViewModel*             ReturnValue;
};

struct URGISocialPartyCollectionViewModel_GetPartyById final
{
public:
	class FString                                     PartyId;
	class URGISocialPartyViewModel*                   ReturnValue;
};

struct URGISocialPartyCollectionViewModel_GetParties final
{
public:
	TArray<class URGISocialPartyViewModel*>           ReturnValue;
};

struct URGISocialPartyCollectionViewModel_GetOutboundInvites final
{
public:
	TArray<class URGISocialPartyInviteViewModel*>     ReturnValue;
};

struct URGISocialPartyCollectionViewModel_GetOutboundInviteCount final
{
public:
	int32                                             ReturnValue;
};

struct URGISocialPartyCollectionViewModel_GetInviteCount final
{
public:
	int32                                             ReturnValue;
};

struct URGISocialPartyCollectionViewModel_GetInboundPartyInvite final
{
public:
	int32                                             Index;
	class URGISocialPartyInviteViewModel*             ReturnValue;
};

struct URGISocialPartyCollectionViewModel_GetInboundInvites final
{
public:
	TArray<class URGISocialPartyInviteViewModel*>     ReturnValue;
};

struct URGISocialPartyCollectionViewModel_GetInboundInviteCount final
{
public:
	int32                                             ReturnValue;
};

struct URGISocialPartyCollectionViewModel_GetAllPartyInvites final
{
public:
	TArray<class URGISocialPartyInviteViewModel*>     ReturnValue;
};

struct URGISocialPartyCollectionViewModel_CreateInboundPartyInviteToast final
{
public:
	class URGISocialPartyInviteViewModel*             NewInvite;
};

struct URGISocialPartyCollectionViewModel_AddParty final
{
public:
	class URGISocialPartyViewModel*                   NewParty;
};

struct URGISocialPartyCollectionViewModel_AddInvite final
{
public:
	class URGISocialPartyInviteViewModel*             NewInvite;
};

struct URGISocialPartyInviteViewModel_SetInviteType final
{
public:
	enum class EERGIFriendsListInviteType             InInviteType;
};

struct URGISocialPartyInviteViewModel_SetInviteStatus final
{
public:
	enum class EERGIFriendsFriendStatus               InInviteStatus;
};

struct URGISocialPartyInviteViewModel_SetInviteState final
{
public:
	enum class EERGIFriendsListInviteState            InInviteState;
};

struct URGISocialPartyInviteViewModel_SetInvitePuuid final
{
public:
	class FString                                     InInvitePuuid;
};

struct URGISocialPartyInviteViewModel_SetInviteId final
{
public:
	class FString                                     InInviteId;
};

struct URGISocialPartyInviteViewModel_SetInviteGameTag final
{
public:
	class FString                                     InInviteGameTag;
};

struct URGISocialPartyInviteViewModel_SetInviteGameName final
{
public:
	class FString                                     InInviteGameName;
};

struct URGISocialPartyInviteViewModel_SetInviteCategory final
{
public:
	class FString                                     InInviteCategory;
};

struct URGISocialPartyInviteViewModel_SetDescription final
{
public:
	class FText                                       InDescription;
};

struct URGISocialPartyInviteViewModel_GetInviteType final
{
public:
	enum class EERGIFriendsListInviteType             ReturnValue;
};

struct URGISocialPartyInviteViewModel_GetInviteStatus final
{
public:
	enum class EERGIFriendsFriendStatus               ReturnValue;
};

struct URGISocialPartyInviteViewModel_GetInviteState final
{
public:
	enum class EERGIFriendsListInviteState            ReturnValue;
};

struct URGISocialPartyInviteViewModel_GetInvitePuuid final
{
public:
	class FString                                     ReturnValue;
};

struct URGISocialPartyInviteViewModel_GetInviteId final
{
public:
	class FString                                     ReturnValue;
};

struct URGISocialPartyInviteViewModel_GetInviteGameTag final
{
public:
	class FString                                     ReturnValue;
};

struct URGISocialPartyInviteViewModel_GetInviteGameName final
{
public:
	class FString                                     ReturnValue;
};

struct URGISocialPartyInviteViewModel_GetInviteCategory final
{
public:
	class FString                                     ReturnValue;
};

struct URGISocialPartyInviteViewModel_GetFullRiotID final
{
public:
	class FString                                     ReturnValue;
};

struct URGISocialPartyInviteViewModel_GetDescription final
{
public:
	class FText                                       ReturnValue;
};

struct URGISocialPartyMemberViewModel_SetPuuid final
{
public:
	class FString                                     InPuuid;
};

struct URGISocialPartyMemberViewModel_SetPresenceStatus final
{
public:
	enum class EERGISocialSharedPresenceStatus        InStatus;
};

struct URGISocialPartyMemberViewModel_SetPlatform final
{
public:
	enum class EERGISocialSharedPlatform              InPlatform;
};

struct URGISocialPartyMemberViewModel_SetPartyID final
{
public:
	class FString                                     InPartyID;
};

struct URGISocialPartyMemberViewModel_SetIsPartyLeader final
{
public:
	bool                                              bInIsPartyLeader;
};

struct URGISocialPartyMemberViewModel_SetIsLocalPlayer final
{
public:
	bool                                              bInIsLocalPlayer;
};

struct URGISocialPartyMemberViewModel_SetIsFriend final
{
public:
	bool                                              bInIsFriend;
};

struct URGISocialPartyMemberViewModel_SetGameTag final
{
public:
	class FString                                     InGameTag;
};

struct URGISocialPartyMemberViewModel_SetGameName final
{
public:
	class FString                                     InGameName;
};

struct URGISocialPartyMemberViewModel_OnSendFriendRequestError final
{
public:
	enum class EERGIFriendsRequestResponseErrors      ErrorType;
};

struct URGISocialPartyMemberViewModel_OnBlockPlayerError final
{
public:
	enum class EERGIFriendsBlockPlayerResponseErrors  ErrorType;
};

struct URGISocialPartyMemberViewModel_MemberUpdated final
{
public:
	class UObject*                                    OptionalContext;
};

struct URGISocialPartyMemberViewModel_IsFriend final
{
public:
	bool                                              ReturnValue;
};

struct URGISocialPartyMemberViewModel_GetPuuid final
{
public:
	class FString                                     ReturnValue;
};

struct URGISocialPartyMemberViewModel_GetPresenceStatus final
{
public:
	enum class EERGISocialSharedPresenceStatus        ReturnValue;
};

struct URGISocialPartyMemberViewModel_GetPlatform final
{
public:
	enum class EERGISocialSharedPlatform              ReturnValue;
};

struct URGISocialPartyMemberViewModel_GetPartyID final
{
public:
	class FString                                     ReturnValue;
};

struct URGISocialPartyMemberViewModel_GetIsPartyLeader final
{
public:
	bool                                              ReturnValue;
};

struct URGISocialPartyMemberViewModel_GetIsLocalPlayer final
{
public:
	bool                                              ReturnValue;
};

struct URGISocialPartyMemberViewModel_GetGameTag final
{
public:
	class FString                                     ReturnValue;
};

struct URGISocialPartyMemberViewModel_GetGameName final
{
public:
	class FString                                     ReturnValue;
};

struct URGISocialPartyViewModel_SetStatus final
{
public:
	enum class EERGIFriendsPresencesPartyStatus       InStatus;
};

struct URGISocialPartyViewModel_SetPartyId final
{
public:
	class FString                                     InPartyId;
};

struct URGISocialPartyViewModel_SetMembers final
{
public:
	TArray<class URGISocialPartyMemberViewModel*>     InMembers;
};

struct URGISocialPartyViewModel_SetMaxPartySize final
{
public:
	int32                                             InMaxPartySize;
};

struct URGISocialPartyViewModel_SetGameTag final
{
public:
	class FText                                       InGameTag;
};

struct URGISocialPartyViewModel_SetGameName final
{
public:
	class FText                                       InGameName;
};

struct URGISocialPartyViewModel_SetCurrentPartySize final
{
public:
	int32                                             InPartySize;
};

struct URGISocialPartyViewModel_RemoveMemberByPuuid final
{
public:
	class FString                                     Puuid;
};

struct URGISocialPartyViewModel_RemoveMember final
{
public:
	class URGISocialPartyMemberViewModel*             Member;
};

struct URGISocialPartyViewModel_PartyUpdated final
{
public:
	class UObject*                                    OptionalContext;
};

struct URGISocialPartyViewModel_GetStatus final
{
public:
	enum class EERGIFriendsPresencesPartyStatus       ReturnValue;
};

struct URGISocialPartyViewModel_GetPartyId final
{
public:
	class FString                                     ReturnValue;
};

struct URGISocialPartyViewModel_GetMembers final
{
public:
	TArray<class URGISocialPartyMemberViewModel*>     ReturnValue;
};

struct URGISocialPartyViewModel_GetMaxPartySize final
{
public:
	int32                                             ReturnValue;
};

struct URGISocialPartyViewModel_GetGameTag final
{
public:
	class FText                                       ReturnValue;
};

struct URGISocialPartyViewModel_GetGameName final
{
public:
	class FText                                       ReturnValue;
};

struct URGISocialPartyViewModel_GetCurrentPartySize final
{
public:
	int32                                             ReturnValue;
};

struct URGISocialPartyViewModel_AddMember final
{
public:
	class URGISocialPartyMemberViewModel*             NewMember;
};

}
}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
