#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

struct FReleaseDetailsDTO
{
public:
	class FString                                     Id;
};

struct FDownloadDetailsDTO
{
public:
	class FString                                     Url;
	bool                                              SCD_Required;
	uint8                                             Pad_0[0x0007];
};

struct FReleaseDTO
{
public:
	struct FReleaseDetailsDTO                         Release;
	struct FDownloadDetailsDTO                        Download;
};

struct FPatchsieveVersionSetDTO
{
public:
	TArray<struct FReleaseDTO>                        Releases;
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
