#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

namespace Params
{

struct URGIInputLatencyBlueprintLibrary_SetTargetFrametimeOverheadPercentage final
{
public:
	int32                                             InTargetFrametimeOverheadPercentage;
};

struct URGIInputLatencyBlueprintLibrary_SetRGIInputLatencyEnabled final
{
public:
	bool                                              bEnabled;
};

struct URGIInputLatencyBlueprintLibrary_IsRGIInputLatencyPluginSupported final
{
public:
	bool                                              ReturnValue;
};

struct URGIInputLatencyBlueprintLibrary_GetTargetFrametimeOverheadPercentage final
{
public:
	int32                                             ReturnValue;
};

struct URGIInputLatencyBlueprintLibrary_GetRGIInputLatencyEnabled final
{
public:
	bool                                              ReturnValue;
};

}
}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
