#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class URGIJiraSubmitterLibrary : public UBlueprintFunctionLibrary
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGIJiraSubmitterLibrary");
		return Clss;
	}

	static void SubmitJiraIssueLatent(class UObject* WorldContextObject, const struct FLatentActionInfo& LatentInfo, class FString* OutIssueId, int32* OutIssueCode, class FString* Summary, const class FString& Type, const class FString& Description, bool bIncludeScreenshot, bool bIncludeServerLog);
	static void SubmitJiraIssue(class UObject* WorldContextObject, class FString* Summary, const class FString& Type, const class FString& Description, bool bIncludeScreenshot, bool bIncludeServerLog);
};

class URGIJiraSubmitterSubsystem : public UEngineSubsystem
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGIJiraSubmitterSubsystem");
		return Clss;
	}
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
