#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

namespace Params
{

struct URGIOPHttpFunctionLibrary_JoinUrls final
{
public:
	class FString                                     FirstUrl;
	class FString                                     SecondUrl;
	class FString                                     ReturnValue;
};

}
}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
