#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

struct FRGIOPAmbassadorError
{
public:
	int32                                             HttpStatus;
	uint8                                             Pad_0[0x0004];
	class FString                                     ErrorCode;
	class FString                                     Message;
	class FString                                     Details;
	struct FJsonObjectWrapper                         Payload;
	class FString                                     RawResponseBody;
};

struct FRGIOPPlatformToken
{
public:
	class FString                                     PlatformType;
	class FString                                     PlatformOS;
	class FString                                     PlatformOSVersion;
	class FString                                     PlatformChipset;
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
