#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

enum class ERGIPermissionsUsersCommunicationPermissionsResponseErrors : uint8
{
	RiotGamesApiUpdateRequired                = 0,
	NotAvailable                              = 1,
	PlatformUserNotConnected                  = 2,
	InternalError                             = 3,
	ERGIPermissionsUsersCommunicationPermissionsResponseErrors_MAX = 4,
};

enum class ERGIPermissionsCommunicationPermissionState : uint8
{
	NotAllowed                                = 0,
	Allowed                                   = 1,
	ERGIPermissionsCommunicationPermissionState_MAX = 2,
};

enum class ERGIPermissionsCommunicationPermissionType : uint8
{
	Unknown                                   = 0,
	Text                                      = 1,
	Voice                                     = 2,
	ERGIPermissionsCommunicationPermissionType_MAX = 3,
};

enum class ERGIPermissionsCrossPlayPermissionsPartyCompatibility : uint8
{
	Compatible                                = 0,
	NewMemberDoesNotSupportCrossPlay          = 1,
	TargetPartyDoesNotSupportCrossPlay        = 2,
	Invalid                                   = 3,
	PartyFull                                 = 4,
	MissingData                               = 5,
	ERGIPermissionsCrossPlayPermissionsPartyCompatibility_MAX = 6,
};

enum class ERGIPermissionsCrossPlayPermissionsPlayerCompatibility : uint8
{
	Compatible                                = 0,
	LocalPlayerCrossPlayOff                   = 1,
	TargetPlayerCrossPlayOff                  = 2,
	Invalid                                   = 3,
	ERGIPermissionsCrossPlayPermissionsPlayerCompatibility_MAX = 4,
};

enum class ERGIPermissionsTextChatPermission : uint8
{
	Everyone                                  = 0,
	FriendsOnly                               = 1,
	None                                      = 2,
	ERGIPermissionsTextChatPermission_MAX     = 3,
};

enum class ERGIPermissionsUsersCommunicationPermissionsDenyReasons : uint8
{
	Unknown                                   = 0,
	NotAllowed                                = 1,
	MissingPrivilege                          = 2,
	PrivilegeRestrictsTarget                  = 3,
	BlockListRestrictsTarget                  = 4,
	MuteListRestrictsTarget                   = 5,
	PrivacySettingRestrictsTarget             = 6,
	CrossNetworkUserMustBeFriend              = 7,
	ERGIPermissionsUsersCommunicationPermissionsDenyReasons_MAX = 8,
};

struct FRGIPermissionsUsersCommunicationPermissions
{
public:
	uint8                                             Pad_0[0x0050];
};

struct FRGIPermissionsCrossPlayPermissionsCheckResult
{
public:
	enum class EERGIPermissionsCrossPlayPermissionsPlayerCompatibility PlayerCompatibility;
	enum class EERGIPermissionsCrossPlayPermissionsPartyCompatibility InviteCompatibility;
	enum class EERGIPermissionsCrossPlayPermissionsPartyCompatibility JoinCompatibility;
};

struct FRGIPermissionsCrossPlayPermissions
{
public:
	bool                                              bHasPlayerCrossPlayEnabled;
	bool                                              bIsInParty;
	bool                                              bHasPartyCrossPlayEnabled;
	uint8                                             Pad_0[0x0005];
	TArray<enum class EERGISocialSharedPlatform>      PartyMemberPlatforms;
	uint32                                            CurrentPartySize;
	uint32                                            MaxPartySize;
};

struct FRGIPermissionsCommunicationPermission
{
public:
	enum class EERGIPermissionsCommunicationPermissionState Permission;
	enum class EERGIPermissionsCommunicationPermissionType Type;
	uint8                                             Pad_0[0x0006];
	TArray<enum class EERGIPermissionsUsersCommunicationPermissionsDenyReasons> Reasons;
};

struct FRGIPermissionsUserCommunicationPermissions
{
public:
	uint8                                             Pad_0[0x0020];
};

struct FRGIPermissionsPermissionEnum
{
public:
	class FString                                     Type;
	TArray<class FString>                             Values;
};

struct FRGIPermissionsPermissionLimit
{
public:
	uint8                                             Pad_0[0x0038];
};

struct FRGIPermissionsLoggedPlayerPermissionDetails
{
public:
	class FString                                     PermissionId;
	bool                                              bIsGranted;
	uint8                                             Pad_0[0x0007];
	TArray<struct FRGIPermissionsPermissionEnum>      Enums;
	TArray<struct FRGIPermissionsPermissionLimit>     Limit;
	uint8                                             Pad_1[0x0050];
};

struct FRGIPermissionsLoggedPlayerPermissions
{
public:
	TArray<struct FRGIPermissionsLoggedPlayerPermissionDetails> Permissions;
	struct FRGIPermissionsCrossPlayPermissions        DetailedCrossPlayPermissions;
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
