#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class URGISocialSharedBaseDataStore : public UObject
{
public:
	uint8                                             Pad_0[0x03A0];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedBaseDataStore");
		return Clss;
	}
};

class URGISocialSharedPlayerViewModel : public UMVVMViewModelBase
{
public:
	class FString                                     Puuid;
	class FString                                     Pid;
	class FString                                     GameName;
	class FString                                     PreferredDisplayName;
	class FString                                     GameTag;
	class FString                                     Region;
	class FString                                     Product;
	class FString                                     ProductPresenceName;
	class FString                                     ProductFolderName;
	class FString                                     Note;
	class FString                                     FirstPartyAAlias;
	class FString                                     FirstPartyBAlias;
	class FString                                     FirstPartyBSuffix;
	class FString                                     Message;
	class FText                                       CustomPresenceMessage;
	class FString                                     AccountRank;
	enum class EERGISocialSharedPresenceStatus        Status;
	enum class EERGISocialSharedPlatform              Platform;
	uint8                                             Pad_0[0x0002];
	int32                                             VisiblePlatforms;
	class FString                                     PresenceState;
	uint8                                             Pad_1[0x0020];
	class FString                                     DiscordDisplayName;
	bool                                              bHasPartyCrossPlayEnabled;
	bool                                              bHasPlayerCrossPlayEnabled;
	bool                                              bIsDiscordFriend;
	bool                                              bIsRiotFriend;
	bool                                              bIsActivePlatformFriend;
	bool                                              bIsRiotBlocked;
	bool                                              bIsActivePlatformBlocked;
	uint8                                             Pad_2[0x0001];
	TArray<struct FRGISocialSharedParty>              Parties;
	bool                                              bIsPartyLeader;
	bool                                              bIsInParty;
	uint8                                             Pad_3[0x0006];
	struct FRGISocialSharedCrossPlayPermissions       CrossPlayPermissions;
	TArray<class URGISocialSharedPreviousAlias*>      PreviousAliases;
	class URGISocialSharedBaseDataStore*              DataStore;
	class URGISocialSharedCustomPresenceMessageViewModel* CustomPresenceMessageViewModel;
	uint8                                             Pad_4[0x0010];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedPlayerViewModel");
		return Clss;
	}

	void SetStatus(enum class EERGISocialSharedPresenceStatus InStatus);
	void SetRegion(const class FString& InRegion);
	void SetPuuid(const class FString& InPuuid);
	void SetProductPresenceName(const class FString& InProductPresenceName);
	void SetProductFolderName(const class FString& InProductFolderName);
	void SetProduct(const class FString& InProduct);
	void SetPreviousAliases(TArray<class URGISocialSharedPreviousAlias*>* InPreviousAliases);
	void SetPresenceState(const class FString& Value);
	void SetPreferredDisplayName(const class FString& InDisplayName);
	void SetPlatform(enum class EERGISocialSharedPlatform InPlatform);
	void SetPid(const class FString& InPid);
	void SetNote(const class FString& InNote);
	void SetMessage(const class FString& InMessage);
	void SetIsRiotFriend(bool bInIsRiotFriend);
	void SetIsRiotBlocked(bool bInIsRiotBlocked);
	void SetIsDiscordFriend(bool bInIsDiscordFriend);
	void SetIsActivePlatformFriend(bool bInIsActivePlatformFriend);
	void SetIsActivePlatformBlocked(bool bInIsActivePlatformBlocked);
	void SetHasPlayerCrossPlayEnabled(bool bInHasPlayerCrossPlayEnabled);
	void SetHasPartyCrossPlayEnabled(bool bInHasPartyCrossPlayEnabled);
	void SetGameTag(const class FString& InGameTag);
	void SetGameName(const class FString& InGameName);
	void SetFirstPartyBSuffix(const class FString& InFirstPartyBSuffix);
	void SetFirstPartyBAlias(const class FString& NewFirstPartyBAlias);
	void SetFirstPartyAAlias(const class FString& NewFirstPartyAAlias);
	void SetDiscordDisplayName(const class FString& InDiscordDisplayName);
	void SetAccountRank(const class FString& InAccountRank);
	void OnPreviousAliasesUpdated(struct FRGISocialSharedAliasList* InPreviousAliases);
	bool IsPlayingSameProductAsLoggedPlayer();
	bool IsPartyLeader();
	enum class EERGISocialSharedPresenceStatus GetStatus();
	bool GetRelevantParty(struct FRGISocialSharedParty* InPartyReference);
	class FString GetRegion();
	class FString GetPuuid();
	class FString GetProductPresenceName();
	class FString GetProductFolderName();
	class FString GetProduct();
	TArray<class URGISocialSharedPreviousAlias*> GetPreviousAliases();
	class FString GetPresenceState();
	class FString GetPreferredDisplayName();
	enum class EERGISocialSharedPlatform GetPlatform();
	class FString GetPid();
	class FString GetNote();
	class FString GetMessage();
	int32 GetMaxPartySize();
	bool GetIsRiotFriend();
	bool GetIsRiotBlocked();
	bool GetIsPartyOpen();
	bool GetIsInParty();
	bool GetIsDiscordFriend();
	bool GetIsAllBlocked();
	bool GetIsActivePlatformFriend();
	bool GetIsActivePlatformBlocked();
	bool GetHasRiotIdentity();
	bool GetHasPreviousAlias();
	bool GetHasPlayerCrossPlayEnabled();
	bool GetHasPartyCrossPlayEnabled();
	bool GetHasNote();
	bool GetHasFirstPartyBAlias();
	bool GetHasFirstPartyAAlias();
	bool GetHasDiscordDisplayName();
	bool GetHasAnyFirstPartyAliases();
	class FString GetGameTag();
	class FString GetGameName();
	class FString GetFirstPartyBSuffix();
	class FString GetFirstPartyBAlias();
	class FString GetFirstPartyAAlias();
	class FString GetDiscordDisplayName();
	class FText GetCustomPresenceMessage();
	int32 GetCurrentPartySize();
	struct FRGISocialSharedCrossPlayPermissions GetCrossPlayPermissions();
	class FText GetCombinedGameNameTagAsText();
	class FString GetAccountRank();
};

class URGISocialSharedBlockedPlayerViewModel : public URGISocialSharedPlayerViewModel
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedBlockedPlayerViewModel");
		return Clss;
	}
};

class URGISocialContextMenuItemViewModel : public UMVVMViewModelBase
{
public:
	class FString                                     ContextMenuId;
	class FString                                     DisplayKey;
	class FString                                     StringTableKey;
	enum class EERGISocialContextMenuItemIntent       Intent;
	bool                                              bIsEnabled;
	bool                                              bShouldTriggerClose;
	bool                                              bShouldTriggerOnHold;
	uint8                                             Pad_0[0x001C];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialContextMenuItemViewModel");
		return Clss;
	}

	void ExecuteActionIfBound();
};

class URGISocialSharedContextMenuItemsViewModel : public UMVVMViewModelBase
{
public:
	uint8                                             Pad_0[0x0008];
	TArray<class URGISocialContextMenuItemViewModel*> ContextMenuItems;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedContextMenuItemsViewModel");
		return Clss;
	}

	void InitializeViewModel(class UGameInstance* GameInstance);
	bool GetHasContextMenu();
	TArray<class URGISocialContextMenuItemViewModel*> GetContextMenuItems();
};

class URGISocialSharedCustomPresenceMessageViewModel : public UMVVMViewModelBase
{
public:
	class UGameInstance*                              GameInstance;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedCustomPresenceMessageViewModel");
		return Clss;
	}
};

class URGISocialSharedDataStore : public UInterface
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedDataStore");
		return Clss;
	}
};

class URGISocialSharedFriendPlayerViewModel : public URGISocialSharedPlayerViewModel
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedFriendPlayerViewModel");
		return Clss;
	}
};

class URGISocialSharedLoggedPlayerViewModel : public URGISocialSharedPlayerViewModel
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedLoggedPlayerViewModel");
		return Clss;
	}
};

class URGISocialSharedMockedDataStore : public URGISocialSharedBaseDataStore
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedMockedDataStore");
		return Clss;
	}
};

class URGISocialSharedNoOpDataStore : public UObject
{
public:
	uint8                                             Pad_0[0x0040];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedNoOpDataStore");
		return Clss;
	}
};

class URGISocialSharedPlayerCollectionViewModel : public UMVVMViewModelBase
{
public:
	TArray<class URGISocialSharedPlayerViewModel*>    FriendsViewModels;
	class URGISocialSharedPlayerViewModel*            SelectedPlayerViewModel;
	class URGISocialSharedBaseDataStore*              DataStore;
	TMap<class FString, class URGISocialSharedFriendPlayerViewModel*> PuuidToFriendViewModelMap;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedPlayerCollectionViewModel");
		return Clss;
	}

	void InitializeViewModel(class UGameInstance* GameInstance);
	class URGISocialSharedPlayerViewModel* GetSelectedPlayerViewModel();
	class URGISocialSharedPlayerViewModel* GetFriendPlayerViewModelByPuuid(const class FString& Puuid);
};

class URGISocialSharedPreviousAlias : public UObject
{
public:
	class FString                                     PreviousAlias;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedPreviousAlias");
		return Clss;
	}
};

class URGISocialSharedViewModelHelper : public UBlueprintFunctionLibrary
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedViewModelHelper");
		return Clss;
	}
};

class URGISocialSharedViewModelInterface : public UInterface
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedViewModelInterface");
		return Clss;
	}
};

class URGISocialSharedSelectableViewModelInterface : public UInterface
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedSelectableViewModelInterface");
		return Clss;
	}

	void OnViewModelSelected();
};

class URGISocialSharedButtonAction : public UObject
{
public:
	uint8                                             Pad_0[0x0048];
	class FText                                       ActionText;
	class FText                                       ActionTextKey;
	struct FGameplayTag                               ActionTag;
	uint8                                             Pad_1[0x0004];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedButtonAction");
		return Clss;
	}

	void SetActionTextKey(class FText* InActionKey);
	void SetActionText(class FText* InActionText);
	class FText GetActionTextKey();
	class FText GetActionText();
	void Execute();
};

class URGISocialSharedModalAction : public UObject
{
public:
	uint8                                             Pad_0[0x0018];
	class FText                                       ActionText;
	struct FGameplayTag                               ActionTag;
	uint8                                             Pad_1[0x0004];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedModalAction");
		return Clss;
	}

	void SetActionText(class FText* InActionText);
	class FText GetActionText();
	void Execute();
};

class URGISocialSharedSettings : public UDeveloperSettings
{
public:
	TSoftClassPtr<class URGISocialSharedAudioViewModel> DefaultAudioViewModel;
	bool                                              bAreAudioEventsEnabled;
	uint8                                             Pad_0[0x0003];
	int32                                             iMaxSoundEventsPerCooldown;
	float                                             fSoundCooldownSeconds;
	uint8                                             Pad_1[0x0004];
	TSoftClassPtr<class URGISocialSharedCustomPresenceMessageViewModel> CustomPresenceMessageViewModelClass;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedSettings");
		return Clss;
	}
};

class URGISocialSharedSubsystem : public UGameInstanceSubsystem
{
public:
	class URGISocialSharedModalManagerViewModel*      ModalManager;
	class URGISocialSharedNavigationViewModel*        NavigationViewModel;
	class URGISocialSharedAudioViewModel*             AudioViewModel;
	class URGISocialSharedToastCollectionViewModel*   ToastCollectionViewModel;
	class URGISocialSharedPlayerCollectionViewModel*  PlayerCollectionViewModel;
	class URGISocialSharedConsoleFriendCollectionViewModel* ConsoleFriendCollectionViewModel;
	class URGISocialSharedBaseDataStore*              DataStore;
	class URGISocialSharedLoggedPlayerViewModel*      LoggedPlayerViewModel;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedSubsystem");
		return Clss;
	}

	void SetupInitialDataAndDelegates();
	static bool IsPlatformRiotPlatform(enum class EERGISocialSharedPlatform InPlatform);
	static class UMVVMSubsystem* GetMVVMSubsystem();
	static class FString GetLocalizedTimeString(struct FDateTime* UtcTimestamp);
	static class FString GetLocalizedDateTimeString(struct FDateTime* UtcTimestamp);
	static class FString GetLocalizedDateString(struct FDateTime* UtcTimestamp);
	static class FString GetLocal24HourTimeString(struct FDateTime* UtcTimestamp);
	class URGISocialSharedAudioViewModel* GetAudioViewModel();
	class URGISocialSharedToastViewModel* CreateToastSuccess(class FText* Text, int32 Duration);
	class URGISocialSharedToastViewModel* CreateToastError(class FText* Text, int32 Duration);
	class URGISocialSharedToastViewModel* CreateToastDefault(class FText* Text, int32 Duration);
	class URGISocialSharedToastViewModel* CreateInboundPartyInviteToast(const class FString& GameName, int32 Duration, const class FString& Puuid);
	class URGISocialSharedToastViewModel* CreateInboundFriendRequestToast(const class FString& GameName, int32 Duration, const class FString& Puuid);
	void CopyTextToClipboard(const class FString& Text);
};

class URGIUINavigationModel : public UMVVMViewModelBase
{
public:
	class FString                                     NavigationPath;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGIUINavigationModel");
		return Clss;
	}
};

class URGISocialSharedAudioViewModel : public UMVVMViewModelBase
{
public:
	struct FMulticastInlineDelegateProperty_          OnAudioEventTriggered;
	TArray<enum class EEAudioLockID>                  LockIDsInUse;
	struct FRGISocialSharedAudioViewModelEventContext LastEvent;
	TArray<struct FDateTime>                          LastEventTimes;
	uint8                                             Pad_0[0x0010];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedAudioViewModel");
		return Clss;
	}

	void UnlockAudio(enum class EEAudioLockID LockId);
	void LockAudio(enum class EEAudioLockID LockId, const class FString& ExtraContext);
	bool IsAudioLocked(enum class EEAudioLockID LockId);
	void Initialize();
	class FString GetLocksFormatted();
	struct FRGISocialSharedAudioViewModelEventContext GetLastEvent();
	void BroadcastAudioEvent(struct FRGISocialSharedAudioViewModelEventContext* EventContext);
};

class URGISocialSharedConsoleFriendCollectionViewModel : public UMVVMViewModelBase
{
public:
	TArray<class URGISocialSharedPlayerViewModel*>    PlayersViewModels;
	class URGISocialSharedBaseDataStore*              DataStore;
	TMap<class FString, class URGISocialSharedConsoleFriendPlayerViewModel*> PuuidToFriendViewModelMap;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedConsoleFriendCollectionViewModel");
		return Clss;
	}

	void SetModel(class URGISocialSharedBaseDataStore* InDataStore);
	class URGISocialSharedPlayerViewModel* GetFriendPlayerViewModelByPuuid(const class FString& Puuid);
};

class URGISocialSharedConsoleFriendPlayerViewModel : public URGISocialSharedFriendPlayerViewModel
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedConsoleFriendPlayerViewModel");
		return Clss;
	}
};

class URGISocialSharedModalManagerViewModel : public UMVVMViewModelBase
{
public:
	TArray<class URGISocialSharedModalViewModelBase*> ModalStack;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedModalManagerViewModel");
		return Clss;
	}

	void PushSimpleModal(const class FName& ModalType, class FText* Title, class FText* Message);
	void PushModal(class URGISocialSharedModalViewModelBase* NewModal);
	void PopModal();
	bool HasActiveModal();
	class URGISocialSharedModalViewModelBase* GetTopModal();
	void ClearModals();
};

class URGISocialSharedModalViewModelBase : public UMVVMViewModelBase
{
public:
	TArray<class URGISocialSharedButtonAction*>       ModalActions;
	uint8                                             Pad_0[0x0018];
	class FName                                       ModalType;
	uint8                                             Pad_1[0x0004];
	class FText                                       Title;
	class FText                                       Message;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedModalViewModelBase");
		return Clss;
	}

	void SetModel(class UObject* Model);
	void OnRequestCloseClicked();
	void AddDefaultCancelAction(class FText* CancelText);
};

class URGISocialSharedNavigationViewModel : public UMVVMViewModelBase
{
public:
	class FString                                     NavigationPath;
	TArray<class FString>                             NavigationHistory;
	class URGIUINavigationModel*                      NavigationModel;
	int32                                             MaxHistorySize;
	uint8                                             Pad_0[0x0004];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedNavigationViewModel");
		return Clss;
	}

	void SetNavigationPath(const class FString& NewPath);
	void NavigateBack();
	void Initialize(class URGIUINavigationModel* Model);
	class FString GetNavigationPath();
	void AddToNavigationPath(const class FString& NewPath);
};

class URGISocialSharedToastCollectionViewModel : public UMVVMViewModelBase
{
public:
	TArray<class URGISocialSharedToastViewModel*>     ToastStack;
	class URGISocialSharedToastViewModel*             LatestToast;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedToastCollectionViewModel");
		return Clss;
	}

	class URGISocialSharedToastViewModel* AddToast(class FText* Text, int32 Duration, enum class EEToastState State);
	class URGISocialSharedToastViewModel* AddPartyInviteInboundToast(const class FString& Puuid, const class FString& GameName, class URGISocialSharedButtonAction* AcceptAction, class URGISocialSharedButtonAction* CancelAction, int32* Duration);
	class URGISocialSharedToastViewModel* AddFriendRequestInboundToast(const class FString& Puuid, const class FString& GameName, class URGISocialSharedButtonAction* AcceptAction, class URGISocialSharedButtonAction* CancelAction, int32* Duration);
};

class URGISocialSharedToastViewModel : public UMVVMViewModelBase
{
public:
	class FText                                       ToastText;
	bool                                              ToastValid;
	uint8                                             Pad_0[0x0003];
	int32                                             ToastDuration;
	enum class EEToastState                           ToastState;
	uint8                                             Pad_1[0x0007];
	class FString                                     ToastPuuid;
	struct FDateTime                                  ToastArrivalTime;
	TArray<class URGISocialSharedButtonAction*>       ToastActions;
	enum class EEToastType                            ToastTag;
	uint8                                             Pad_2[0x000F];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("RGISocialSharedToastViewModel");
		return Clss;
	}

	void SetToastValid(bool Valid);
	void SetToastText(class FText* Text);
	void SetToastState(enum class EEToastState State);
	void SetToastPuuid(const class FString& Puuid);
	void SetToastDuration(int32 Duration);
	bool IsToastValid();
	void Initialize(class FText* Text, int32* Duration, enum class EEToastState State, const class FString& Puuid);
	class FText GetToastText();
	enum class EEToastState GetToastState();
	class FString GetToastPuuid();
	int32 GetToastDuration();
	void ForceToastExpire();
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
