#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

enum class ERGITonemapperType : uint8
{
	DefaultUE                                 = 0,
	ExtendedReinhard                          = 1,
	ACESLuminanceOnlyFit                      = 2,
	GranTurismo                               = 3,
	LegacyUE                                  = 4,
	AgX                                       = 5,
	ERGITonemapperType_MAX                    = 6,
};

enum class EAgXLookType : uint8
{
	Default                                   = 0,
	Golden                                    = 1,
	Punchy                                    = 2,
	EAgXLookType_MAX                          = 3,
};

struct FUELegacyTonemapperSettings
{
public:
	bool                                              bOverrideContentTonemappingSettings;
	uint8                                             Pad_0[0x0003];
	struct FLinearColor                               FilmWhitePoint;
	struct FLinearColor                               FilmShadowTint;
	float                                             FilmShadowTintBlend;
	float                                             FilmShadowTintAmount;
	float                                             FilmSaturation;
	struct FLinearColor                               FilmChannelMixerRed;
	struct FLinearColor                               FilmChannelMixerGreen;
	struct FLinearColor                               FilmChannelMixerBlue;
	float                                             FilmContrast;
	float                                             FilmToeAmount;
	float                                             FilmHealAmount;
	float                                             FilmDynamicRange;
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
