#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

struct FSessionServicePing
{
public:
	class FString                                     UserName;
};

struct FSessionServicePong
{
public:
	bool                                              Authorized;
	uint8                                             Pad_0[0x0007];
	class FString                                     BuildDate;
	class FString                                     DeviceName;
	struct FGuid                                      InstanceId;
	class FString                                     InstanceName;
	class FString                                     PlatformName;
	struct FGuid                                      SessionId;
	class FString                                     SessionName;
	class FString                                     SessionOwner;
	bool                                              Standalone;
	uint8                                             Pad_1[0x0007];
};

struct FSessionServiceLog
{
public:
	class FName                                       Category;
	uint8                                             Pad_0[0x0004];
	class FString                                     Data;
	struct FGuid                                      InstanceId;
	double                                            TimeSeconds;
	uint8                                             Verbosity;
	uint8                                             Pad_1[0x0007];
};

struct FSessionServiceLogSubscribe
{
public:
	uint8                                             Pad_0[0x0001];
};

struct FSessionServiceLogUnsubscribe
{
public:
	uint8                                             Pad_0[0x0001];
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
