#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

enum class EStructUtilsResult : uint8
{
	Valid                                     = 0,
	NotValid                                  = 1,
	EStructUtilsResult_MAX                    = 2,
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
