#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

enum class ESynth1OscType : uint8
{
	Sine                                      = 0,
	Saw                                       = 1,
	Triangle                                  = 2,
	Square                                    = 3,
	Noise                                     = 4,
	Count                                     = 5,
	ESynth1OscType_MAX                        = 6,
};

enum class ESynthLFOType : uint8
{
	Sine                                      = 0,
	UpSaw                                     = 1,
	DownSaw                                   = 2,
	Square                                    = 3,
	Triangle                                  = 4,
	Exponential                               = 5,
	RandomSampleHold                          = 6,
	Count                                     = 7,
	ESynthLFOType_MAX                         = 8,
};

enum class ESynthLFOMode : uint8
{
	Sync                                      = 0,
	OneShot                                   = 1,
	Free                                      = 2,
	Count                                     = 3,
	ESynthLFOMode_MAX                         = 4,
};

enum class ESynthLFOPatchType : uint8
{
	PatchToNone                               = 0,
	PatchToGain                               = 1,
	PatchToOscFreq                            = 2,
	PatchToFilterFreq                         = 3,
	PatchToFilterQ                            = 4,
	PatchToOscPulseWidth                      = 5,
	PatchToOscPan                             = 6,
	PatchLFO1ToLFO2Frequency                  = 7,
	PatchLFO1ToLFO2Gain                       = 8,
	Count                                     = 9,
	ESynthLFOPatchType_MAX                    = 10,
};

enum class ESynthModEnvPatch : uint8
{
	PatchToNone                               = 0,
	PatchToOscFreq                            = 1,
	PatchToFilterFreq                         = 2,
	PatchToFilterQ                            = 3,
	PatchToLFO1Gain                           = 4,
	PatchToLFO2Gain                           = 5,
	PatchToLFO1Freq                           = 6,
	PatchToLFO2Freq                           = 7,
	Count                                     = 8,
	ESynthModEnvPatch_MAX                     = 9,
};

enum class ESynthModEnvBiasPatch : uint8
{
	PatchToNone                               = 0,
	PatchToOscFreq                            = 1,
	PatchToFilterFreq                         = 2,
	PatchToFilterQ                            = 3,
	PatchToLFO1Gain                           = 4,
	PatchToLFO2Gain                           = 5,
	PatchToLFO1Freq                           = 6,
	PatchToLFO2Freq                           = 7,
	Count                                     = 8,
	ESynthModEnvBiasPatch_MAX                 = 9,
};

enum class ESynthFilterType : uint8
{
	LowPass                                   = 0,
	HighPass                                  = 1,
	BandPass                                  = 2,
	BandStop                                  = 3,
	Count                                     = 4,
	ESynthFilterType_MAX                      = 5,
};

enum class ESynthFilterAlgorithm : uint8
{
	OnePole                                   = 0,
	StateVariable                             = 1,
	Ladder                                    = 2,
	Count                                     = 3,
	ESynthFilterAlgorithm_MAX                 = 4,
};

enum class ESynthStereoDelayMode : uint8
{
	Normal                                    = 0,
	Cross                                     = 1,
	PingPong                                  = 2,
	Count                                     = 3,
	ESynthStereoDelayMode_MAX                 = 4,
};

enum class ESynth1PatchSource : uint8
{
	LFO1                                      = 0,
	LFO2                                      = 1,
	Envelope                                  = 2,
	BiasEnvelope                              = 3,
	Count                                     = 4,
	ESynth1PatchSource_MAX                    = 5,
};

enum class ESynth1PatchDestination : uint8
{
	Osc1Gain                                  = 0,
	Osc1Frequency                             = 1,
	Osc1Pulsewidth                            = 2,
	Osc2Gain                                  = 3,
	Osc2Frequency                             = 4,
	Osc2Pulsewidth                            = 5,
	FilterFrequency                           = 6,
	FilterQ                                   = 7,
	Gain                                      = 8,
	Pan                                       = 9,
	LFO1Frequency                             = 10,
	LFO1Gain                                  = 11,
	LFO2Frequency                             = 12,
	LFO2Gain                                  = 13,
	Count                                     = 14,
	ESynth1PatchDestination_MAX               = 15,
};

enum class ESubmixEffectConvolutionReverbBlockSize : uint8
{
	BlockSize256                              = 0,
	BlockSize512                              = 1,
	BlockSize1024                             = 2,
	ESubmixEffectConvolutionReverbBlockSize_MAX = 3,
};

enum class ESourceEffectDynamicsProcessorType : uint8
{
	Compressor                                = 0,
	Limiter                                   = 1,
	Expander                                  = 2,
	Gate                                      = 3,
	UpwardsCompressor                         = 4,
	Count                                     = 5,
	ESourceEffectDynamicsProcessorType_MAX    = 6,
};

enum class ESourceEffectDynamicsPeakMode : uint8
{
	MeanSquared                               = 0,
	RootMeanSquared                           = 1,
	Peak                                      = 2,
	Count                                     = 3,
	ESourceEffectDynamicsPeakMode_MAX         = 4,
};

enum class EEnvelopeFollowerPeakMode : uint8
{
	MeanSquared                               = 0,
	RootMeanSquared                           = 1,
	Peak                                      = 2,
	Count                                     = 3,
	EEnvelopeFollowerPeakMode_MAX             = 4,
};

enum class ESourceEffectFilterCircuit : uint8
{
	OnePole                                   = 0,
	StateVariable                             = 1,
	Ladder                                    = 2,
	Count                                     = 3,
	ESourceEffectFilterCircuit_MAX            = 4,
};

enum class ESourceEffectFilterType : uint8
{
	LowPass                                   = 0,
	HighPass                                  = 1,
	BandPass                                  = 2,
	BandStop                                  = 3,
	Count                                     = 4,
	ESourceEffectFilterType_MAX               = 5,
};

enum class ESourceEffectFilterParam : uint8
{
	FilterFrequency                           = 0,
	FilterResonance                           = 1,
	Count                                     = 2,
	ESourceEffectFilterParam_MAX              = 3,
};

enum class EStereoChannelMode : uint8
{
	MidSide                                   = 0,
	LeftRight                                 = 1,
	count                                     = 2,
	EStereoChannelMode_MAX                    = 3,
};

enum class ESourceEffectMotionFilterModSource : uint8
{
	DistanceFromListener                      = 0,
	SpeedRelativeToListener                   = 1,
	SpeedOfSourceEmitter                      = 2,
	SpeedOfListener                           = 3,
	SpeedOfAngleDelta                         = 4,
	Count                                     = 5,
	ESourceEffectMotionFilterModSource_MAX    = 6,
};

enum class ESourceEffectMotionFilterModDestination : uint8
{
	FilterACutoffFrequency                    = 0,
	FilterAResonance                          = 1,
	FilterAOutputVolumeDB                     = 2,
	FilterBCutoffFrequency                    = 3,
	FilterBResonance                          = 4,
	FilterBOutputVolumeDB                     = 5,
	FilterMix                                 = 6,
	Count                                     = 7,
	ESourceEffectMotionFilterModDestination_MAX = 8,
};

enum class ESourceEffectMotionFilterTopology : uint8
{
	SerialMode                                = 0,
	ParallelMode                              = 1,
	Count                                     = 2,
	ESourceEffectMotionFilterTopology_MAX     = 3,
};

enum class ESourceEffectMotionFilterCircuit : uint8
{
	OnePole                                   = 0,
	StateVariable                             = 1,
	Ladder                                    = 2,
	Count                                     = 3,
	ESourceEffectMotionFilterCircuit_MAX      = 4,
};

enum class ESourceEffectMotionFilterType : uint8
{
	LowPass                                   = 0,
	HighPass                                  = 1,
	BandPass                                  = 2,
	BandStop                                  = 3,
	Count                                     = 4,
	ESourceEffectMotionFilterType_MAX         = 5,
};

enum class EPhaserLFOType : uint8
{
	Sine                                      = 0,
	UpSaw                                     = 1,
	DownSaw                                   = 2,
	Square                                    = 3,
	Triangle                                  = 4,
	Exponential                               = 5,
	RandomSampleHold                          = 6,
	Count                                     = 7,
	EPhaserLFOType_MAX                        = 8,
};

enum class ERingModulatorTypeSourceEffect : uint8
{
	Sine                                      = 0,
	Saw                                       = 1,
	Triangle                                  = 2,
	Square                                    = 3,
	Count                                     = 4,
	ERingModulatorTypeSourceEffect_MAX        = 5,
};

enum class EStereoDelaySourceEffect : uint8
{
	Normal                                    = 0,
	Cross                                     = 1,
	PingPong                                  = 2,
	Count                                     = 3,
	EStereoDelaySourceEffect_MAX              = 4,
};

enum class EStereoDelayFiltertype : uint8
{
	Lowpass                                   = 0,
	Highpass                                  = 1,
	Bandpass                                  = 2,
	Notch                                     = 3,
	Count                                     = 4,
	EStereoDelayFiltertype_MAX                = 5,
};

enum class ESubmixFilterType : uint8
{
	LowPass                                   = 0,
	HighPass                                  = 1,
	BandPass                                  = 2,
	BandStop                                  = 3,
	Count                                     = 4,
	ESubmixFilterType_MAX                     = 5,
};

enum class ESubmixFilterAlgorithm : uint8
{
	OnePole                                   = 0,
	StateVariable                             = 1,
	Ladder                                    = 2,
	Count                                     = 3,
	ESubmixFilterAlgorithm_MAX                = 4,
};

enum class ETapLineMode : uint8
{
	SendToChannel                             = 0,
	Panning                                   = 1,
	Disabled                                  = 2,
	ETapLineMode_MAX                          = 3,
};

enum class EGranularSynthEnvelopeType : uint8
{
	Rectangular                               = 0,
	Triangle                                  = 1,
	DownwardTriangle                          = 2,
	UpwardTriangle                            = 3,
	ExponentialDecay                          = 4,
	ExponentialIncrease                       = 5,
	Gaussian                                  = 6,
	Hanning                                   = 7,
	Lanczos                                   = 8,
	Cosine                                    = 9,
	CosineSquared                             = 10,
	Welch                                     = 11,
	Blackman                                  = 12,
	BlackmanHarris                            = 13,
	Count                                     = 14,
	EGranularSynthEnvelopeType_MAX            = 15,
};

enum class EGranularSynthSeekType : uint8
{
	FromBeginning                             = 0,
	FromCurrentPosition                       = 1,
	Count                                     = 2,
	EGranularSynthSeekType_MAX                = 3,
};

enum class ECurveInterpolationType : uint8
{
	AUTOINTERP                                = 0,
	LINEAR                                    = 1,
	CONSTANT                                  = 2,
	CurveInterpolationType_MAX                = 3,
};

enum class ESamplePlayerSeekType : uint8
{
	FromBeginning                             = 0,
	FromCurrentPosition                       = 1,
	FromEnd                                   = 2,
	Count                                     = 3,
	ESamplePlayerSeekType_MAX                 = 4,
};

enum class ESynthKnobSize : uint8
{
	Medium                                    = 0,
	Large                                     = 1,
	Count                                     = 2,
	ESynthKnobSize_MAX                        = 3,
};

enum class ESynthSlateSizeType : uint8
{
	Small                                     = 0,
	Medium                                    = 1,
	Large                                     = 2,
	Count                                     = 3,
	ESynthSlateSizeType_MAX                   = 4,
};

enum class ESynthSlateColorStyle : uint8
{
	Light                                     = 0,
	Dark                                      = 1,
	Count                                     = 2,
	ESynthSlateColorStyle_MAX                 = 3,
};

struct FSynth1PatchCable
{
public:
	float                                             Depth;
	enum class EESynth1PatchDestination               Destination;
	uint8                                             Pad_0[0x0003];
};

struct FPatchId
{
public:
	int32                                             Id;
};

struct FEpicSynth1Patch
{
public:
	enum class EESynth1PatchSource                    PatchSource;
	uint8                                             Pad_0[0x0007];
	TArray<struct FSynth1PatchCable>                  PatchCables;
};

struct FModularSynthPreset : public FTableRowBase
{
public:
	uint8                                             bEnablePolyphony : 1;
	uint8                                             BitPad_0 : 7;
	uint8                                             Pad_0[0x0003];
	enum class EESynth1OscType                        Osc1Type;
	uint8                                             Pad_1[0x0003];
	float                                             Osc1Gain;
	float                                             Osc1Octave;
	float                                             Osc1Semitones;
	float                                             Osc1Cents;
	float                                             Osc1PulseWidth;
	enum class EESynth1OscType                        Osc2Type;
	uint8                                             Pad_2[0x0003];
	float                                             Osc2Gain;
	float                                             Osc2Octave;
	float                                             Osc2Semitones;
	float                                             Osc2Cents;
	float                                             Osc2PulseWidth;
	float                                             Portamento;
	uint8                                             bEnableUnison : 1;
	uint8                                             bEnableOscillatorSync : 1;
	uint8                                             BitPad_1 : 6;
	uint8                                             Pad_3[0x0003];
	float                                             Spread;
	float                                             Pan;
	float                                             LFO1Frequency;
	float                                             LFO1Gain;
	enum class EESynthLFOType                         LFO1Type;
	enum class EESynthLFOMode                         LFO1Mode;
	enum class EESynthLFOPatchType                    LFO1PatchType;
	uint8                                             Pad_4[0x0001];
	float                                             LFO2Frequency;
	float                                             LFO2Gain;
	enum class EESynthLFOType                         LFO2Type;
	enum class EESynthLFOMode                         LFO2Mode;
	enum class EESynthLFOPatchType                    LFO2PatchType;
	uint8                                             Pad_5[0x0001];
	float                                             GainDb;
	float                                             AttackTime;
	float                                             DecayTime;
	float                                             SustainGain;
	float                                             ReleaseTime;
	enum class EESynthModEnvPatch                     ModEnvPatchType;
	enum class EESynthModEnvBiasPatch                 ModEnvBiasPatchType;
	uint8                                             Pad_6[0x0002];
	uint8                                             bInvertModulationEnvelope : 1;
	uint8                                             bInvertModulationEnvelopeBias : 1;
	uint8                                             BitPad_2 : 6;
	uint8                                             Pad_7[0x0003];
	float                                             ModulationEnvelopeDepth;
	float                                             ModulationEnvelopeAttackTime;
	float                                             ModulationEnvelopeDecayTime;
	float                                             ModulationEnvelopeSustainGain;
	float                                             ModulationEnvelopeReleaseTime;
	uint8                                             bLegato : 1;
	uint8                                             bRetrigger : 1;
	uint8                                             BitPad_3 : 6;
	uint8                                             Pad_8[0x0003];
	float                                             FilterFrequency;
	float                                             FilterQ;
	enum class EESynthFilterType                      FilterType;
	enum class EESynthFilterAlgorithm                 FilterAlgorithm;
	uint8                                             Pad_9[0x0002];
	uint8                                             bStereoDelayEnabled : 1;
	uint8                                             BitPad_4 : 7;
	uint8                                             Pad_A[0x0003];
	enum class EESynthStereoDelayMode                 StereoDelayMode;
	uint8                                             Pad_B[0x0003];
	float                                             StereoDelayTime;
	float                                             StereoDelayFeedback;
	float                                             StereoDelayWetlevel;
	float                                             StereoDelayRatio;
	uint8                                             bChorusEnabled : 1;
	uint8                                             BitPad_5 : 7;
	uint8                                             Pad_C[0x0003];
	float                                             ChorusDepth;
	float                                             ChorusFeedback;
	float                                             ChorusFrequency;
	uint8                                             Pad_D[0x0004];
	TArray<struct FEpicSynth1Patch>                   Patches;
};

struct FModularSynthPresetBankEntry
{
public:
	class FString                                     PresetName;
	struct FModularSynthPreset                        Preset;
};

struct FSourceEffectBitCrusherBaseSettings
{
public:
	float                                             SampleRate;
	float                                             BitDepth;
};

struct FSourceEffectBitCrusherSettings
{
public:
	float                                             CrushedSampleRate;
	uint8                                             Pad_0[0x0004];
	struct FSoundModulationDestinationSettings        SampleRateModulation;
	float                                             CrushedBits;
	uint8                                             Pad_1[0x0004];
	struct FSoundModulationDestinationSettings        BitModulation;
};

struct FSourceEffectChorusBaseSettings
{
public:
	float                                             Depth;
	float                                             Frequency;
	float                                             Feedback;
	float                                             WetLevel;
	float                                             DryLevel;
	float                                             Spread;
};

struct FSourceEffectChorusSettings
{
public:
	float                                             Depth;
	float                                             Frequency;
	float                                             Feedback;
	float                                             WetLevel;
	float                                             DryLevel;
	float                                             Spread;
	struct FSoundModulationDestinationSettings        DepthModulation;
	struct FSoundModulationDestinationSettings        FrequencyModulation;
	struct FSoundModulationDestinationSettings        FeedbackModulation;
	struct FSoundModulationDestinationSettings        WetModulation;
	struct FSoundModulationDestinationSettings        DryModulation;
	struct FSoundModulationDestinationSettings        SpreadModulation;
};

struct FSourceEffectConvolutionReverbSettings
{
public:
	float                                             NormalizationVolumeDb;
	float                                             WetVolumeDb;
	float                                             DryVolumeDb;
	bool                                              bBypass;
	uint8                                             Pad_0[0x0003];
};

struct FSourceEffectDynamicsProcessorSettings
{
public:
	enum class EESourceEffectDynamicsProcessorType    DynamicsProcessorType;
	enum class EESourceEffectDynamicsPeakMode         PeakMode;
	uint8                                             Pad_0[0x0002];
	float                                             LookAheadMsec;
	float                                             AttackTimeMsec;
	float                                             ReleaseTimeMsec;
	float                                             ThresholdDb;
	float                                             Ratio;
	float                                             KneeBandwidthDb;
	float                                             InputGainDb;
	float                                             OutputGainDb;
	uint8                                             bStereoLinked : 1;
	uint8                                             bAnalogMode : 1;
	uint8                                             BitPad_0 : 6;
	uint8                                             Pad_1[0x0003];
};

struct FSourceEffectEnvelopeFollowerSettings
{
public:
	float                                             AttackTime;
	float                                             ReleaseTime;
	enum class EEEnvelopeFollowerPeakMode             PeakMode;
	bool                                              bIsAnalogMode;
	uint8                                             Pad_0[0x0002];
};

struct FSourceEffectEQBand
{
public:
	float                                             Frequency;
	float                                             Bandwidth;
	float                                             GainDb;
	uint8                                             bEnabled : 1;
	uint8                                             BitPad_0 : 7;
	uint8                                             Pad_0[0x0003];
};

struct FSourceEffectEQSettings
{
public:
	TArray<struct FSourceEffectEQBand>                EQBands;
};

struct FSourceEffectFilterAudioBusModulationSettings
{
public:
	class UAudioBus*                                  AudioBus;
	int32                                             EnvelopeFollowerAttackTimeMsec;
	int32                                             EnvelopeFollowerReleaseTimeMsec;
	float                                             EnvelopeGainMultiplier;
	enum class EESourceEffectFilterParam              FilterParam;
	uint8                                             Pad_0[0x0003];
	float                                             MinFrequencyModulation;
	float                                             MaxFrequencyModulation;
	float                                             MinResonanceModulation;
	float                                             MaxResonanceModulation;
};

struct FSourceEffectFilterSettings
{
public:
	enum class EESourceEffectFilterCircuit            FilterCircuit;
	enum class EESourceEffectFilterType               FilterType;
	uint8                                             Pad_0[0x0002];
	float                                             CutoffFrequency;
	float                                             FilterQ;
	uint8                                             Pad_1[0x0004];
	TArray<struct FSourceEffectFilterAudioBusModulationSettings> AudioBusModulation;
};

struct FSourceEffectFoldbackDistortionSettings
{
public:
	float                                             InputGainDb;
	float                                             ThresholdDb;
	float                                             OutputGainDb;
};

struct FSourceEffectMidSideSpreaderSettings
{
public:
	float                                             SpreadAmount;
	enum class EEStereoChannelMode                    InputMode;
	enum class EEStereoChannelMode                    OutputMode;
	bool                                              bEqualPower;
	uint8                                             Pad_0[0x0001];
};

struct FSourceEffectIndividualFilterSettings
{
public:
	enum class EESourceEffectMotionFilterCircuit      FilterCircuit;
	enum class EESourceEffectMotionFilterType         FilterType;
	uint8                                             Pad_0[0x0002];
	float                                             CutoffFrequency;
	float                                             FilterQ;
};

struct FSourceEffectMotionFilterModulationSettings
{
public:
	enum class EESourceEffectMotionFilterModSource    ModulationSource;
	uint8                                             Pad_0[0x0007];
	struct FVector2D                                  ModulationInputRange;
	struct FVector2D                                  ModulationOutputMinimumRange;
	struct FVector2D                                  ModulationOutputMaximumRange;
	float                                             UpdateEaseMS;
	uint8                                             Pad_1[0x0004];
};

struct FSourceEffectMotionFilterSettings
{
public:
	enum class EESourceEffectMotionFilterTopology     MotionFilterTopology;
	uint8                                             Pad_0[0x0003];
	float                                             MotionFilterMix;
	struct FSourceEffectIndividualFilterSettings      FilterASettings;
	struct FSourceEffectIndividualFilterSettings      FilterBSettings;
	TMap<enum class EESourceEffectMotionFilterModDestination, struct FSourceEffectMotionFilterModulationSettings> ModulationMappings;
	float                                             DryVolumeDb;
	uint8                                             Pad_1[0x0004];
};

struct FSourceEffectPannerSettings
{
public:
	float                                             Spread;
	float                                             Pan;
};

struct FSourceEffectPhaserSettings
{
public:
	float                                             WetLevel;
	float                                             Frequency;
	float                                             Feedback;
	enum class EEPhaserLFOType                        LFOType;
	bool                                              UseQuadraturePhase;
	uint8                                             Pad_0[0x0002];
};

struct FSourceEffectRingModulationSettings
{
public:
	enum class EERingModulatorTypeSourceEffect        ModulatorType;
	uint8                                             Pad_0[0x0003];
	float                                             Frequency;
	float                                             Depth;
	float                                             DryLevel;
	float                                             WetLevel;
	uint8                                             Pad_1[0x0004];
	class UAudioBus*                                  AudioBusModulator;
};

struct FSourceEffectSimpleDelaySettings
{
public:
	float                                             SpeedOfSound;
	float                                             DelayAmount;
	float                                             DryAmount;
	float                                             WetAmount;
	float                                             Feedback;
	uint8                                             bDelayBasedOnDistance : 1;
	uint8                                             bUseDistanceOverride : 1;
	uint8                                             BitPad_0 : 6;
	uint8                                             Pad_0[0x0003];
};

struct FSourceEffectStereoDelaySettings
{
public:
	enum class EEStereoDelaySourceEffect              DelayMode;
	uint8                                             Pad_0[0x0003];
	float                                             DelayTimeMsec;
	float                                             Feedback;
	float                                             DelayRatio;
	float                                             WetLevel;
	float                                             DryLevel;
	bool                                              bFilterEnabled;
	enum class EEStereoDelayFiltertype                FilterType;
	uint8                                             Pad_1[0x0002];
	float                                             FilterFrequency;
	float                                             FilterQ;
};

struct FSourceEffectWaveShaperSettings
{
public:
	float                                             Amount;
	float                                             OutputGainDb;
};

struct FSubmixEffectConvolutionReverbSettings
{
public:
	float                                             NormalizationVolumeDb;
	float                                             WetVolumeDb;
	float                                             DryVolumeDb;
	bool                                              bBypass;
	bool                                              bMixInputChannelFormatToImpulseResponseFormat;
	bool                                              bMixReverbOutputToOutputChannelFormat;
	uint8                                             Pad_0[0x0001];
	float                                             SurroundRearChannelBleedDb;
	bool                                              bInvertRearChannelBleedPhase;
	bool                                              bSurroundRearChannelFlip;
	uint8                                             Pad_1[0x0002];
	float                                             SurroundRearChannelBleedAmount;
	uint8                                             Pad_2[0x0004];
	class UAudioImpulseResponse*                      ImpulseResponse;
	bool                                              AllowHardwareAcceleration;
	uint8                                             Pad_3[0x0007];
};

struct FSubmixEffectDelaySettings
{
public:
	float                                             MaximumDelayLength;
	float                                             InterpolationTime;
	float                                             DelayLength;
};

struct FSubmixEffectFilterSettings
{
public:
	enum class EESubmixFilterType                     FilterType;
	enum class EESubmixFilterAlgorithm                FilterAlgorithm;
	uint8                                             Pad_0[0x0002];
	float                                             FilterFrequency;
	float                                             FilterQ;
};

struct FSubmixEffectFlexiverbSettings
{
public:
	float                                             PreDelay;
	float                                             DecayTime;
	float                                             RoomDampening;
	int32                                             Complexity;
};

struct FDynamicsBandSettings
{
public:
	float                                             CrossoverTopFrequency;
	float                                             AttackTimeMsec;
	float                                             ReleaseTimeMsec;
	float                                             ThresholdDb;
	float                                             Ratio;
	float                                             KneeBandwidthDb;
	float                                             InputGainDb;
	float                                             OutputGainDb;
};

struct FSubmixEffectMultibandCompressorSettings
{
public:
	enum class EESubmixEffectDynamicsProcessorType    DynamicsProcessorType;
	enum class EESubmixEffectDynamicsPeakMode         PeakMode;
	enum class EESubmixEffectDynamicsChannelLinkMode  LinkMode;
	uint8                                             Pad_0[0x0001];
	float                                             LookAheadMsec;
	bool                                              bAnalogMode;
	bool                                              bFourPole;
	bool                                              bBypass;
	enum class EESubmixEffectDynamicsKeySource        KeySource;
	uint8                                             Pad_1[0x0004];
	class UAudioBus*                                  ExternalAudioBus;
	class USoundSubmix*                               ExternalSubmix;
	float                                             KeyGainDb;
	bool                                              bKeyAudition;
	uint8                                             Pad_2[0x0003];
	TArray<struct FDynamicsBandSettings>              Bands;
};

struct FSubmixEffectStereoDelaySettings
{
public:
	enum class EEStereoDelaySourceEffect              DelayMode;
	uint8                                             Pad_0[0x0003];
	float                                             DelayTimeMsec;
	float                                             Feedback;
	float                                             DelayRatio;
	float                                             WetLevel;
	float                                             DryLevel;
	bool                                              bFilterEnabled;
	enum class EEStereoDelayFiltertype                FilterType;
	uint8                                             Pad_1[0x0002];
	float                                             FilterFrequency;
	float                                             FilterQ;
};

struct FSubmixEffectStereoToQuadSettings
{
public:
	bool                                              bFlipChannels;
	uint8                                             Pad_0[0x0003];
	float                                             RearChannelGain;
};

struct FTapDelayInfo
{
public:
	enum class EETapLineMode                          TapLineMode;
	uint8                                             Pad_0[0x0003];
	float                                             DelayLength;
	float                                             Gain;
	int32                                             OutputChannel;
	float                                             PanInDegrees;
	int32                                             TapId;
};

struct FSubmixEffectTapDelaySettings
{
public:
	float                                             MaximumDelayLength;
	float                                             InterpolationTime;
	TArray<struct FTapDelayInfo>                      Taps;
};

struct FSynth2DSliderStyle : public FSlateWidgetStyle
{
public:
	uint8                                             Pad_0[0x0008];
	struct FSlateBrush                                NormalThumbImage;
	struct FSlateBrush                                DisabledThumbImage;
	struct FSlateBrush                                NormalBarImage;
	struct FSlateBrush                                DisabledBarImage;
	struct FSlateBrush                                BackgroundImage;
	float                                             BarThickness;
	uint8                                             Pad_1[0x000C];
};

struct FSynthKnobStyle : public FSlateWidgetStyle
{
public:
	uint8                                             Pad_0[0x0008];
	struct FSlateBrush                                LargeKnob;
	struct FSlateBrush                                LargeKnobOverlay;
	struct FSlateBrush                                MediumKnob;
	struct FSlateBrush                                MediumKnobOverlay;
	float                                             MinValueAngle;
	float                                             MaxValueAngle;
	enum class EESynthKnobSize                        KnobSize;
	uint8                                             Pad_1[0x0007];
};

struct FSynthSlateStyle : public FSlateWidgetStyle
{
public:
	enum class EESynthSlateSizeType                   SizeType;
	enum class EESynthSlateColorStyle                 ColorStyle;
	uint8                                             Pad_0[0x0006];
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
