#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class UTemplateSequence : public UMovieSceneSequence
{
public:
	class UMovieScene*                                MovieScene;
	TSoftClassPtr<class AActor>                       BoundActorClass;
	TMap<struct FGuid, class FName>                   BoundActorComponents;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("TemplateSequence");
		return Clss;
	}
};

class UCameraAnimationSequence : public UTemplateSequence
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("CameraAnimationSequence");
		return Clss;
	}
};

class UCameraAnimationSequenceCameraStandIn : public UObject
{
public:
	float                                             FieldOfView;
	uint8                                             bConstrainAspectRatio : 1;
	uint8                                             BitPad_0 : 7;
	uint8                                             Pad_0[0x0003];
	float                                             AspectRatio;
	uint8                                             Pad_1[0x0004];
	struct FPostProcessSettings                       PostProcessSettings;
	float                                             PostProcessBlendWeight;
	struct FCameraFilmbackSettings                    Filmback;
	struct FCameraLensSettings                        LensSettings;
	uint8                                             Pad_2[0x0004];
	struct FCameraFocusSettings                       FocusSettings;
	float                                             CurrentFocalLength;
	float                                             CurrentAperture;
	float                                             CurrentFocusDistance;
	uint8                                             Pad_3[0x007C];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("CameraAnimationSequenceCameraStandIn");
		return Clss;
	}
};

class UCameraAnimationSequencePlayer : public UObject
{
public:
	uint8                                             Pad_0[0x0270];
	class UObject*                                    BoundObjectOverride;
	class UMovieSceneSequence*                        Sequence;
	struct FMovieSceneRootEvaluationTemplateInstance  RootTemplateInstance;
	uint8                                             Pad_1[0x0068];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("CameraAnimationSequencePlayer");
		return Clss;
	}
};

class UCameraAnimationSpawnableSystem : public UMovieSceneEntitySystem
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("CameraAnimationSpawnableSystem");
		return Clss;
	}
};

class UCameraAnimationBoundObjectInstantiator : public UMovieSceneEntityInstantiatorSystem
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("CameraAnimationBoundObjectInstantiator");
		return Clss;
	}
};

class UCameraAnimationEntitySystemLinker : public UMovieSceneEntitySystemLinker
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("CameraAnimationEntitySystemLinker");
		return Clss;
	}
};

class UCameraAnimationSequenceSubsystem : public UWorldSubsystem
{
public:
	class UMovieSceneEntitySystemLinker*              Linker;
	uint8                                             Pad_0[0x0010];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("CameraAnimationSequenceSubsystem");
		return Clss;
	}
};

class UTemplateSequenceSection : public UMovieSceneSubSection
{
public:
	TArray<struct FTemplateSectionPropertyScale>      PropertyScales;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("TemplateSequenceSection");
		return Clss;
	}
};

class USequenceCameraShakePattern : public UCameraShakePattern
{
public:
	class UCameraAnimationSequence*                   Sequence;
	float                                             PlayRate;
	float                                             Scale;
	float                                             BlendInTime;
	float                                             BlendOutTime;
	float                                             RandomSegmentDuration;
	bool                                              bRandomSegment;
	uint8                                             Pad_0[0x0003];
	class UCameraAnimationSequencePlayer*             Player;
	class UCameraAnimationSequenceCameraStandIn*      CameraStandIn;
	uint8                                             Pad_1[0x0020];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("SequenceCameraShakePattern");
		return Clss;
	}
};

class UTemplateSequenceSystem : public UMovieSceneEntitySystem
{
public:
	uint8                                             Pad_0[0x0070];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("TemplateSequenceSystem");
		return Clss;
	}
};

class UTemplateSequencePropertyScalingInstantiatorSystem : public UMovieSceneEntitySystem
{
public:
	uint8                                             Pad_0[0x0058];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("TemplateSequencePropertyScalingInstantiatorSystem");
		return Clss;
	}
};

class UTemplateSequencePropertyScalingEvaluatorSystem : public UMovieSceneEntitySystem
{
public:
	uint8                                             Pad_0[0x0050];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("TemplateSequencePropertyScalingEvaluatorSystem");
		return Clss;
	}
};

class ATemplateSequenceActor : public AActor
{
public:
	uint8                                             Pad_0[0x0008];
	struct FMovieSceneSequencePlaybackSettings        PlaybackSettings;
	class UTemplateSequencePlayer*                    SequencePlayer;
	struct FSoftObjectPath                            TemplateSequence;
	struct FTemplateSequenceBindingOverrideData       BindingOverride;
	uint8                                             Pad_1[0x0004];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("TemplateSequenceActor");
		return Clss;
	}

	void SetSequence(class UTemplateSequence* InSequence);
	void SetBinding(class AActor* Actor, bool bOverridesDefault);
	class UTemplateSequence* LoadSequence();
	class UTemplateSequencePlayer* GetSequencePlayer();
	class UTemplateSequence* GetSequence();
};

class UTemplateSequencePlayer : public UMovieSceneSequencePlayer
{
public:
	uint8                                             Pad_0[0x0008];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("TemplateSequencePlayer");
		return Clss;
	}

	static class UTemplateSequencePlayer* CreateTemplateSequencePlayer(class UObject* WorldContextObject, class UTemplateSequence* TemplateSequence, const struct FMovieSceneSequencePlaybackSettings& Settings, class ATemplateSequenceActor** OutActor);
};

class USequenceCameraShakeTestUtil : public UBlueprintFunctionLibrary
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("SequenceCameraShakeTestUtil");
		return Clss;
	}

	static bool GetPostProcessBlendCache(class APlayerController* PlayerController, int32 PPIndex, struct FPostProcessSettings* OutPPSettings, float* OutPPBlendWeight);
	static struct FMinimalViewInfo GetLastFrameCameraCachePOV(class APlayerController* PlayerController);
	static struct FMinimalViewInfo GetCameraCachePOV(class APlayerController* PlayerController);
};

class UTemplateSequenceTrack : public UMovieSceneSubTrack
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("TemplateSequenceTrack");
		return Clss;
	}
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
