// generated by beardumper

#include "../SDK.hpp"

namespace SDK
{

struct FFrameTime UTimeManagementBlueprintLibrary::TransformTime(struct FFrameTime* SourceTime, struct FFrameRate* SourceRate, struct FFrameRate* DestinationRate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("TimeManagementBlueprintLibrary", "TransformTime");

	Params::UTimeManagementBlueprintLibrary_TransformTime Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (SourceTime != nullptr)
		*SourceTime = Parms.SourceTime;
	if (SourceRate != nullptr)
		*SourceRate = Parms.SourceRate;
	if (DestinationRate != nullptr)
		*DestinationRate = Parms.DestinationRate;

	return Parms.ReturnValue;
}

struct FFrameNumber UTimeManagementBlueprintLibrary::Subtract_FrameNumberInteger(const struct FFrameNumber& A, int32 B)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("TimeManagementBlueprintLibrary", "Subtract_FrameNumberInteger");

	Params::UTimeManagementBlueprintLibrary_Subtract_FrameNumberInteger Parms{};
	Parms.A = A;
	Parms.B = B;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

struct FFrameNumber UTimeManagementBlueprintLibrary::Subtract_FrameNumberFrameNumber(const struct FFrameNumber& A, const struct FFrameNumber& B)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("TimeManagementBlueprintLibrary", "Subtract_FrameNumberFrameNumber");

	Params::UTimeManagementBlueprintLibrary_Subtract_FrameNumberFrameNumber Parms{};
	Parms.A = A;
	Parms.B = B;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

struct FFrameTime UTimeManagementBlueprintLibrary::SnapFrameTimeToRate(struct FFrameTime* SourceTime, struct FFrameRate* SourceRate, struct FFrameRate* SnapToRate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("TimeManagementBlueprintLibrary", "SnapFrameTimeToRate");

	Params::UTimeManagementBlueprintLibrary_SnapFrameTimeToRate Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (SourceTime != nullptr)
		*SourceTime = Parms.SourceTime;
	if (SourceRate != nullptr)
		*SourceRate = Parms.SourceRate;
	if (SnapToRate != nullptr)
		*SnapToRate = Parms.SnapToRate;

	return Parms.ReturnValue;
}

struct FFrameTime UTimeManagementBlueprintLibrary::Multiply_SecondsFrameRate(float TimeInSeconds, struct FFrameRate* FrameRate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("TimeManagementBlueprintLibrary", "Multiply_SecondsFrameRate");

	Params::UTimeManagementBlueprintLibrary_Multiply_SecondsFrameRate Parms{};
	Parms.TimeInSeconds = TimeInSeconds;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (FrameRate != nullptr)
		*FrameRate = Parms.FrameRate;

	return Parms.ReturnValue;
}

struct FFrameNumber UTimeManagementBlueprintLibrary::Multiply_FrameNumberInteger(const struct FFrameNumber& A, int32 B)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("TimeManagementBlueprintLibrary", "Multiply_FrameNumberInteger");

	Params::UTimeManagementBlueprintLibrary_Multiply_FrameNumberInteger Parms{};
	Parms.A = A;
	Parms.B = B;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

bool UTimeManagementBlueprintLibrary::IsValid_MultipleOf(struct FFrameRate* InFrameRate, struct FFrameRate* OtherFramerate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("TimeManagementBlueprintLibrary", "IsValid_MultipleOf");

	Params::UTimeManagementBlueprintLibrary_IsValid_MultipleOf Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (InFrameRate != nullptr)
		*InFrameRate = Parms.InFrameRate;
	if (OtherFramerate != nullptr)
		*OtherFramerate = Parms.OtherFramerate;

	return Parms.ReturnValue;
}

bool UTimeManagementBlueprintLibrary::IsValid_Framerate(struct FFrameRate* InFrameRate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("TimeManagementBlueprintLibrary", "IsValid_Framerate");

	Params::UTimeManagementBlueprintLibrary_IsValid_Framerate Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (InFrameRate != nullptr)
		*InFrameRate = Parms.InFrameRate;

	return Parms.ReturnValue;
}

struct FFrameRate UTimeManagementBlueprintLibrary::GetTimecodeFrameRate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("TimeManagementBlueprintLibrary", "GetTimecodeFrameRate");

	Params::UTimeManagementBlueprintLibrary_GetTimecodeFrameRate Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

struct FTimecode UTimeManagementBlueprintLibrary::GetTimecode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("TimeManagementBlueprintLibrary", "GetTimecode");

	Params::UTimeManagementBlueprintLibrary_GetTimecode Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

struct FFrameNumber UTimeManagementBlueprintLibrary::Divide_FrameNumberInteger(const struct FFrameNumber& A, int32 B)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("TimeManagementBlueprintLibrary", "Divide_FrameNumberInteger");

	Params::UTimeManagementBlueprintLibrary_Divide_FrameNumberInteger Parms{};
	Parms.A = A;
	Parms.B = B;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

class FString UTimeManagementBlueprintLibrary::Conv_TimecodeToString(struct FTimecode* InTimecode, bool bForceSignDisplay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("TimeManagementBlueprintLibrary", "Conv_TimecodeToString");

	Params::UTimeManagementBlueprintLibrary_Conv_TimecodeToString Parms{};
	Parms.bForceSignDisplay = bForceSignDisplay;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (InTimecode != nullptr)
		*InTimecode = Parms.InTimecode;

	return Parms.ReturnValue;
}

float UTimeManagementBlueprintLibrary::Conv_QualifiedFrameTimeToSeconds(struct FQualifiedFrameTime* InFrameTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("TimeManagementBlueprintLibrary", "Conv_QualifiedFrameTimeToSeconds");

	Params::UTimeManagementBlueprintLibrary_Conv_QualifiedFrameTimeToSeconds Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (InFrameTime != nullptr)
		*InFrameTime = Parms.InFrameTime;

	return Parms.ReturnValue;
}

float UTimeManagementBlueprintLibrary::Conv_FrameRateToSeconds(struct FFrameRate* InFrameRate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("TimeManagementBlueprintLibrary", "Conv_FrameRateToSeconds");

	Params::UTimeManagementBlueprintLibrary_Conv_FrameRateToSeconds Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (InFrameRate != nullptr)
		*InFrameRate = Parms.InFrameRate;

	return Parms.ReturnValue;
}

float UTimeManagementBlueprintLibrary::Conv_FrameRateToInterval(const struct FFrameRate& InFrameRate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("TimeManagementBlueprintLibrary", "Conv_FrameRateToInterval");

	Params::UTimeManagementBlueprintLibrary_Conv_FrameRateToInterval Parms{};
	Parms.InFrameRate = InFrameRate;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

int32 UTimeManagementBlueprintLibrary::Conv_FrameNumberToInteger(struct FFrameNumber* InFrameNumber)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("TimeManagementBlueprintLibrary", "Conv_FrameNumberToInteger");

	Params::UTimeManagementBlueprintLibrary_Conv_FrameNumberToInteger Parms{};

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	if (InFrameNumber != nullptr)
		*InFrameNumber = Parms.InFrameNumber;

	return Parms.ReturnValue;
}

struct FFrameNumber UTimeManagementBlueprintLibrary::Add_FrameNumberInteger(const struct FFrameNumber& A, int32 B)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("TimeManagementBlueprintLibrary", "Add_FrameNumberInteger");

	Params::UTimeManagementBlueprintLibrary_Add_FrameNumberInteger Parms{};
	Parms.A = A;
	Parms.B = B;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

struct FFrameNumber UTimeManagementBlueprintLibrary::Add_FrameNumberFrameNumber(const struct FFrameNumber& A, const struct FFrameNumber& B)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = SDK::Rt::FindFunction("TimeManagementBlueprintLibrary", "Add_FrameNumberFrameNumber");

	Params::UTimeManagementBlueprintLibrary_Add_FrameNumberFrameNumber Parms{};
	Parms.A = A;
	Parms.B = B;

	SDK::Rt::ProcessEvent(this, Func, &Parms);

	return Parms.ReturnValue;
}

}
