#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

namespace Params
{

struct UTraceUtilLibrary_TraceMarkRegionStart final
{
public:
	class FString                                     Name;
};

struct UTraceUtilLibrary_TraceMarkRegionEnd final
{
public:
	class FString                                     Name;
};

struct UTraceUtilLibrary_TraceBookmark final
{
public:
	class FString                                     Name;
};

struct UTraceUtilLibrary_ToggleChannel final
{
public:
	class FString                                     ChannelName;
	bool                                              enabled;
	bool                                              ReturnValue;
};

struct UTraceUtilLibrary_StopTracing final
{
public:
	bool                                              ReturnValue;
};

struct UTraceUtilLibrary_StartTraceToFile final
{
public:
	class FString                                     FileName;
	TArray<class FString>                             Channels;
	bool                                              ReturnValue;
};

struct UTraceUtilLibrary_StartTraceSendTo final
{
public:
	class FString                                     Target;
	TArray<class FString>                             Channels;
	bool                                              ReturnValue;
};

struct UTraceUtilLibrary_ResumeTracing final
{
public:
	bool                                              ReturnValue;
};

struct UTraceUtilLibrary_PauseTracing final
{
public:
	bool                                              ReturnValue;
};

struct UTraceUtilLibrary_IsTracing final
{
public:
	bool                                              ReturnValue;
};

struct UTraceUtilLibrary_IsChannelEnabled final
{
public:
	class FString                                     ChannelName;
	bool                                              ReturnValue;
};

struct UTraceUtilLibrary_GetEnabledChannels final
{
public:
	TArray<class FString>                             ReturnValue;
};

struct UTraceUtilLibrary_GetAllChannels final
{
public:
	TArray<class FString>                             ReturnValue;
};

}
}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
