#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

namespace Params
{

struct UTypedElementSelectionSetLibrary_SetSelectionFromList final
{
public:
	class UTypedElementSelectionSet*                  SelectionSet;
	struct FScriptTypedElementListProxy               ElementList;
	struct FTypedElementSelectionOptions              SelectionOptions;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionSetLibrary_SelectElementsFromList final
{
public:
	class UTypedElementSelectionSet*                  SelectionSet;
	struct FScriptTypedElementListProxy               ElementList;
	struct FTypedElementSelectionOptions              SelectionOptions;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionSetLibrary_GetNormalizedSelection final
{
public:
	class UTypedElementSelectionSet*                  SelectionSet;
	struct FTypedElementSelectionNormalizationOptions NormalizationOptions;
	struct FScriptTypedElementListProxy               ReturnValue;
};

struct UTypedElementSelectionSetLibrary_GetNormalizedElementList final
{
public:
	class UTypedElementSelectionSet*                  SelectionSet;
	struct FScriptTypedElementListProxy               ElementList;
	struct FTypedElementSelectionNormalizationOptions NormalizationOptions;
	struct FScriptTypedElementListProxy               ReturnValue;
};

struct UTypedElementSelectionSetLibrary_DeselectElementsFromList final
{
public:
	class UTypedElementSelectionSet*                  SelectionSet;
	struct FScriptTypedElementListProxy               ElementList;
	struct FTypedElementSelectionOptions              SelectionOptions;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionSet_SetSelection final
{
public:
	TArray<struct FScriptTypedElementHandle>          InElementHandles;
	struct FTypedElementSelectionOptions              InSelectionOptions;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionSet_SelectElements final
{
public:
	TArray<struct FScriptTypedElementHandle>          InElementHandles;
	struct FTypedElementSelectionOptions              InSelectionOptions;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionSet_SelectElement final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	struct FTypedElementSelectionOptions              InSelectionOptions;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionSet_RestoreSelectionState final
{
public:
	struct FTypedElementSelectionSetState             InSelectionState;
};

struct UTypedElementSelectionSet_K2_GetSelectedElementHandles final
{
public:
	class UClass*                                     InBaseInterfaceType;
	TArray<struct FScriptTypedElementHandle>          ReturnValue;
};

struct UTypedElementSelectionSet_IsElementSelected final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	struct FTypedElementIsSelectedOptions             InSelectionOptions;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionSet_HasSelectedObjects final
{
public:
	class UClass*                                     InRequiredClass;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionSet_HasSelectedElements final
{
public:
	class UClass*                                     InBaseInterfaceType;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionSet_GetTopSelectedObject final
{
public:
	class UClass*                                     InRequiredClass;
	class UObject*                                    ReturnValue;
};

struct UTypedElementSelectionSet_GetSelectionElement final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	enum class EETypedElementSelectionMethod          InSelectionMethod;
	struct FScriptTypedElementHandle                  ReturnValue;
};

struct UTypedElementSelectionSet_GetSelectedObjects final
{
public:
	class UClass*                                     InRequiredClass;
	TArray<class UObject*>                            ReturnValue;
};

struct UTypedElementSelectionSet_GetNumSelectedElements final
{
public:
	int32                                             ReturnValue;
};

struct UTypedElementSelectionSet_GetCurrentSelectionState final
{
public:
	struct FTypedElementSelectionSetState             ReturnValue;
};

struct UTypedElementSelectionSet_GetBottomSelectedObject final
{
public:
	class UClass*                                     InRequiredClass;
	class UObject*                                    ReturnValue;
};

struct UTypedElementSelectionSet_DeselectElements final
{
public:
	TArray<struct FScriptTypedElementHandle>          InElementHandles;
	struct FTypedElementSelectionOptions              InSelectionOptions;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionSet_DeselectElement final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	struct FTypedElementSelectionOptions              InSelectionOptions;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionSet_CountSelectedObjects final
{
public:
	class UClass*                                     InRequiredClass;
	int32                                             ReturnValue;
};

struct UTypedElementSelectionSet_CountSelectedElements final
{
public:
	class UClass*                                     InBaseInterfaceType;
	int32                                             ReturnValue;
};

struct UTypedElementSelectionSet_ClearSelection final
{
public:
	struct FTypedElementSelectionOptions              InSelectionOptions;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionSet_CanSelectElement final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	struct FTypedElementSelectionOptions              InSelectionOptions;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionSet_CanDeselectElement final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	struct FTypedElementSelectionOptions              InSelectionOptions;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionSet_AllowSelectionModifiers final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	bool                                              ReturnValue;
};

struct UTypedElementAssetDataInterface_GetAssetData final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	struct FAssetData                                 ReturnValue;
};

struct UTypedElementAssetDataInterface_GetAllReferencedAssetDatas final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	TArray<struct FAssetData>                         ReturnValue;
};

struct UTypedElementHierarchyInterface_GetParentElement final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	bool                                              bAllowCreate;
	struct FScriptTypedElementHandle                  ReturnValue;
};

struct UTypedElementHierarchyInterface_GetChildElements final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	TArray<struct FScriptTypedElementHandle>          OutElementHandles;
	bool                                              bAllowCreate;
};

struct UTypedElementObjectInterface_GetObjectClass final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	class UClass*                                     ReturnValue;
};

struct UTypedElementObjectInterface_GetObject final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	class UObject*                                    ReturnValue;
};

struct UTypedElementPrimitiveCustomDataInterface_SetCustomDataValue final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	int32                                             CustomDataIndex;
	float                                             CustomDataValue;
	bool                                              bMarkRenderStateDirty;
};

struct UTypedElementPrimitiveCustomDataInterface_SetCustomData final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	TArray<float>                                     CustomDataFloats;
	bool                                              bMarkRenderStateDirty;
};

struct UTypedElementSelectionInterface_SelectElement final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	struct FScriptTypedElementListProxy               InSelectionSet;
	struct FTypedElementSelectionOptions              InSelectionOptions;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionInterface_IsElementSelected final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	struct FScriptTypedElementListProxy               InSelectionSet;
	struct FTypedElementIsSelectedOptions             InSelectionOptions;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionInterface_GetSelectionElement final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	struct FScriptTypedElementListProxy               InCurrentSelection;
	enum class EETypedElementSelectionMethod          InSelectionMethod;
	struct FScriptTypedElementHandle                  ReturnValue;
};

struct UTypedElementSelectionInterface_DeselectElement final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	struct FScriptTypedElementListProxy               InSelectionSet;
	struct FTypedElementSelectionOptions              InSelectionOptions;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionInterface_CanSelectElement final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	struct FTypedElementSelectionOptions              InSelectionOptions;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionInterface_CanDeselectElement final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	struct FTypedElementSelectionOptions              InSelectionOptions;
	bool                                              ReturnValue;
};

struct UTypedElementSelectionInterface_AllowSelectionModifiers final
{
public:
	struct FScriptTypedElementHandle                  InElementHandle;
	struct FScriptTypedElementListProxy               InSelectionSet;
	bool                                              ReturnValue;
};

}
}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
