#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class UTypedElementSelectionSetLibrary : public UObject
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("TypedElementSelectionSetLibrary");
		return Clss;
	}

	static bool SetSelectionFromList(class UTypedElementSelectionSet* SelectionSet, const struct FScriptTypedElementListProxy& ElementList, const struct FTypedElementSelectionOptions& SelectionOptions);
	static bool SelectElementsFromList(class UTypedElementSelectionSet* SelectionSet, const struct FScriptTypedElementListProxy& ElementList, const struct FTypedElementSelectionOptions& SelectionOptions);
	static struct FScriptTypedElementListProxy GetNormalizedSelection(class UTypedElementSelectionSet* SelectionSet, const struct FTypedElementSelectionNormalizationOptions& NormalizationOptions);
	static struct FScriptTypedElementListProxy GetNormalizedElementList(class UTypedElementSelectionSet* SelectionSet, const struct FScriptTypedElementListProxy& ElementList, const struct FTypedElementSelectionNormalizationOptions& NormalizationOptions);
	static bool DeselectElementsFromList(class UTypedElementSelectionSet* SelectionSet, const struct FScriptTypedElementListProxy& ElementList, const struct FTypedElementSelectionOptions& SelectionOptions);
};

class UTypedElementSelectionSet : public UObject
{
public:
	uint8                                             Pad_0[0x0800];
	struct FMulticastInlineDelegateProperty_          OnPreSelectionChange;
	struct FMulticastInlineDelegateProperty_          OnSelectionChange;
	uint8                                             Pad_1[0x0050];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("TypedElementSelectionSet");
		return Clss;
	}

	bool SetSelection(TArray<struct FScriptTypedElementHandle>* InElementHandles, const struct FTypedElementSelectionOptions& InSelectionOptions);
	bool SelectElements(TArray<struct FScriptTypedElementHandle>* InElementHandles, const struct FTypedElementSelectionOptions& InSelectionOptions);
	bool SelectElement(struct FScriptTypedElementHandle* InElementHandle, const struct FTypedElementSelectionOptions& InSelectionOptions);
	void RestoreSelectionState(struct FTypedElementSelectionSetState* InSelectionState);
	TArray<struct FScriptTypedElementHandle> K2_GetSelectedElementHandles(class UClass* InBaseInterfaceType);
	bool IsElementSelected(struct FScriptTypedElementHandle* InElementHandle, const struct FTypedElementIsSelectedOptions& InSelectionOptions);
	bool HasSelectedObjects(class UClass* InRequiredClass);
	bool HasSelectedElements(class UClass* InBaseInterfaceType);
	class UObject* GetTopSelectedObject(class UClass* InRequiredClass);
	struct FScriptTypedElementHandle GetSelectionElement(struct FScriptTypedElementHandle* InElementHandle, enum class EETypedElementSelectionMethod InSelectionMethod);
	TArray<class UObject*> GetSelectedObjects(class UClass* InRequiredClass);
	int32 GetNumSelectedElements();
	struct FTypedElementSelectionSetState GetCurrentSelectionState();
	class UObject* GetBottomSelectedObject(class UClass* InRequiredClass);
	bool DeselectElements(TArray<struct FScriptTypedElementHandle>* InElementHandles, const struct FTypedElementSelectionOptions& InSelectionOptions);
	bool DeselectElement(struct FScriptTypedElementHandle* InElementHandle, const struct FTypedElementSelectionOptions& InSelectionOptions);
	int32 CountSelectedObjects(class UClass* InRequiredClass);
	int32 CountSelectedElements(class UClass* InBaseInterfaceType);
	bool ClearSelection(const struct FTypedElementSelectionOptions& InSelectionOptions);
	bool CanSelectElement(struct FScriptTypedElementHandle* InElementHandle, const struct FTypedElementSelectionOptions& InSelectionOptions);
	bool CanDeselectElement(struct FScriptTypedElementHandle* InElementHandle, const struct FTypedElementSelectionOptions& InSelectionOptions);
	bool AllowSelectionModifiers(struct FScriptTypedElementHandle* InElementHandle);
};

class UTypedElementAssetDataInterface : public UInterface
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("TypedElementAssetDataInterface");
		return Clss;
	}

	struct FAssetData GetAssetData(struct FScriptTypedElementHandle* InElementHandle);
	TArray<struct FAssetData> GetAllReferencedAssetDatas(struct FScriptTypedElementHandle* InElementHandle);
};

class UTypedElementHierarchyInterface : public UInterface
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("TypedElementHierarchyInterface");
		return Clss;
	}

	struct FScriptTypedElementHandle GetParentElement(struct FScriptTypedElementHandle* InElementHandle, bool bAllowCreate);
	void GetChildElements(struct FScriptTypedElementHandle* InElementHandle, TArray<struct FScriptTypedElementHandle>* OutElementHandles, bool bAllowCreate);
};

class UTypedElementObjectInterface : public UInterface
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("TypedElementObjectInterface");
		return Clss;
	}

	class UClass* GetObjectClass(struct FScriptTypedElementHandle* InElementHandle);
	class UObject* GetObject(struct FScriptTypedElementHandle* InElementHandle);
};

class UTypedElementPrimitiveCustomDataInterface : public UInterface
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("TypedElementPrimitiveCustomDataInterface");
		return Clss;
	}

	void SetCustomDataValue(struct FScriptTypedElementHandle* InElementHandle, int32 CustomDataIndex, float CustomDataValue, bool bMarkRenderStateDirty);
	void SetCustomData(struct FScriptTypedElementHandle* InElementHandle, TArray<float>* CustomDataFloats, bool bMarkRenderStateDirty);
};

class UTypedElementSelectionInterface : public UInterface
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("TypedElementSelectionInterface");
		return Clss;
	}

	bool SelectElement(struct FScriptTypedElementHandle* InElementHandle, const struct FScriptTypedElementListProxy& InSelectionSet, struct FTypedElementSelectionOptions* InSelectionOptions);
	bool IsElementSelected(struct FScriptTypedElementHandle* InElementHandle, const struct FScriptTypedElementListProxy& InSelectionSet, struct FTypedElementIsSelectedOptions* InSelectionOptions);
	struct FScriptTypedElementHandle GetSelectionElement(struct FScriptTypedElementHandle* InElementHandle, const struct FScriptTypedElementListProxy& InCurrentSelection, enum class EETypedElementSelectionMethod InSelectionMethod);
	bool DeselectElement(struct FScriptTypedElementHandle* InElementHandle, const struct FScriptTypedElementListProxy& InSelectionSet, struct FTypedElementSelectionOptions* InSelectionOptions);
	bool CanSelectElement(struct FScriptTypedElementHandle* InElementHandle, struct FTypedElementSelectionOptions* InSelectionOptions);
	bool CanDeselectElement(struct FScriptTypedElementHandle* InElementHandle, struct FTypedElementSelectionOptions* InSelectionOptions);
	bool AllowSelectionModifiers(struct FScriptTypedElementHandle* InElementHandle, const struct FScriptTypedElementListProxy& InSelectionSet);
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
