#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class UMyPluginObject : public UObject
{
public:
	struct FMyPluginStruct                            MyStruct;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("MyPluginObject");
		return Clss;
	}
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
