#pragma once
// generated by beardumper

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{

class UVTSGameTimelineManager : public UObject
{
public:
	TArray<class UVTSPlayerTimelineSynchronizer*>     PlayerTimelineSynchronizers;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSGameTimelineManager");
		return Clss;
	}
};

class UVTSAuthorityGameTimelineManager : public UVTSGameTimelineManager
{
public:
	class UVTSFixedTimeStepTimeline*                  AuthorityFixedTimeStepTimeline;
	class UVTSFixedTimeStepTimelineAPI*               AuthorityFixedTimeStepTimelineAPI;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSAuthorityGameTimelineManager");
		return Clss;
	}
};

class UVTSPlayerTimelineSynchronizer : public UObject
{
public:
	bool                                              bHasBasis;
	uint8                                             Pad_0[0x0003];
	int32                                             Basis;
	uint8                                             Pad_1[0x0068];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSPlayerTimelineSynchronizer");
		return Clss;
	}
};

class UVTSAuthorityPlayerTimelineSynchronizer : public UVTSPlayerTimelineSynchronizer
{
public:
	class UVTSFixedTimeStepTimeline*                  AuthorityFixedTimeStepTimeline;
	class UVTSTimeShiftMonitor*                       AuthorityTimeShiftMonitor;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSAuthorityPlayerTimelineSynchronizer");
		return Clss;
	}

	void Rebase();
};

class UVTSAutonomousGameTimelineManager : public UVTSGameTimelineManager
{
public:
	class UVTSFixedTimeStepTimeline*                  AutonomousFixedTimeStepTimeline;
	class UVTSFixedTimeStepTimelineAPI*               AutonomousFixedTimeStepTimelineAPI;
	class UVTSFixedTimeStepTimeline*                  RemoteFixedTimeStepTimeline;
	class UVTSFixedTimeStepTimelineAPI*               RemoteFixedTimeStepTimelineAPI;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSAutonomousGameTimelineManager");
		return Clss;
	}
};

class UVTSAutonomousPlayerTimelineSynchronizer : public UVTSPlayerTimelineSynchronizer
{
public:
	class UVTSFixedTimeStepTimeline*                  AutonomousFixedTimeStepTimeline;
	class UVTSFixedTimeStepTimeline*                  RemoteFixedTimeStepTimeline;
	class UVTSTimeShiftMonitee*                       AutonomousTimeShiftMonitee;
	class UVTSRemoteTimeShifter*                      RemoteTimeShifter;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSAutonomousPlayerTimelineSynchronizer");
		return Clss;
	}

	void Rebase();
};

class UVTSFixedTimeStepTimeline : public UObject
{
public:
	uint8                                             Pad_0[0x0018];
	TArray<TScriptInterface<class IVTSTimeSynchronizedInterface>> TimeSynchronizedObjects;
	TMap<class UObject*, class UVTSTimeSynchronizedInterfaceBlueprintAdapter*> ObjectAdapterMap;
	TArray<struct FVTSTimeStampDelegate>              TimeStampDelegates;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSFixedTimeStepTimeline");
		return Clss;
	}
};

class UVTSFixedTimeStepTimelineAPI : public UObject
{
public:
	class UVTSFixedTimeStepTimeline*                  FixedTimeStepTimeline;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSFixedTimeStepTimelineAPI");
		return Clss;
	}

	void UnregisterTimeSynchronizedObjectBlueprint(class UObject* TimeSynchronizedObjectBlueprint);
	bool SetTimeStampDelegateBlueprint(struct FVTSTimeStampIndex* TimeStampIndex, const struct FDelegateProperty_& TimeStampActionDynamicDelegate);
	void RegisterTimeSynchronizedObjectBlueprint(class UObject* TimeSynchronizedObjectBlueprint);
	float GetRemainingRequiredSimulationTime();
	float GetInterpolationValue();
	float GetFixedTimeStepSize();
	struct FVTSTimeStampIndex GetCurrentTimeStampIndex();
};

class UVTSMoniteeTimeShiftCoreInterface : public UInterface
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSMoniteeTimeShiftCoreInterface");
		return Clss;
	}
};

class UVTSMonitorTimeShiftCoreInterface : public UInterface
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSMonitorTimeShiftCoreInterface");
		return Clss;
	}
};

class UVTSRemoteTimeShifter : public UObject
{
public:
	uint8                                             Pad_0[0x0008];
	TScriptInterface<class IVTSMonitorTimeShiftCoreInterface> MonitorCoreInterface;
	TScriptInterface<class IVTSMoniteeTimeShiftCoreInterface> MoniteeCoreInterface;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSRemoteTimeShifter");
		return Clss;
	}
};

class UVTSTAppEmulationData : public UObject
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTAppEmulationData");
		return Clss;
	}
};

class UVTSTBasicTestAppEmulationData : public UVTSTAppEmulationData
{
public:
	uint8                                             Pad_0[0x0010];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTBasicTestAppEmulationData");
		return Clss;
	}
};

class UVTSTTest : public UObject
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTTest");
		return Clss;
	}
};

class UVTSTBasicTestEnvironmentEmulatorTest : public UVTSTTest
{
public:
	struct FVTSTBasicTestEnvironmentEmulatorTrackingData TrackingData;
	TArray<class UVTSTBasicTestTestParticipant*>      Participants;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTBasicTestEnvironmentEmulatorTest");
		return Clss;
	}
};

class UVTSTBasicTestTest : public UVTSTTest
{
public:
	class UVTSTBasicTestTestParticipant*              Participant;
	uint8                                             Pad_0[0x0018];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTBasicTestTest");
		return Clss;
	}
};

class UVTSTTestParticipant : public UObject
{
public:
	class UVTSTAppEmulationData*                      AppData;
	class UVTSTTransportEmulationData*                TransportData;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTTestParticipant");
		return Clss;
	}
};

class UVTSTBasicTestTestParticipant : public UVTSTTestParticipant
{
public:
	uint8                                             Pad_0[0x0008];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTBasicTestTestParticipant");
		return Clss;
	}
};

class UVTSTTransportEmulationData : public UObject
{
public:
	class UVTSTTestParticipant*                       Destination;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTTransportEmulationData");
		return Clss;
	}
};

class UVTSTBasicTestTransportEmulationData : public UVTSTTransportEmulationData
{
public:
	uint8                                             Pad_0[0x0010];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTBasicTestTransportEmulationData");
		return Clss;
	}
};

class UVTSTClientManager : public UVTSTTestParticipant
{
public:
	class UVTSAutonomousGameTimelineManager*          AutonomousTimelineManager;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTClientManager");
		return Clss;
	}
};

class UVTSTClientPlayerTimelineSynchronizer : public UVTSTTestParticipant
{
public:
	class UVTSAutonomousPlayerTimelineSynchronizer*   AutonomousPlayerTimelineSynchronizer;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTClientPlayerTimelineSynchronizer");
		return Clss;
	}
};

class UVTSTConstantDeltaTimeAppEmulationData : public UVTSTAppEmulationData
{
public:
	uint8                                             Pad_0[0x0008];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTConstantDeltaTimeAppEmulationData");
		return Clss;
	}
};

class UVTSTConstantLatencyTransportEmulationData : public UVTSTTransportEmulationData
{
public:
	uint8                                             Pad_0[0x0010];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTConstantLatencyTransportEmulationData");
		return Clss;
	}
};

class UVTSTEnvironmentEmulator : public UObject
{
public:
	uint8                                             Pad_0[0x0018];
	TArray<class UVTSTSimulationInstruction*>         SimulationInstructions;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTEnvironmentEmulator");
		return Clss;
	}
};

class UVTSTimeShiftMonitee : public UObject
{
public:
	uint8                                             Pad_0[0x0008];
	TScriptInterface<class IVTSMoniteeTimeShiftCoreInterface> MoniteeCoreInterface;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTimeShiftMonitee");
		return Clss;
	}
};

class UVTSTimeShiftMonitor : public UObject
{
public:
	TScriptInterface<class IVTSMonitorTimeShiftCoreInterface> MonitorCoreInterface;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTimeShiftMonitor");
		return Clss;
	}
};

class UVTSTimeSynchronizedInterface : public UInterface
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTimeSynchronizedInterface");
		return Clss;
	}
};

class UVTSTimeSynchronizedInterfaceBlueprint : public UInterface
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTimeSynchronizedInterfaceBlueprint");
		return Clss;
	}

	void OnRebaseBlueprint();
	void OnPreFixedTimeStepsBlueprint(float ResidualTimeSeconds);
	void OnPostFixedTimeStepsBlueprint(float ResidualTimeSeconds);
	void OnFixedTimeStepBlueprint(struct FVTSTimeStampIndex* TimeStampIndex);
	int32 GetFixedTimeStepPriorityBlueprint();
};

class UVTSTimeSynchronizedInterfaceBlueprintAdapter : public UObject
{
public:
	uint8                                             Pad_0[0x0008];
	class UObject*                                    TimeSynchronizedBlueprintObject;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTimeSynchronizedInterfaceBlueprintAdapter");
		return Clss;
	}
};

class UVTSTServerManager : public UVTSTTestParticipant
{
public:
	class UVTSAuthorityGameTimelineManager*           AuthorityTimelineManager;
	uint8                                             Pad_0[0x0008];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTServerManager");
		return Clss;
	}
};

class UVTSTServerPlayerTimelineSynchronizer : public UVTSTTestParticipant
{
public:
	class UVTSAuthorityPlayerTimelineSynchronizer*    AuthorityPlayerTimelineSynchronizer;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTServerPlayerTimelineSynchronizer");
		return Clss;
	}
};

class UVTSTSimulationInstruction : public UObject
{
public:
	uint8                                             Pad_0[0x00D8];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTSimulationInstruction");
		return Clss;
	}
};

class UVTSTTestResult : public UObject
{
public:
	uint8                                             Pad_0[0x0028];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTTestResult");
		return Clss;
	}
};

class UVTSTVALGameObjectTest : public UObject
{
public:
	uint8                                             Pad_0[0x0008];
	class FString                                     LogPrefix;
	struct FVTSTimeStampIndex                         MostRecentTimeStampIndex;
	uint8                                             Pad_1[0x0004];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTVALGameObjectTest");
		return Clss;
	}
};

class UVTSTValTest : public UVTSTTest
{
public:
	class UVTSTServerManager*                         ServerManager;
	TArray<class UVTSTClientManager*>                 ClientManagers;
	TArray<class UVTSTServerPlayerTimelineSynchronizer*> ServerPlayers;
	TArray<class UVTSTClientPlayerTimelineSynchronizer*> ClientPlayers;
	TArray<class UVTSTVALGameObjectTest*>             ServerPlayerGameObjects;
	TArray<class UVTSTVALGameObjectTest*>             ClientPlayerGameObjects;
	struct FVTSTValTestTrackingData                   TrackingData;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSTValTest");
		return Clss;
	}
};

class UVTSVALHeartbeatQueue : public UObject
{
public:
	uint8                                             Pad_0[0x0030];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALHeartbeatQueue");
		return Clss;
	}
};

class UVTSVALMaxTimeShiftMagnitudeStrategyConfig : public UObject
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALMaxTimeShiftMagnitudeStrategyConfig");
		return Clss;
	}
};

class UVTSVALMaxTimeShiftMagnitudeStrategy : public UObject
{
public:
	class UVTSVALMaxTimeShiftMagnitudeStrategyConfig* MaxTimeShiftMagnitudeStrategyConfig;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALMaxTimeShiftMagnitudeStrategy");
		return Clss;
	}
};

class UVTSVALMoniteeTimeShiftCoreConfig : public UObject
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALMoniteeTimeShiftCoreConfig");
		return Clss;
	}
};

class UVTSVALMoniteeTimeShiftCore : public UObject
{
public:
	uint8                                             Pad_0[0x0008];
	class UVTSVALMoniteeTimeShiftCoreConfig*          MoniteeTimeShiftCoreConfig;
	class UVTSVALMaxTimeShiftMagnitudeStrategy*       MaxTimeShiftMagnitudeStrategy;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALMoniteeTimeShiftCore");
		return Clss;
	}
};

class UVTSVALMonitorTimeShiftCoreConfig : public UObject
{
public:
	uint8                                             Pad_0[0x0010];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALMonitorTimeShiftCoreConfig");
		return Clss;
	}
};

class UVTSVALMonitorTimeShiftCore : public UObject
{
public:
	uint8                                             Pad_0[0x0008];
	class UVTSVALMonitorTimeShiftCoreConfig*          MonitorTimeShiftCoreConfig;
	class UVTSVALMaxTimeShiftMagnitudeStrategy*       MaxTimeShiftMagnitudeStrategy;
	class UVTSVALTimeShiftMonitorQueueEvaluationStrategy* TimeShiftMonitorQueueEvaluationStrategy;
	class UVTSVALTimeShiftMonitorQueueSizeTargetStrategy* TimeShiftMonitorQueueSizeTargetStrategy;
	class UVTSVALTimeShiftMonitorRebaseStrategy*      TimeShiftMonitorRebaseStrategy;
	uint8                                             Pad_1[0x0008];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALMonitorTimeShiftCore");
		return Clss;
	}
};

class UVTSVALNoOpTimeShiftCore : public UObject
{
public:
	uint8                                             Pad_0[0x0010];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALNoOpTimeShiftCore");
		return Clss;
	}
};

class UVTSVALRichCurveMaxTimeShiftMagnitudeStrategyConfig : public UVTSVALMaxTimeShiftMagnitudeStrategyConfig
{
public:
	uint8                                             Pad_0[0x0018];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALRichCurveMaxTimeShiftMagnitudeStrategyConfig");
		return Clss;
	}
};

class UVTSVALRichCurveMaxTimeShiftMagnitudeStrategy : public UVTSVALMaxTimeShiftMagnitudeStrategy
{
public:
	class UVTSVALRichCurveMaxTimeShiftMagnitudeStrategyConfig* RichCurveMaxTimeShiftMagnitudeStrategyConfig;
	struct FRuntimeFloatCurve                         ShiftApplyRateCurve;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALRichCurveMaxTimeShiftMagnitudeStrategy");
		return Clss;
	}
};

class UVTSVALMonitorTimeShiftCorePreset : public UObject
{
public:
	class UVTSVALMonitorTimeShiftCoreConfig*          MonitorTimeShiftCoreConfig;
	class UVTSVALRichCurveMaxTimeShiftMagnitudeStrategy* MaxTimeShiftMagnitudeStrategy;
	class UVTSVALTimeShiftMonitorFixedQueueSizeTargetStrategy* QueueSizeTargetStrategy;
	class UVTSVALTimeShiftMonitorMinAbsDistanceQueueEvaluationStrategy* QueueEvaluationStrategy;
	class UVTSVALTimeShiftMonitorOverqueuedFailedInsertionRebaseStrategy* RebaseStrategy;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALMonitorTimeShiftCorePreset");
		return Clss;
	}
};

class UVTSVALMoniteeTimeShiftCorePreset : public UObject
{
public:
	class UVTSVALMoniteeTimeShiftCoreConfig*          MoniteeTimeShiftCoreConfig;
	class UVTSVALRichCurveMaxTimeShiftMagnitudeStrategy* MaxTimeShiftMagnitudeStrategy;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALMoniteeTimeShiftCorePreset");
		return Clss;
	}
};

class UVTSVALRemoteTimeShifterMonitorTimeShiftCorePreset : public UObject
{
public:
	class UVTSVALMonitorTimeShiftCoreConfig*          MonitorTimeShiftCoreConfig;
	class UVTSVALRichCurveMaxTimeShiftMagnitudeStrategy* MaxTimeShiftMagnitudeStrategy;
	class UVTSVALTimeShiftMonitorFixedQueueSizeTargetStrategy* QueueSizeTargetStrategy;
	class UVTSVALTimeShiftMonitorMinAbsDistanceQueueEvaluationStrategy* QueueEvaluationStrategy;
	class UVTSVALTimeShiftMonitorOverqueuedFailedInsertionRebaseStrategy* RebaseStrategy;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALRemoteTimeShifterMonitorTimeShiftCorePreset");
		return Clss;
	}
};

class UVTSVALRemoteTimeShifterMoniteeTimeShiftCorePreset : public UObject
{
public:
	class UVTSVALMoniteeTimeShiftCoreConfig*          MoniteeTimeShiftCoreConfig;
	class UVTSVALRichCurveMaxTimeShiftMagnitudeStrategy* MaxTimeShiftMagnitudeStrategy;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALRemoteTimeShifterMoniteeTimeShiftCorePreset");
		return Clss;
	}
};

class UVTSVALTimeShiftMonitorQueueSizeTargetStrategyConfig : public UObject
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALTimeShiftMonitorQueueSizeTargetStrategyConfig");
		return Clss;
	}
};

class UVTSVALTimeShiftMonitorFixedQueueSizeTargetStrategyConfig : public UVTSVALTimeShiftMonitorQueueSizeTargetStrategyConfig
{
public:
	uint8                                             Pad_0[0x0008];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALTimeShiftMonitorFixedQueueSizeTargetStrategyConfig");
		return Clss;
	}
};

class UVTSVALTimeShiftMonitorQueueSizeTargetStrategy : public UObject
{
public:
	class UVTSVALTimeShiftMonitorQueueSizeTargetStrategyConfig* TimeShiftMonitorQueueSizeTargetStrategyConfig;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALTimeShiftMonitorQueueSizeTargetStrategy");
		return Clss;
	}
};

class UVTSVALTimeShiftMonitorFixedQueueSizeTargetStrategy : public UVTSVALTimeShiftMonitorQueueSizeTargetStrategy
{
public:
	class UVTSVALTimeShiftMonitorFixedQueueSizeTargetStrategyConfig* TimeShiftMonitorFixedQueueSizeTargetStrategyConfig;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALTimeShiftMonitorFixedQueueSizeTargetStrategy");
		return Clss;
	}
};

class UVTSVALTimeShiftMonitorQueueEvaluationStrategyConfig : public UObject
{
public:
	uint8                                             Pad_0[0x0018];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALTimeShiftMonitorQueueEvaluationStrategyConfig");
		return Clss;
	}
};

class UVTSVALTimeShiftMonitorMinAbsDistanceQueueEvaluationStrategyConfig : public UVTSVALTimeShiftMonitorQueueEvaluationStrategyConfig
{
public:
	uint8                                             Pad_0[0x0010];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALTimeShiftMonitorMinAbsDistanceQueueEvaluationStrategyConfig");
		return Clss;
	}
};

class UVTSVALTimeShiftMonitorQueueEvaluationStrategy : public UObject
{
public:
	class UVTSVALTimeShiftMonitorQueueEvaluationStrategyConfig* TimeShiftMonitorQueueEvaluationStrategyConfig;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALTimeShiftMonitorQueueEvaluationStrategy");
		return Clss;
	}
};

class UVTSVALTimeShiftMonitorMinAbsDistanceQueueEvaluationStrategy : public UVTSVALTimeShiftMonitorQueueEvaluationStrategy
{
public:
	class UVTSVALTimeShiftMonitorMinAbsDistanceQueueEvaluationStrategyConfig* TimeShiftMonitorMinAbsDistanceQueueEvaluationStrategyConfig;
	class UVTSVALHeartbeatQueue*                      HeartbeatQueue;
	uint8                                             Pad_0[0x0028];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALTimeShiftMonitorMinAbsDistanceQueueEvaluationStrategy");
		return Clss;
	}
};

class UVTSVALTimeShiftMonitorRebaseStrategyConfig : public UObject
{
public:

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALTimeShiftMonitorRebaseStrategyConfig");
		return Clss;
	}
};

class UVTSVALTimeShiftMonitorOverqueuedFailedInsertionRebaseStrategyConfig : public UVTSVALTimeShiftMonitorRebaseStrategyConfig
{
public:
	uint8                                             Pad_0[0x0010];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALTimeShiftMonitorOverqueuedFailedInsertionRebaseStrategyConfig");
		return Clss;
	}
};

class UVTSVALTimeShiftMonitorRebaseStrategy : public UObject
{
public:
	class UVTSVALTimeShiftMonitorRebaseStrategyConfig* TimeShiftMonitorRebaseStrategyConfig;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALTimeShiftMonitorRebaseStrategy");
		return Clss;
	}
};

class UVTSVALTimeShiftMonitorOverqueuedFailedInsertionRebaseStrategy : public UVTSVALTimeShiftMonitorRebaseStrategy
{
public:
	class UVTSVALTimeShiftMonitorOverqueuedFailedInsertionRebaseStrategyConfig* TimeShiftMonitorOverqueuedFailedInsertionRebaseStrategyConfig;
	class UVTSVALHeartbeatQueue*                      HeartbeatQueue;
	uint8                                             Pad_0[0x0008];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALTimeShiftMonitorOverqueuedFailedInsertionRebaseStrategy");
		return Clss;
	}
};

class UVTSVALTimeShiftMonitorRemoteDelayQueueSizeTargetStrategyConfig : public UVTSVALTimeShiftMonitorQueueSizeTargetStrategyConfig
{
public:
	uint8                                             Pad_0[0x0020];

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALTimeShiftMonitorRemoteDelayQueueSizeTargetStrategyConfig");
		return Clss;
	}
};

class UVTSVALTimeShiftMonitorRemoteDelayQueueSizeTargetStrategy : public UVTSVALTimeShiftMonitorQueueSizeTargetStrategy
{
public:
	class UVTSVALTimeShiftMonitorRemoteDelayQueueSizeTargetStrategyConfig* TimeShiftMonitorFixedQueueSizeTargetStrategyConfig;

public:
	static class UClass* StaticClass()
	{
		static class UClass* Clss = nullptr;
		if (Clss == nullptr)
			Clss = SDK::Rt::FindClass("VTSVALTimeShiftMonitorRemoteDelayQueueSizeTargetStrategy");
		return Clss;
	}
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
